### ISSUE TITLE
360 T7 cpu 显示频率降低

### ISSUE THREAD

**Issue by liyiranlab** [immortalwrt/immortalwrt#1017]
### Describe the bug

360 T7 显示cpu 频率1300Mhz随机降低数值，有时候会低到1000Mhz+。

### ImmortalWrt version

r26795-482669f7f2

### ImmortalWrt target/subtarget

 mediatek/filogic

### Device

Qihoo 360T7 (custom U-Boot layout)

### Image kind

Official downloaded image

### Steps to reproduce

手机客户端开5Gwifi测速，浏览器打开路由器首页，会看到360 T7 显示cpu 频率1300Mhz随机降低数值，有时候会低到1000Mhz+。

### Actual behaviour

手机客户端开5G wifi测速，路由器首页会看到360 T7 显示cpu 频率1300Mhz随机降低数值，有时候会低到1000Mhz+

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
mhz 计算问题，mt7981 的时钟频率是固定的。
