### ISSUE TITLE
有关仓库简介中的“中国大陆(mainland China)”英文翻译错误。

### ISSUE THREAD

**Issue by cwuom** [immortalwrt/immortalwrt#1028]
"_An opensource OpenWrt variant for mainland China users._"中的"mainland China"翻译错误，应改成"**Chinese mainland**"或"**the mainland of China**"又或是"**China's mainland**"。希望可以更正此问题，在国际传播中不应出现这种错误用法

**Comment by xlighting2017** [comment]
<img width="369" alt="image" src="https://github.com/immortalwrt/immortalwrt/assets/25970065/9068ad45-1b25-4d22-b5b7-d90b33285431">


https://english.www.gov.cn/services/202304/18/content_WS5e04749bc6d0554996894a1a.html
<img width="756" alt="image" src="https://github.com/immortalwrt/immortalwrt/assets/25970065/17ea623d-2ef7-4979-8f27-ba290971f4f3">

http://au.china-embassy.gov.cn/eng/lsfw_12/vc/201305/t20130509_1002348.htm
<img width="671" alt="image" src="https://github.com/immortalwrt/immortalwrt/assets/25970065/04fd69bb-0e7e-44b7-91cc-ec9803dd0d6a">

https://en.safea.gov.cn/photonews/200609/t20060919_36160.htm
<img width="695" alt="image" src="https://github.com/immortalwrt/immortalwrt/assets/25970065/1248a364-9762-48c1-8f96-3af583116619">

http://en.moe.gov.cn/news/press_releases/201909/t20190930_401810.html
<img width="721" alt="image" src="https://github.com/immortalwrt/immortalwrt/assets/25970065/7a01af26-5f00-492a-9d09-3cdfda397478">

**Comment by Fangliding** [comment]
大哥第一天上网吗 中国大陆基本都是怎么翻译的

**Comment by MarksonHon** [comment]
英文写地名就是从小地名往大地名写，mainland China 符合英语语境

**Comment by 1715173329** [comment]
以上。

**Comment by cherinyy** [comment]
> 在国际传播中不应出现这种错误用法

对于普通人而言，只要知道是中国大陆（内地）就行，纠结“Mainland China”还是“the Chinese mainland”实则是陷入了政治陷阱之中。我自己会采用“the Chinese mainland”，但我不会去改变别人的用法。

就好比这几天所谓的“究竟是账号还是帐号”：

> 最新一篇为2022年4月30日。中国社会科学院语言研究所新型辞书编辑室主任储泽祥表示，《现代汉语词典》第7版只收“账号”，不收“帐号”。《现代汉语词典》第7版和《新华字典》第12版，都在“帐”字条目下注明表示账簿、账目时，“旧同‘账’”。也就是说，“帐号”是旧时用法，现在应该用“账号”。

普通人知道是什么就行了，我为什么非要跟随你《现代汉语词典》和《新华字典》的说明？

然后搞得所有公司开始更正自己的文本，真的无语……另一种形式的文字狱罢了。
