### ISSUE TITLE
PVE虚机机在概览页的端口状态不显示虚拟网卡

### ISSUE THREAD

**Issue by shenlijun** [immortalwrt/immortalwrt#1034]
### Describe the bug

直通进来的实体网卡没有这个问题。

### ImmortalWrt version

r26858-63caa6875f

### ImmortalWrt target/subtarget

x86/64

### Device

QEMU Standard PC (Q35 + ICH9, 2009)

### Image kind

Official downloaded image

### Steps to reproduce

PVE8安装wrt虚拟机,给它一个虚拟网卡就可以复现，我有4台服务器都是同样的问题

### Expected behaviour

概览页可以显示所有网口，不管是否是虚拟的

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
虚拟网卡缺少必要的数据，无法显示。

**Comment by shenlijun** [comment]
> 虚拟网卡缺少必要的数据，无法显示。

是新版luci的问题么？刚才又试了下LEAN的固件，是可以显示的

**Comment by 1715173329** [comment]
lean 的 autocore 与我们的实现方式不同，如需显示可以继续用 lean 的固件。

**Comment by shenlijun** [comment]
> lean 的 autocore 与我们的实现方式不同，如需显示可以继续用 lean 的固件。

我看看月底以后有空，试试参考下那边的代码，能不能搞个PR

**Comment by 1715173329** [comment]
不必了，这部分的实现不会改动。
