### ISSUE TITLE
diffconfig.sh使用报错

### ISSUE THREAD

**Issue by Baiduyun28** [immortalwrt/immortalwrt#1040]
### Describe the bug

在Actions里进行make menuconfig配置保存.config后，再执行./scripts/diffconfig.sh > diff.config命令执行报错：
./scripts/diffconfig.sh: 11: ./scripts/config/conf: not found
can't open file 'tmp/.diffconfig.stage1' at ./scripts/kconfig.pl line 32.
./scripts/diffconfig.sh: 13: ./scripts/config/conf: not found
can't open file 'tmp/.diffconfig.stage2' at ./scripts/kconfig.pl line 32.

### ImmortalWrt version

21.02

### ImmortalWrt target/subtarget

MT7621

### Device

HC5962

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
user configuration issue. Move to discussion.
