### ISSUE TITLE
SYSUPGRADE not working

### ISSUE THREAD

**Issue by naveen1hot** [immortalwrt/immortalwrt#1042]
### Describe the bug

Hi Team,
Every time while I trying for SYSUPGRADE via luci it's taking too long without results. While checking with url https://sysupgrade.immortalwrt.org getting access error as below.
![Screenshot_20230817-075623](https://github.com/immortalwrt/immortalwrt/assets/67212860/c6eb9f6f-ae62-4af6-85d6-cfa3ee74ae13)

Request kindly help with error fix.

### ImmortalWrt version

21.05.0.rc3

### ImmortalWrt target/subtarget

Mt7621

### Device

Xiaomi Mi Router 4A Gigabit Edition

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
This is your own (network) issue. The only reason you saw this page is you, or the IP you used (VPN, Proxy or whatever), were trying to abuse our services.
