### ISSUE TITLE
toolchain-aarch64_cortex-a53_gcc-12.3.0_musl 的工具无法编译

### ISSUE THREAD

**Issue by Potterli20** [immortalwrt/immortalwrt#1088]
### Describe the bug

/home/potter/immortalwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-12.3.0_musl/include/string.h:99:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
   99 | char *basename();
      | ^~~~
./readelf.c: In function 'fseek64':
./readelf.c:372:3: error: unknown type name 'off64_t'; did you mean 'off_t'?
  372 |   off64_t o = offset;
      |   ^~~~~~~
      |   off_t
./readelf.c:378:10: warning: implicit declaration of function 'fseeko64'; did you mean 'fseek64'? [-Wimplicit-function-declaration]
  378 |   return fseeko64 (stream, o, whence);
      |          ^~~~~~~~
      |          fseek64
make[8]: *** [Makefile:1929: readelf.o] Error 1

### ImmortalWrt version

23.05

### ImmortalWrt target/subtarget

23.05

### Device

nx 30pro

### Image kind

Official downloaded image

### Steps to reproduce

[log.txt](https://github.com/immortalwrt/immortalwrt/files/12908338/log.txt)

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
没有环境信息，log.txt 没有任何有效信息。
只能假定你没有使用我们推荐的构建环境。

**Comment by MarksonHon** [comment]
@Potterli20 建议是根据 OpenWrt 上的教程，虚拟机起一个 Debian 或 Alpine 编译

**Comment by zheshifandian** [comment]
我用的wsl2的ubuntu-20.04

**Comment by xlighting2017** [comment]
先详细描述一下， 你的环境 是怎么配置的， 有没有按照 readme 里面的步骤来
以及：
![image](https://github.com/immortalwrt/immortalwrt/assets/25970065/0d7abb6d-ff2c-42de-8b0e-016f996a40a6)

**Comment by warkcod** [comment]
@Potterli20 po 请教下，如何修改BINUTILS_VERSION？谢谢
强制修改.config里的版本信息后，make defconfig或make oldconfig都会被重置为2.42版本
