### ISSUE TITLE
更新源码后出错 net/netfilter/nf_tables_core.o: file not recognized: file format not recognized

### ISSUE THREAD

**Issue by mitsukileung** [immortalwrt/immortalwrt#1089]
### Describe the bug

  CALL    scripts/checksyscalls.sh
  CALL    scripts/atomic/check-atomics.sh
  DESCEND objtool
  DESCEND bpf/resolve_btfids
  CHK     include/generated/compile.h
  LD [M]  net/netfilter/nf_tables.o
net/netfilter/nf_tables_core.o: file not recognized: file format not recognized
make[7]: *** [scripts/Makefile.build:486: net/netfilter/nf_tables.o] Error 1
make[6]: *** [scripts/Makefile.build:552: net/netfilter] Error 2
make[5]: *** [Makefile:1908: net] Error 2
make[5]: Leaving directory '/home/koysuke/immortalwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.15.135'
make[4]: *** [Makefile:29: /home/koysuke/immortalwrt/build_dir/target-x86_64_musl/linux-x86_64/linux-5.15.135/.modules] Error 2
make[4]: Leaving directory '/home/koysuke/immortalwrt/target/linux/x86'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/home/koysuke/immortalwrt/target/linux'
time: target/linux/compile#13.46#4.73#18.22
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:30: target/linux/compile] Error 1
make[2]: Leaving directory '/home/koysuke/immortalwrt'
make[1]: *** [target/Makefile:23: /home/koysuke/immortalwrt/staging_dir/target-x86_64_musl/stamp/.target_compile] Error 2

### ImmortalWrt version

Latest

### ImmortalWrt target/subtarget

x86_generic

### Device

X86

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
Run make clean first
