### ISSUE TITLE
200-Implements-AES-and-GCM-with-ARMv8-Crypto-Extensions.patch Patch failed!

### ISSUE THREAD

**Issue by mitsukileung** [immortalwrt/immortalwrt#1090]
### Describe the bug

Applying /workdir/openwrt/package/libs/mbedtls/patches/200-Implements-AES-and-GCM-with-ARMv8-Crypto-Extensions.patch using plaintext: 
patching file ChangeLog.d/armv8_crypto_extensions.txt
patching file include/mbedtls/armv8ce_aes.h
patching file include/mbedtls/check_config.h
patching file include/mbedtls/config.h
Hunk #2 succeeded at 2472 (offset 97 lines).
patching file library/aes.c
Hunk #2 FAILED at 1042.
1 out of 2 hunks FAILED -- saving rejects to file library/aes.c.rej
patching file library/armv8ce_aes.c
patching file library/CMakeLists.txt
patching file library/gcm.c
Hunk #1 succeeded at 43 (offset 1 line).
Hunk #2 succeeded at 85 (offset 1 line).
Hunk #3 succeeded at 201 (offset 1 line).
patching file library/Makefile
patching file library/version_features.c
Hunk #1 succeeded at 636 (offset 12 lines).
Patch failed!  Please fix /workdir/openwrt/package/libs/mbedtls/patches/200-Implements-AES-and-GCM-with-ARMv8-Crypto-Extensions.patch!
make[3]: *** [Makefile:173: /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/mbedtls-2.28.5/.prepared_38847705ebce75249344c5ae87702445_6664517399ebbbc92a37c5bb081b5c53] Error 1
make[3]: Leaving directory '/workdir/openwrt/package/libs/mbedtls'
time: package/libs/mbedtls/compile#0.21#0.14#0.35
    ERROR: package/libs/mbedtls failed to build.
make[2]: *** [package/Makefile:120: package/libs/mbedtls/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:114: /workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make: *** [/workdir/openwrt/include/toplevel.mk:232: world] Error 2
Error: Process completed with exit code 2.

### ImmortalWrt version

Latest

### ImmortalWrt target/subtarget

ipq807x

### Device

Ax3600 Ax6

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
Pull source.
