### ISSUE TITLE
Firmware Selector custom build Snapshot Generic x86/64 failed

### ISSUE THREAD

**Issue by Ricky-Hao** [immortalwrt/immortalwrt#1103]
### Describe the bug

Trigger build with default packages on Firmware Selector: [https://firmware-selector.immortalwrt.org/?version=SNAPSHOT&target=x86%2F64&id=generic
](https://firmware-selector.immortalwrt.org/?version=SNAPSHOT&target=x86%2F64&id=generic
)

And build return error.
![image](https://github.com/immortalwrt/immortalwrt/assets/14084342/d39d9ccd-9709-4440-8b27-46482edde419)

### ImmortalWrt version

r28008-3f9bf2c41b

### ImmortalWrt target/subtarget

x86/64

### Device

Microsoft Corporation Virtual Machine

### Image kind

Official downloaded image

### Steps to reproduce

Trigger build with default packages on Firmware Selector: [https://firmware-selector.immortalwrt.org/?version=SNAPSHOT&target=x86%2F64&id=generic
](https://firmware-selector.immortalwrt.org/?version=SNAPSHOT&target=x86%2F64&id=generic
)

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
upstream issue, still under investigation

**Comment by 1715173329** [comment]
Upstream fixed.
