### ISSUE TITLE
23.05.1流量分载(Flow offloading)不生效导致网速变慢

### ISSUE THREAD

**Issue by microka** [immortalwrt/immortalwrt#1117]
### Describe the bug

![2023-11-21_044312](https://github.com/immortalwrt/immortalwrt/assets/490351/3c7c75d8-cfc3-47a3-a8d6-59fa8f90682a)
J4125 i225-V(b6)*6
刷入 immortalwrt-23.05.1-x86-64-generic-squashfs-combined-efi.img.gz 固件，系统版本 ImmortalWrt 23.05.1 r27304-31bc47589e

![2023-11-21_041059](https://github.com/immortalwrt/immortalwrt/assets/490351/2da35a38-d32b-493a-b9c0-3666a8c49b6a)
流量分载(Flow offloading)为默认开启

只配置一条电信 2000M wan，由 ImmortalWrt PPPoE 拨号，安装 sysstat 软件包，ssh 使用 `mpstat -P ALL 1` 观察 CPU 实时占用

![2023-11-21_043656_telecom](https://github.com/immortalwrt/immortalwrt/assets/490351/e44b702d-e151-4676-8809-211f4122bf5b)
[电信官方IPv4测速](https://10000.gd.cn/#/speed)，下行能跑满2000M，CPU占用60-90%

![2023-11-21_043745_ustc6](https://github.com/immortalwrt/immortalwrt/assets/490351/b5705ecc-eea8-4a3a-819e-b5e98a5762cb)
[中科大IPv6测速](http://test6.ustc.edu.cn/)，下行只能跑到1300+M，CPU占用40-70%

![2023-11-21_043825_neu6](https://github.com/immortalwrt/immortalwrt/assets/490351/f7611e2f-0244-429a-95d9-fcdc7a4abfc8)
[东北大学IPv6测速](https://speed.neu6.edu.cn/)，下行只能跑到1100+M，CPU占用40-60%

![2023-11-21_034829](https://github.com/immortalwrt/immortalwrt/assets/490351/bf833b95-fb98-4211-b281-03c22360df61)
作为对照，同设备刷入 immortalwrt-21.02.7-x86-64-generic-squashfs-combined-efi.img.gz 固件，系统版本 ImmortalWrt 21.02.7 r20074-a8bbadefaf
![2023-11-21_035603_TurboACC](https://github.com/immortalwrt/immortalwrt/assets/490351/e1c14987-ceef-49ad-9b21-fc13b8e9e2a2)
流量分载(Flow offloading)为默认开启
其余配置与 ImmortalWrt 23.05.1 保持一致，进行测速

![2023-11-21_042524_telecom](https://github.com/immortalwrt/immortalwrt/assets/490351/2ddbc3e0-e295-421e-ad95-3067078b7c2e)
[电信官方IPv4测速](https://10000.gd.cn/#/speed)，下行能跑满2000M，CPU占用20-40%

![2023-11-21_042813_ustc6](https://github.com/immortalwrt/immortalwrt/assets/490351/c2af6e89-cd4a-42f5-9768-5bdf719db34f)
[中科大IPv6测速](http://test6.ustc.edu.cn/)，下行能跑满2000M，CPU占用20-40%

![2023-11-21_042700_neu6](https://github.com/immortalwrt/immortalwrt/assets/490351/67653ed2-4c9c-4dc3-96b9-ab535acc86b7)
[东北大学IPv6测速](https://speed.neu6.edu.cn/)，下行能跑满2000M，CPU占用20-40%

经搜索找到 https://github.com/openwrt/openwrt/issues/10224 ，从讨论中可知这是 OpenWrt 从 22.03 开始的 bug，在最新的 OpenWrt 23.05.2 中仍未修复（那个issue里面还在讨论，讨论中也给出了临时解决方法，但我试了不成功），不知 ImmortalWrt 这边能否进行修复呢？

### ImmortalWrt version

r27304-31bc47589e

### ImmortalWrt release

23.05.1

### ImmortalWrt target/subtarget

x86/64

### Device

J4125 i225-V(b6)*6

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by microka** [comment]
> [这个补丁](https://github.com/openwrt/openwrt/issues/10224#issuecomment-1471911970)是有效的

已经重新部署好了 ImmortalWrt 21.02.7，希望这个补丁能整合进 ImmortalWrt 下个版本。

**Comment by ximiTech** [comment]
> [这个补丁](https://github.com/openwrt/openwrt/issues/10224#issuecomment-1471911970)是有效的


大佬能否给出详细的代码，例如应该在源代码的哪个目录下新增此patch文件，以及patch文件的具体内容？

**Comment by skefy** [comment]
同样关注这个问题。

**Comment by 1715173329** [comment]
patched.
