### ISSUE TITLE
MT7981编译错误

### ISSUE THREAD

**Issue by LinChiQ** [immortalwrt/immortalwrt#1121]
### Describe the bug

make[5]: Entering directory '/home/late/immortalwrt/build_dir/host/mpfr-4.2.0'
make[6]: Entering directory '/home/late/immortalwrt/build_dir/host/mpfr-4.2.0'
make[6]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/home/late/immortalwrt/staging_dir/host/share/doc/mpfr'
 /usr/bin/mkdir -p '/home/late/immortalwrt/staging_dir/host/lib/pkgconfig'
 /home/late/immortalwrt/staging_dir/host/bin/install -c -m 644 mpfr.pc '/home/late/immortalwrt/staging_dir/host/lib/pkgconfig'
 /usr/bin/mkdir -p '/home/late/immortalwrt/staging_dir/host/share/doc/mpfr/examples'
 /home/late/immortalwrt/staging_dir/host/bin/install -c -m 644  examples/ReadMe examples/can_round.c examples/divworst.c examples/rndo-add.c examples/sample.c examples/threads.c examples/version.c '/home/late/immortalwrt/staging_dir/host/share/doc/mpfr/examples'
 /home/late/immortalwrt/staging_dir/host/bin/install -c -m 644  AUTHORS BUGS COPYING COPYING.LESSER NEWS TODO '/home/late/immortalwrt/staging_dir/host/share/doc/mpfr/.'
make[6]: Leaving directory '/home/late/immortalwrt/build_dir/host/mpfr-4.2.0'
make[5]: Leaving directory '/home/late/immortalwrt/build_dir/host/mpfr-4.2.0'
make[4]: Leaving directory '/home/late/immortalwrt/build_dir/host/mpfr-4.2.0'
mkdir -p /home/late/immortalwrt/staging_dir/host/stamp
touch /home/late/immortalwrt/build_dir/host/mpfr-4.2.0/.built
touch /home/late/immortalwrt/staging_dir/host/stamp/.mpfr_installed
make[3]: Leaving directory '/home/late/immortalwrt/tools/mpfr'
time: tools/mpfr/compile#72.96#185.01#21719.33
make[2]: Leaving directory '/home/late/immortalwrt'
make[1]: *** [tools/Makefile:224: /home/late/immortalwrt/staging_dir/host/stamp/.tools_compile_nyyynyynnnyyyyynyyyyyyynyyynnnynyynnynnyyyyyyyyyyyyyyyynynynnyyyyyyy] Error 2
make[1]: Leaving directory '/home/late/immortalwrt'
make: *** [/home/late/immortalwrt/include/toplevel.mk:232: world] Error 2

### ImmortalWrt version

23.05

### ImmortalWrt release

23.05

### ImmortalWrt target/subtarget

MediaTek Ralink ARM

### Device

Qihoo 360 T7(custom uboot layout)

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by xlighting2017** [comment]
what you have done before the error, we need every detail step and a Full log

otherwise you get nothing.

no doctor can make prescription with just the last few lines on your  Medical record.
