### ISSUE TITLE
u-boot-2023.07.02/.built] Error 2

### ISSUE THREAD

**Issue by xiaobaishu1** [immortalwrt/immortalwrt#1125]
### Describe the bug

  BINMAN  .binman_stamp
Traceback (most recent call last):
  File "/home/openwrt/immortalwrt/build_dir/target-aarch64_generic_musl/u-boot-fastrhino-r66s-rk3568/u-boot-2023.07.02/tools/binman/control.py", line 11, in <module>
    import importlib.resources
ModuleNotFoundError: No module named 'importlib.resources'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/binman/binman", line 46, in <module>
    from binman import control
  File "/home/openwrt/immortalwrt/build_dir/target-aarch64_generic_musl/u-boot-fastrhino-r66s-rk3568/u-boot-2023.07.02/tools/binman/control.py", line 14, in <module>
    import importlib_resources
ModuleNotFoundError: No module named 'importlib_resources'
Makefile:1111: recipe for target '.binman_stamp' failed
make[4]: *** [.binman_stamp] Error 1
make[4]: Leaving directory '/home/openwrt/immortalwrt/build_dir/target-aarch64_generic_musl/u-boot-fastrhino-r66s-rk3568/u-boot-2023.07.02'
Makefile:242: recipe for target '/home/openwrt/immortalwrt/build_dir/target-aarch64_generic_musl/u-boot-fastrhino-r66s-rk3568/u-boot-2023.07.02/.built' failed
make[3]: *** [/home/openwrt/immortalwrt/build_dir/target-aarch64_generic_musl/u-boot-fastrhino-r66s-rk3568/u-boot-2023.07.02/.built] Error 2
make[3]: Leaving directory '/home/openwrt/immortalwrt/package/boot/uboot-rockchip'
time: package/boot/uboot-rockchip/fastrhino-r66s-rk3568/compile#52.44#8.27#60.69
    ERROR: package/boot/uboot-rockchip failed to build (build variant: fastrhino-r66s-rk3568).
package/Makefile:126: recipe for target 'package/boot/uboot-rockchip/compile' failed
make[2]: *** [package/boot/uboot-rockchip/compile] Error 1
make[2]: Leaving directory '/home/openwrt/immortalwrt'
package/Makefile:122: recipe for target '/home/openwrt/immortalwrt/staging_dir/target-aarch64_generic_musl/stamp/.package_compile' failed
make[1]: *** [/home/openwrt/immortalwrt/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/openwrt/immortalwrt'
/home/openwrt/immortalwrt/include/toplevel.mk:230: recipe for target 'world' failed

### ImmortalWrt version

23.05

### ImmortalWrt release

最新

### ImmortalWrt target/subtarget

无

### Device

电牛子R66S

### Image kind

Official downloaded image

### Steps to reproduce

感觉是缺少什么依赖了！

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
如果您觉得您的时间宝贵到连谷歌一下都是一种浪费，那么对于我们而言也等同。
