### ISSUE TITLE
NanoPi R5C WiFi PCI not detected

### ISSUE THREAD

**Issue by GektorUA** [immortalwrt/immortalwrt#1132]
### Describe the bug

When boot from built-in EMMC with ImmortalWrt there is no m.2 WiFi detected:

```
lspci
0000:00:00.0 PCI bridge: Rockchip Electronics Co., Ltd RK3568 Remote Signal Processor (rev 01)
0001:10:00.0 PCI bridge: Rockchip Electronics Co., Ltd RK3568 Remote Signal Processor (rev 01)
0001:11:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8125 2.5GbE Controller (rev 05)
0002:20:00.0 PCI bridge: Rockchip Electronics Co., Ltd RK3568 Remote Signal Processor (rev 01)
0002:21:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8125 2.5GbE Controller (rev 05)
```

But when i am force to boot from MicroSD with FriendlyWRT with MASK button pressed m.2 WiFi detected:

```
lspci
0000:00:00.0 PCI bridge: Rockchip Electronics Co., Ltd RK3568 Remote Signal Processor (rev 01)
0000:01:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8821CE 802.11ac PCIe Wireless Network Adapter
0001:10:00.0 PCI bridge: Rockchip Electronics Co., Ltd RK3568 Remote Signal Processor (rev 01)
0001:11:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8125 2.5GbE Controller (rev 05)
0002:20:00.0 PCI bridge: Rockchip Electronics Co., Ltd RK3568 Remote Signal Processor (rev 01)
0002:21:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8125 2.5GbE Controller (rev 05)
```

Then, if do reboot in FriendlyWRT, system will boot again from EMMC with ImmortalWrt and m.2 WiFi starts works until power cycle (off/on) device.

I have try 3 different m.2 WiFi cards that working in FriendlyWrt but did not detected in ImmortalWrt, seems there is need to switch on PCI bus in ImmortalWrt for m.2?

### ImmortalWrt version

r28491-d60186f9a9

### ImmortalWrt release

SNAPSHOT

### ImmortalWrt target/subtarget

rockchip/armv8

### Device

FriendlyElec NanoPi R5C

### Image kind

Official downloaded image

### Steps to reproduce

Boot from built-in EMMC with ImmortalWrt and there is no m.2 WiFi detected, then force to boot from MicroSD with FriendlyWRT with MASK button pressed, when system boots up - reboot by GUI, system will automatically boot from EMMC with ImmortalWrt and m.2 WiFi starts works until power cycle (off/on) device.

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
https://github.com/immortalwrt/immortalwrt/blob/d60186f9a9d5e61a27e3665a157e18a3aa34a37c/target/linux/rockchip/patches-6.1/004-v6.4-arm64-dts-rockchip-Add-FriendlyARM-NanoPi-R5C.patch#L143

change `pcfg_pull_up` to `pcfg_output_high` and retry.

**Comment by 1715173329** [comment]
I just remembered another user is using m.2 slot with a MT7922 chip and it works smoothy.

The driver for rtl8821ce is not included by default, so you need to install it by yourself - along with the firmware.

**Comment by 1715173329** [comment]
btw, always, get away from realtek craps

**Comment by 1715173329** [comment]
Unfortunately I can't reproduce this problem after wasting $2 for a rtl8822ce crap.

> $ lspci
> 0000:01:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8822CE 802.11ac PCIe Wireless Network Adapter


> $ lsusb
Bus 003 Device 002: ID 0bda:b00c Realtek  Bluetooth Radio

I'm booting from eMMC.

You may probably check your kernel log.

**Comment by BoboYaung** [comment]
能不能教教我怎么在网络选项下边加入无线选项，我在软件包中下载了关于wireless的两个软件包，但是还是没有无线选项

**Comment by 1715173329** [comment]
https://git.kernel.org/pci/pci/c/b00c483a1075
This patch may resolve your problem.
