### ISSUE TITLE
wireguard编译问题

### ISSUE THREAD

**Issue by sxf5487** [immortalwrt/immortalwrt#1136]
### Describe the bug

编译时候没有wireguard插件选择，希望能添加，非常感谢！

### ImmortalWrt version

23.05

### ImmortalWrt release

23.05

### ImmortalWrt target/subtarget

23.05

### Device

所有设备

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by ksong008** [comment]
@sxf5487 wg不以插件形式了，在proto内
