### ISSUE TITLE
编译分支21.02运行passwall日志显示缺少依赖

### ISSUE THREAD

**Issue by gforce1206** [immortalwrt/immortalwrt#1155]
### Describe the bug

passwall（PKG version=4.72-2）日志显示缺少iptables-mod-socket，在make menuconfig-Network-firewall中没有这个编译项

### ImmortalWrt version

openwrt-21.02

### ImmortalWrt release

openwrt-21.02

### ImmortalWrt target/subtarget

QEMU ARM Virtual Machine

### Device

TVbox

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
21.02 is eol
