### ISSUE TITLE
odhcpd: Ignore leasetime from Static Leases

### ISSUE THREAD

**Issue by sst311212** [immortalwrt/immortalwrt#1156]
It always use `max_valid_lifetime` even if set `leasetime` is smaller than `max_valid_lifetime` from static leases.

https://github.com/immortalwrt/immortalwrt/blob/2e77acf140bb51fb8c68a2e71e74712dec60c5b7/package/network/services/odhcpd/patches/001-odhcpd-RFC-9096-compliance.patch#L198-L199

**Comment by 1715173329** [comment]
cc @skbeh

**Comment by 1715173329** [comment]
目前是预期行为。
