### ISSUE TITLE
Request adaptation to IPQ807X NSS, including NSS and WIFI NSS（请求适配IPQ807X NSS，包括NSS以及WIFI NSS）

### ISSUE THREAD

**Issue by OrdinaryJoys** [immortalwrt/immortalwrt#1167]
### Describe the bug

There are solutions in the forum, but it seems that no one has updated and adapted, hoping to adapt ipq807x-nss to solve the problem of excessive CPU usage（论坛中已有解决方案，但好像没人做过更新和适配，希望可以适配ipq807x-nss，以解决CPU占用过高的问题） 论坛链接：https://forum.openwrt.org/t/ipq807x-nss-build/148529/1078

### ImmortalWrt version

r27458-a83b379a31

### ImmortalWrt release

23.05-SNAPSHOT

### ImmortalWrt target/subtarget

rockchip/armv8

### Device

Devices with ipq807x

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
除非有人以上游标准重写这部分实现，否则不会支持。
