### ISSUE TITLE
求大佬解惑

### ISSUE THREAD

**Issue by lmxslpc** [immortalwrt/immortalwrt#1176]
### Describe the bug

使用Action进行编译一定会卡在编译tools/libtool
但是完全相同的环境,相同的配置,ssh登录Action使用runner用户 手动运行编译
make download -j$(nproc)&&make -j$(nproc) || make -j1 V=s | tee build.log
则能正常完成整个固件的编译
实在搞不明白为什么

这是我自己定义的变量,难道是什么环境变量冲突了???困惑
env:
  PROJECT: 'immortalwrt' 
  TARGET: 'x86_64'       
  REPO_URL: 'https://github.com/immortalwrt/immortalwrt'  
  REPO_BRANCH: 'openwrt-23.05'   
  PLATFORM: 'amd64'  
  SSH_DEBUG: 'true'
  SSH_TIME: '3m'    
  SSH_TIME2: '2h'   
  CCACHE: 'false'    
  CLEAN: 'false'    
  ARTIFACT: 'true'  
  RELEASE: 'true'  

### ImmortalWrt version

openwrt-23.05

### ImmortalWrt release

openwrt-23.05

### ImmortalWrt target/subtarget

x86_64

### Device

x86_64

### Image kind

Official downloaded image

### Steps to reproduce

这是报错

CFLAGS="-O2 -I/home/runner/work/openwrt-build/openwrt-build/immortalwrt/staging_dir/host/include " CPPFLAGS="-I/home/runner/work/openwrt-build/openwrt-build/immortalwrt/staging_dir/host/include " CXXFLAGS="" LDFLAGS="-L/home/runner/work/openwrt-build/openwrt-build/immortalwrt/staging_dir/host/lib " make  -C /home/runner/work/openwrt-build/openwrt-build/immortalwrt/build_dir/host/libtool-2.4.7  uninstall
make[4]: Entering directory '/home/runner/work/openwrt-build/openwrt-build/immortalwrt/build_dir/host/libtool-2.4.7'
There seems to be no Makefile in this directory.
You must run ./configure before running 'make'.
make[4]: *** [GNUmakefile:108: abort-due-to-no-makefile] Error 1
make[4]: Leaving directory '/home/runner/work/openwrt-build/openwrt-build/immortalwrt/build_dir/host/libtool-2.4.7'
make[3]: [Makefile:67: /home/runner/work/openwrt-build/openwrt-build/immortalwrt/build_dir/host/libtool-2.4.7/.prepared251a0ebb61864622f4235d01c3a8ccb4_6664517399ebbbc92a37c5bb081b5c53] Error 2 (ignored)
(cd /home/runner/work/openwrt-build/openwrt-build/immortalwrt/staging_dir/host/share/aclocal/ && rm -f libtool.m4 ltdl.m4 lt~obsolete.m4 ltoptions.m4 ltsugar.m4 ltversion.m4)
( cd /home/runner/work/openwrt-build/openwrt-build/immortalwrt/build_dir/host/libtool-2.4.7; AUTOM4TE=/home/runner/work/openwrt-build/openwrt-build/immortalwrt/staging_dir/host/bin/autom4te AUTOCONF=/home/runner/work/openwrt-build/openwrt-build/immortalwrt/staging_dir/host/bin/autoconf AUTOMAKE=/home/runner/work/openwrt-build/openwrt-build/immortalwrt/staging_dir/host/bin/automake ACLOCAL=/home/runner/work/openwrt-build/openwrt-build/immortalwrt/staging_dir/host/bin/aclocal AUTOHEADER=/home/runner/work/openwrt-build/openwrt-build/immortalwrt/staging_dir/host/bin/autoheader LIBTOOLIZE=/home/runner/work/openwrt-build/openwrt-build/immortalwrt/staging_dir/host/bin/libtoolize LIBTOOL=/home/runner/work/openwrt-build/openwrt-build/immortalwrt/staging_dir/host/bin/libtool M4=/home/runner/work/openwrt-build/openwrt-build/immortalwrt/staging_dir/host/bin/m4 AUTOPOINT=true GTKDOCIZE=true ./bootstrap --force --skip-git --skip-po --gnulib-srcdir=/home/runner/work/openwrt-build/openwrt-build/immortalwrt/staging_dir/host/share/gnulib )
bootstrap:   error: Prerequisite '/home/runner/work/openwrt-build/openwrt-build/immortalwrt/staging_dir/host/bin/autoconf' not found. Please install it, or
bootstrap:          'export AUTOCONF=/path/to//home/runner/work/openwrt-build/openwrt-build/immortalwrt/staging_dir/host/bin/autoconf'.
bootstrap:   error: Program    Min_version Homepage
bootstrap:          -----------------------------------------------------------
bootstrap:          help2man   1.29        http://www.gnu.org/s/help2man
bootstrap:          make       3.81        http://www.gnu.org/s/make
bootstrap:          makeinfo   4.8         http://www.gnu.org/s/texinfo
bootstrap:          xz         4.999.8beta http://tukaani.org/xz
bootstrap:          autoconf   2.64        http://www.gnu.org/s/autoconf
bootstrap:          automake   1.11.1      http://www.gnu.org/s/automake
bootstrap:          -----------------------------------------------------------
make[3]: *** [Makefile:69: /home/runner/work/openwrt-build/openwrt-build/immortalwrt/build_dir/host/libtool-2.4.7/.prepared251a0ebb61864622f4235d01c3a8ccb4_6664517399ebbbc92a37c5bb081b5c53] Error 1
make[3]: Leaving directory '/home/runner/work/openwrt-build/openwrt-build/immortalwrt/tools/libtool'
time: tools/libtool/compile#0.48#0.14#0.56
    ERROR: tools/libtool failed to build.
make[2]: *** [tools/Makefile:228: tools/libtool/compile] Error 1
make[2]: Leaving directory '/home/runner/work/openwrt-build/openwrt-build/immortalwrt'
make[1]: *** [tools/Makefile:224: /home/runner/work/openwrt-build/openwrt-build/immortalwrt/staging_dir/host/stamp/.tools_compile_nyyynyynnnyyyyynyyyyyyynyyynnnynyynnynnyyyyyyyyyyyyyyyynynynnyyyyyyy] Error 2
make[1]: Leaving directory '/home/runner/work/openwrt-build/openwrt-build/immortalwrt'
make: *** [/home/runner/work/openwrt-build/openwrt-build/immortalwrt/include/toplevel.mk:232: world] Error 2

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
停止滥用 github actions。
