### ISSUE TITLE
dnsmasq-full 没有编译 ipset 功能，导致一些程序无法使用

### ISSUE THREAD

**Issue by qiang-yu** [immortalwrt/immortalwrt#1184]
### Describe the bug

dnsmasq-full 之前编译都是带 ipset 功能的，v23.05.1 没有 ipset 功能，导致无法使用 adbyby

![Screenshot_1](https://github.com/immortalwrt/immortalwrt/assets/5996702/01842d29-43f0-4cc6-9449-99edc917c82f)

### ImmortalWrt version

v23.05.1

### ImmortalWrt release

v23.05.1

### ImmortalWrt target/subtarget

x86/64

### Device

x86/64

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
ipset 已被 nftset 取代，默认不再支持，有需要可以自行用 sdk 编译。
