### ISSUE TITLE
immortalwrt23.05.1实时信息中的连接无法查看

### ISSUE THREAD

**Issue by LemonCrab666** [immortalwrt/immortalwrt#1185]
### Describe the bug

23.05.1 x86实时信息中的连接打开会加载然后就显示登录过期，连接数在九千多
虚拟机中测试连接数二十多无此问题，master也是如此，系统日志中无报错
![Screenshot_20240217-213607](https://github.com/immortalwrt/immortalwrt/assets/55867630/c627126e-50c0-4106-9b8a-513c7f6e4d9b)
![Screenshot_20240217-213619](https://github.com/immortalwrt/immortalwrt/assets/55867630/d01cbe61-ee54-4c7a-ade1-eb233b70e15d)
![Screenshot_20240217-213920](https://github.com/immortalwrt/immortalwrt/assets/55867630/e2692a15-3bc0-4971-9eef-dfe81a9b4627)

### ImmortalWrt version

r27304-31bc47589e

### ImmortalWrt release

23.05.1

### ImmortalWrt target/subtarget

x86/64

### Device

CncTion J4125-4L

### Image kind

Self-built image

### Terms

- [x] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by science2468** [comment]
截图看看概览和日志，顺便把主题换成默认的。

**Comment by microka** [comment]
我也试过，连接数一多起来去看实时信息里的连接，看着看着会卡住，过一会儿要重新登录。

**Comment by microka** [comment]
![2024-05-02_145133](https://github.com/immortalwrt/immortalwrt/assets/490351/c3226d19-98cb-42b7-8e7c-a687079402e9)
![2024-05-02_145020](https://github.com/immortalwrt/immortalwrt/assets/490351/ce961a54-ca4e-4006-955b-1c0f3351a828)
![2024-05-02_144939](https://github.com/immortalwrt/immortalwrt/assets/490351/bb576bf0-da75-4cc6-a270-903a0a286df1)
![2024-05-02_144954](https://github.com/immortalwrt/immortalwrt/assets/490351/c770fa66-6e2a-4937-8535-29d5811207b8)
ImmortalWrt 23.05.2，连接数 10000+，实时信息连接情况无法查看。

**Comment by microka** [comment]
![2024-05-02_150338](https://github.com/immortalwrt/immortalwrt/assets/490351/abcabe2e-50a6-432f-9398-0d8c2094ee7a)
现在面板还进不去了

**Comment by liuweiGL** [comment]
需要我提供什么信息给你们调试吗

**Comment by aYangQT** [comment]
一样的问题，问过大佬了，连接数过大，实时信息-连接会卡死

**Comment by ternam** [comment]
Same issue here on 23.05 version.

**Comment by microka** [comment]
@LemonCrab666 请问这个问题解决了吗？
