### ISSUE TITLE
miniupnpd中规则无法自动清除

### ISSUE THREAD

**Issue by kxjhcmc** [immortalwrt/immortalwrt#1204]
### Describe the bug

miniupnpd中规则无法自动清除，设置了清除清除规则阈值为1，定时清除规则 1800秒，依然不会自动清除无效规则

### ImmortalWrt version

r29272-f08b89f121

### ImmortalWrt release

 SNAPSHOT

### ImmortalWrt target/subtarget

x86/64

### Device

CncTion J4125-4L-I225

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
https://github.com/immortalwrt/immortalwrt/discussions/1190
垃圾 upnp 免问即可。

**Comment by kxjhcmc** [comment]
没有解决，估计国外的软件都比较友好，会自己删除自己映射的端口，不像国内软件那么流氓，不断映射新端口，不删除老端口
