### ISSUE TITLE
请求添加 HinLink H6xK 系列源码 瑞星微RK35系列处理器

### ISSUE THREAD

**Issue by fuyi200** [immortalwrt/immortalwrt#1208]
请求添加 HinLink H6xK 系列源码 瑞星微RK35系列处理器

**Comment by xlighting2017** [comment]
https://github.com/immortalwrt/immortalwrt/commit/e0ab5b6aa808202939dae170f75ed3d532b8ab38

<img width="445" alt="image" src="https://github.com/immortalwrt/immortalwrt/assets/25970065/e57395a9-8a23-4b8e-b37b-2669e16ed0ce">

**Comment by 1715173329** [comment]
hinlink 的垃圾东西下辈子都不会支持的。
