### ISSUE TITLE
请求添加龙芯Loongarch支持

### ISSUE THREAD

**Issue by luoei** [immortalwrt/immortalwrt#1227]
### Describe the bug

目前已有部分仓库实现了支持。https://github.com/hackpascal/openwrt-dev

### ImmortalWrt version

master

### ImmortalWrt release

master

### ImmortalWrt target/subtarget

master

### Device

龙芯3a6000

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
正在上游 review。
