### ISSUE TITLE
OrangePi Zero3 CPU主频问题

### ISSUE THREAD

**Issue by ZZM365-CN** [immortalwrt/immortalwrt#1234]
### Describe the bug

用immortalwrt master分支编译OrangePi Zero3，添加luci-app-cpufreq后发现Zero3CPU最高主频只能调到1416000。看了下官网给的信息，CPU的主频是可以调到1.5GHz的。看大佬能不能修一下。
![屏幕截图(2)](https://github.com/immortalwrt/immortalwrt/assets/57690855/49b761f7-178c-40f6-a236-a9a8978904ce)

### ImmortalWrt version

r29831-2e9cc64cec

### ImmortalWrt release

SNAPSHOT

### ImmortalWrt target/subtarget

sunxi/cortexa53

### Device

OrangePi Zero3

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
根据芯片 id 决定频率上限。

**Comment by ZZM365-CN** [comment]
忘记说芯片参数了，lede那好像可以到1.5GHz的
![image](https://github.com/immortalwrt/immortalwrt/assets/57690855/a85069b5-1552-417a-a081-0471dc410c55)
