### ISSUE TITLE
能否为刷了暗云Uboot的XIAOMI_AX9000提供支持

### ISSUE THREAD

**Issue by maogeddd** [immortalwrt/immortalwrt#1244]
### Describe the bug

我使用master分支和openwrt-23.05分支都进行过编译且都成功,但通过uboot更新固件后无法正常使用(系统指示灯橙色闪烁,网口无法识别,2.5G网口指示灯常亮)等问题,经过查询是分区表不一致导致,我尝试过修改dts文件但无效,编译成功后故障同上,希望对刷了暗云Uboot的ax0000添加支持
下方是现在正常使用固件的分区表
root@XiaoMi:~# cat /proc/mtd
dev:    size   erasesize  name
mtd0: 00100000 00020000 "0:sbl1"
mtd1: 00100000 00020000 "0:mibib"
mtd2: 00080000 00020000 "0:bootconfig"
mtd3: 00080000 00020000 "0:bootconfig1"
mtd4: 00300000 00020000 "0:qsee"
mtd5: 00300000 00020000 "0:qsee_1"
mtd6: 00080000 00020000 "0:devcfg"
mtd7: 00080000 00020000 "0:devcfg_1"
mtd8: 00080000 00020000 "0:apdp"
mtd9: 00080000 00020000 "0:apdp_1"
mtd10: 00080000 00020000 "0:rpm"
mtd11: 00080000 00020000 "0:rpm_1"
mtd12: 00080000 00020000 "0:cdt"
mtd13: 00080000 00020000 "0:cdt_1"
mtd14: 00080000 00020000 "0:appsblenv"
mtd15: 00100000 00020000 "0:appsbl"
mtd16: 00100000 00020000 "0:appsbl_1"
mtd17: 00080000 00020000 "0:art"
mtd18: 00080000 00020000 "bdata"
mtd19: 00080000 00020000 "crash"
mtd20: 00080000 00020000 "crash_syslog"
mtd21: 0e800000 00020000 "rootfs"
mtd22: 00080000 00020000 "cfg_bak"

### ImmortalWrt version

r29866-a0227dddf3

### ImmortalWrt release

none

### ImmortalWrt target/subtarget

none

### Device

xiaomi-ax9000

### Image kind

Self-built image

### Steps to reproduce

none

### Actual behaviour

编译好的固件无法正常启动,且网口无法识别

### Expected behaviour

希望对刷了暗云uboot的xiaomi_ax9000添加支持

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
只兼容原厂 uboot 和分区表。
