### ISSUE TITLE
Orange Pi 5 Plus build don't boot

### ISSUE THREAD

**Issue by mplaviak** [immortalwrt/immortalwrt#1280]
### Describe the bug

I'm trying to use snapshot compilation on my Orange Pi 5 Plus. but it is not booting, I tried using the memory card, and the nvme SSD

### ImmortalWrt version

snapshot

### ImmortalWrt release

snapshot

### ImmortalWrt target/subtarget

armv8

### Device

Orange Pi 5 Plus

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
no log = no solution

**Comment by mplaviak** [comment]
> no log = no solution

How do I get a log? the device does not boot, and on the computer it appears as an unrecognized device. The compilation is for the sd card or emmc, correct?

**Comment by 1715173329** [comment]
It's a development board, so of course, from serial.

**Comment by mplaviak** [comment]
I will buy a serial cable, and send the log here

**Comment by Y-ZD-heheka** [comment]
the same problem ， looking for solution

**Comment by Y-ZD-heheka** [comment]
After one update of U-Boot, it could not start up anymore.

**Comment by MashiroYae** [comment]
same as NanoPi 6 https://github.com/immortalwrt/immortalwrt/issues/1285

**Comment by mplaviak** [comment]
I believe the problem its because the kernel 6.6. When I test the compilation with the Kernel 6.1, the system works correctly.

**Comment by Y-ZD-heheka** [comment]
chuange boot device to emmc

**Comment by 1715173329** [comment]
by checking logs in #1285 I found the sdmmc seems broken... under investigating

**Comment by 1715173329** [comment]
try a3a117453659a8fa898b931c951b24c1980771b2
