### ISSUE TITLE
FastRhino R66S lan and wan’led is not work

### ISSUE THREAD

**Issue by myd2898129** [immortalwrt/immortalwrt#1314]
### Describe the bug

FastRhino R66S lan and wan’led is not work
![image](https://github.com/immortalwrt/immortalwrt/assets/24140334/02404cbd-1e08-48ef-97c1-fca98f1fc7e6)

### ImmortalWrt version

V23.05.2

### ImmortalWrt release

V23.05.2

### ImmortalWrt target/subtarget

Rockchip/armv8

### Device

R66s

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
Only available for snapshot now.
