### ISSUE TITLE
immortalwrt 怎么替换编译最新的passwall

### ISSUE THREAD

**Issue by qq1316237299** [immortalwrt/immortalwrt#1321]
### Describe the bug

immortalwrt 怎么替换编译最新的passwall

### ImmortalWrt version

immortalwrt 怎么替换编译最新的passwall

### ImmortalWrt release

immortalwrt 怎么替换编译最新的passwall

### ImmortalWrt target/subtarget

immortalwrt 怎么替换编译最新的passwall

### Device

immortalwrt 怎么替换编译最新的passwall

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by cubercsl** [comment]
@qq1316237299
