### ISSUE TITLE
京东云百里ax6000    网络下面没有无线选项

### ISSUE THREAD

**Issue by zongheng23333** [immortalwrt/immortalwrt#1357]
[系统日志.txt](https://github.com/user-attachments/files/16081191/default.txt)
[内核日志.txt](https://github.com/user-attachments/files/16081192/default.txt)
![PixPin_2024-07-03_11-28-25](https://github.com/immortalwrt/immortalwrt/assets/29665054/36cff523-e7ca-4160-a440-72c1a84c1b39)

**Comment by 1715173329** [comment]
duplicate #1355 #1356
