### ISSUE TITLE
概览页面端口状态无内容显示

### ISSUE THREAD

**Issue by Raytheon-S** [immortalwrt/immortalwrt#1365]
### Describe the bug

概览页面端口状态无内容显示
![屏幕截图_9-7-2024_134141_10 10 10 250](https://github.com/immortalwrt/immortalwrt/assets/57355869/0802f516-8d2b-4d60-8aea-47a77cbf6087)

### ImmortalWrt version

r27625-416c8c5c91 

### ImmortalWrt release

23.05.2  

### ImmortalWrt target/subtarget

x86/64

### Device

VMware, Inc. VMware20,1

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
网卡本身信息不全或缺失，无法展示。
