### ISSUE TITLE
luci-app-strongswan-swanctl

### ISSUE THREAD

**Issue by lexin8** [immortalwrt/immortalwrt#1368]
### Describe the bug

luci-app-strongswan-swanctl为何加载不起来？
![1](https://github.com/user-attachments/assets/2a088a07-be54-4824-a9c1-66238dc08bf3)

### ImmortalWrt version

*

### ImmortalWrt release

*

### ImmortalWrt target/subtarget

*

### Device

*

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
不填写 issue template，视为无效问题。
