### ISSUE TITLE
luci-app-nlbwmon无效，没有任何流量统计信息

### ISSUE THREAD

**Issue by kylongteng** [immortalwrt/immortalwrt#1387]
### Describe the bug

luci-app-nlbwmon无效，没有任何流量统计信息。话说，只有我一个人遇到这个问题吗？我搜遍了几乎能搜索的所有信息，包括issue，好像都没人提这个bug。从去年开始接触openwrt，几个出名的分支包括原版openwrt编译了不少于100个openwrt，来回的纠结到底用哪个，最近狠下心决定用immortalwrt。但是immortalwrt就是有个让我膈应的地方，luci-app-nlbwmon不能用，去年我编译的第一个immortalwrt就是这样，其它几个分支都可以。昨天编译了3个immortalwrt依然还是这样……一个ax6s，两个x86，其中两个纯净的immortalwrt，1个加入了kenzok8的仓库。有评论说是流量分载导致的，但是关掉后luci-app-nlbwmon还是无效。期待各位大佬抽点时间看看这个问题。由于我当时没有保存日志，所以现在手里没有日志。但是我当时是仔细看过日志的，还和其它两个分支能正常使用luci-app-nlbwmon的日志做了对比，发现没有异常。这就奇怪了。下面版本信息是我现在用的ax6s的，昨天先编译了一个带luci-app-nlbwmon的，后来又去掉编译了一个不带luci-app-nlbwmon的，下面是版本信息

### ImmortalWrt version

r27925-eea6071d07

### ImmortalWrt release

23.05-SNAPSHOT

### ImmortalWrt target/subtarget

mediatek/mt7622

### Device

Xiaomi Redmi Router AX6S

### Image kind

Self-built image

### Steps to reproduce

luci-app-nlbwmon无效，没有任何流量统计信息。关闭流量分载，关闭NAT1甚至关闭所有能关闭的启动项重启后问题依旧，从去年底编译的第一个版本直到现在问题一直存在。
编译包含的软件包括：自动重启、ttyd、passwall、wol、KMS、luci-app-nlbwmon、argon

### Diffconfig

```text
#!/bin/sh
make ./scripts/config/conf >/dev/null || { make ./scripts/config/conf; exit 1; }
grep \^CONFIG_TARGET_ .config | head -n3 > tmp/.diffconfig.head
grep \^CONFIG_TARGET_DEVICE_ .config >> tmp/.diffconfig.head
grep '^CONFIG_ALL=y' .config >> tmp/.diffconfig.head
grep '^CONFIG_ALL_KMODS=y' .config >> tmp/.diffconfig.head
grep '^CONFIG_ALL_NONSHARED=y' .config >> tmp/.diffconfig.head
grep '^CONFIG_DEVEL=y' .config >> tmp/.diffconfig.head
grep '^CONFIG_TOOLCHAINOPTS=y' .config >> tmp/.diffconfig.head
grep '^CONFIG_BUSYBOX_CUSTOM=y' .config >> tmp/.diffconfig.head
grep '^CONFIG_TARGET_PER_DEVICE_ROOTFS=y' .config >> tmp/.diffconfig.head
./scripts/config/conf --defconfig=tmp/.diffconfig.head -w tmp/.diffconfig.stage1 Config.in >/dev/null
./scripts/kconfig.pl '>+' tmp/.diffconfig.stage1 .config >> tmp/.diffconfig.head
./scripts/config/conf --defconfig=tmp/.diffconfig.head -w tmp/.diffconfig.stage2 Config.in >/dev/null
./scripts/kconfig.pl '>' tmp/.diffconfig.stage2 .config >> tmp/.diffconfig.head
cat tmp/.diffconfig.head
rm -f tmp/.diffconfig tmp/.diffconfig.head
```

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
duplicate #1273
