### ISSUE TITLE
23.05分支编译报错

### ISSUE THREAD

**Issue by free-diy** [immortalwrt/immortalwrt#1399]
### Describe the bug

编译报错

Configuring luci-i18n-opkg-zh-cn.
Configuring autosamba.
Configuring kmod-amazon-ena.
Configuring kmod-e1000e.
Configuring luci-i18n-upnp-zh-cn.
Configuring alsa-ucm-conf.
Configuring alsa-utils.
Configuring kmod-button-hotplug.
Configuring smartdns.
Configuring kmod-igb.
Configuring kmod-igc.
Configuring kmod-bnx2.
Configuring urngd.
Configuring luci-i18n-firewall-zh-cn.
Configuring ppp-mod-pppoe.
Configuring kmod-ipt-nat.
Configuring iptables-zz-legacy.
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:168: /workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:248: world] Error 2
Error: Process completed with exit code 2.

### ImmortalWrt version

23.05分支

### ImmortalWrt release

x86

### ImmortalWrt target/subtarget

x86

### Device

x86

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
依赖冲突，日志不全自行判断。
