### ISSUE TITLE
红米AX6000采用最新代码5G信号问题

### ISSUE THREAD

**Issue by UR-l** [immortalwrt/immortalwrt#1428]
### Describe the bug

红米AX6000采用最新代码5Gwifi无法被其他设备搜索到，有时会显示未关联，有时会正常，但是其他设备搜索不到5g信号

### ImmortalWrt version

r31323-288bb4facc

### ImmortalWrt release

SNAPSHOT

### ImmortalWrt target/subtarget

mediatek/filogic

### Device

Xiaomi Redmi Router AX6000

### Image kind

Self-built image

### Expected behaviour

可以正常打开并被其他设备搜索到5G信号

### Additional info

/etc/config/wireless如下:

config wifi-device 'radio0'
	option type 'mac80211'
	option path 'platform/soc/18000000.wifi'
	option band '2g'
	option channel 'auto'
	option htmode 'HE40'
	option cell_density '0'

config wifi-iface 'default_radio0'
	option device 'radio0'
	option network 'lan'
	option mode 'ap'
	option ssid 'UR'
	option encryption 'psk-mixed'
	option key '123456789'

config wifi-device 'radio1'
	option type 'mac80211'
	option path 'platform/soc/18000000.wifi+1'
	option band '5g'
	option channel '36'
	option htmode 'HE160'
	option cell_density '0'
	option txpower '10'

config wifi-iface 'default_radio1'
	option device 'radio1'
	option network 'lan'
	option mode 'ap'
	option ssid 'UR-5G'
	option encryption 'psk-mixed'
	option key '123456789'

系统日志如下:
Mon Aug 19 16:12:26 2024 daemon.notice hostapd: Set new config for phy phy1:
Mon Aug 19 16:12:26 2024 daemon.notice hostapd: Remove interface 'phy1'
Mon Aug 19 16:12:26 2024 daemon.notice hostapd: phy1-ap0: interface state DFS->DISABLED
Mon Aug 19 16:12:26 2024 daemon.notice hostapd: phy1-ap0: AP-DISABLED
Mon Aug 19 16:12:26 2024 daemon.notice hostapd: phy1-ap0: CTRL-EVENT-TERMINATING
Mon Aug 19 16:12:26 2024 daemon.err hostapd: rmdir[ctrl_interface=/var/run/hostapd]: Permission denied
Mon Aug 19 16:12:26 2024 daemon.err hostapd: hostapd_free_hapd_data: Interface phy1-ap0 wasn't started
Mon Aug 19 16:12:26 2024 daemon.notice hostapd: nl80211: deinit ifname=phy1-ap0 disabled_11b_rates=0
Mon Aug 19 16:12:26 2024 kern.info kernel: [ 1019.347528] mt798x-wmac 18000000.wifi phy1-ap0: left allmulticast mode
Mon Aug 19 16:12:26 2024 kern.info kernel: [ 1019.354081] mt798x-wmac 18000000.wifi phy1-ap0: left promiscuous mode
Mon Aug 19 16:12:26 2024 kern.info kernel: [ 1019.360644] br-lan: port 5(phy1-ap0) entered disabled state
Mon Aug 19 16:12:26 2024 daemon.notice wpa_supplicant[2265]: Set new config for phy phy1
Mon Aug 19 16:12:26 2024 daemon.notice netifd: Wireless device 'radio1' is now down
Mon Aug 19 16:12:26 2024 daemon.notice netifd: radio1 (23106): WARNING: Variable 'data' does not exist or is not an array/object
Mon Aug 19 16:12:26 2024 daemon.notice hostapd: Set new config for phy phy1:
Mon Aug 19 16:12:27 2024 daemon.notice wpa_supplicant[2265]: Set new config for phy phy1
Mon Aug 19 16:12:27 2024 daemon.notice wpa_supplicant[2265]: Set new config for phy phy1
Mon Aug 19 16:12:27 2024 daemon.notice hostapd: Set new config for phy phy1: /var/run/hostapd-phy1.conf
Mon Aug 19 16:12:27 2024 daemon.notice hostapd: Restart interface for phy phy1
Mon Aug 19 16:12:27 2024 daemon.notice hostapd: Configuration file: data: driver=nl80211 logger_syslog=127 logger_syslog_level=2 logger_stdout=127 logger_stdout_level=2 hw_mode=a beacon_int=100 chanlist=36 tx_queue_data2_burst=2.0 #num_global_macaddr=1 ieee80211n=1 ht_coex=0 ht_capab=[HT40+][LDPC][SHORT-GI-20][SHORT-GI-40][TX-STBC][RX-STBC1][MAX-AMSDU-7935] ieee80211ac=1 vht_oper_chwidth=2 vht_oper_centr_freq_seg0_idx=50 vht_capab=[RXLDPC][SHORT-GI-80][SHORT-GI-160][TX-STBC-2BY1][SU-BEAMFORMER][SU-BEAMFORMEE][MU-BEAMFORMER][MU-BEAMFORMEE][RX-ANTENNA-PATTERN][TX-ANTENNA-PATTERN][RX-STBC-1][SOUNDING-DIMENSION-4][BF-ANTENNA-4][VHT160][MAX-MPDU-11454][MAX-A-MPDU-LEN-EXP7] ieee80211ax=1 he_oper_chwidth=2 he_oper_centr_freq_seg0_idx=50 he_su_beamformer=1 he_su_beamformee=1 he_mu_beamformer=1 he_bss_color=128 he_spr_sr_control=3 he_default_pe_duration=4 he_rts_threshold=1023 he_mu_edca_qos_info_param_count=0 he_mu_edca_qos_info_q_ack=0 he_mu_edca_qos_info_queue_request=0 he_mu_edca_qos_info_txop_request=0 he_mu_edca_ac_be_aifsn=8 he_
Mon Aug 19 16:12:27 2024 kern.info kernel: [ 1020.065625] br-lan: port 5(phy1-ap0) entered blocking state
Mon Aug 19 16:12:27 2024 kern.info kernel: [ 1020.071243] br-lan: port 5(phy1-ap0) entered disabled state
Mon Aug 19 16:12:27 2024 kern.info kernel: [ 1020.076882] mt798x-wmac 18000000.wifi phy1-ap0: entered allmulticast mode
Mon Aug 19 16:12:27 2024 kern.info kernel: [ 1020.083833] mt798x-wmac 18000000.wifi phy1-ap0: entered promiscuous mode
Mon Aug 19 16:12:27 2024 daemon.notice hostapd: phy1-ap0: interface state UNINITIALIZED->HT_SCAN
Mon Aug 19 16:12:27 2024 daemon.notice netifd: Wireless device 'radio1' is now up
Mon Aug 19 16:12:27 2024 daemon.err hostapd: could not get valid channel
Mon Aug 19 16:12:27 2024 daemon.notice hostapd: phy1-ap0: interface state HT_SCAN->DFS
Mon Aug 19 16:15:33 2024 daemon.warn odhcpd[2452]: No default route present, setting ra_lifetime to 0!
Mon Aug 19 16:20:34 2024 daemon.warn odhcpd[2452]: No default route present, setting ra_lifetime to 0!

### Diffconfig

```text
CONFIG_TARGET_mediatek=y
CONFIG_TARGET_mediatek_filogic=y
CONFIG_TARGET_mediatek_filogic_DEVICE_xiaomi_redmi-router-ax6000=y
CONFIG_DRIVER_11AC_SUPPORT=y
CONFIG_DRIVER_11AX_SUPPORT=y
CONFIG_KERNEL_PAGE_POOL=y
CONFIG_KERNEL_RELAY=y
CONFIG_LIBCURL_COOKIES=y
CONFIG_LIBCURL_CRYPTO_AUTH=y
CONFIG_LIBCURL_FILE=y
CONFIG_LIBCURL_FTP=y
CONFIG_LIBCURL_HTTP=y
CONFIG_LIBCURL_NGHTTP2=y
CONFIG_LIBCURL_OPENSSL=y
CONFIG_LIBCURL_PROXY=y
CONFIG_LIBCURL_TFTP=y
CONFIG_LIBCURL_THREADED_RESOLVER=y
CONFIG_LIBCURL_TLS_SRP=y
CONFIG_LIBCURL_UNIX_SOCKETS=y
CONFIG_LUCI_LANG_zh_Hans=y
CONFIG_NODEJS_18=y
# CONFIG_NODEJS_20 is not set
CONFIG_OPENSSL_ENGINE_BUILTIN=y
CONFIG_OPENSSL_ENGINE_BUILTIN_AFALG=y
CONFIG_OPENSSL_ENGINE_BUILTIN_DEVCRYPTO=y
CONFIG_PACKAGE_MAC80211_DEBUGFS=y
CONFIG_PACKAGE_MAC80211_MESH=y
CONFIG_PACKAGE_acme=y
CONFIG_PACKAGE_acme-acmesh=y
CONFIG_PACKAGE_acme-common=y
CONFIG_PACKAGE_appfilter=y
CONFIG_PACKAGE_autocore=y
CONFIG_PACKAGE_bash=y
CONFIG_PACKAGE_block-mount=y
CONFIG_PACKAGE_ca-certificates=y
CONFIG_PACKAGE_cgi-io=y
CONFIG_PACKAGE_coreutils=y
CONFIG_PACKAGE_coreutils-nohup=y
CONFIG_PACKAGE_curl=y
CONFIG_PACKAGE_default-settings=y
CONFIG_PACKAGE_default-settings-chn=y
CONFIG_PACKAGE_etherwake=y
CONFIG_PACKAGE_frpc=y
CONFIG_PACKAGE_ip-full=y
CONFIG_PACKAGE_iw=y
CONFIG_PACKAGE_kmod-asn1-decoder=y
CONFIG_PACKAGE_kmod-cfg80211=y
CONFIG_PACKAGE_kmod-crypto-ccm=y
CONFIG_PACKAGE_kmod-crypto-cmac=y
CONFIG_PACKAGE_kmod-crypto-ctr=y
CONFIG_PACKAGE_kmod-crypto-gcm=y
CONFIG_PACKAGE_kmod-crypto-geniv=y
CONFIG_PACKAGE_kmod-crypto-gf128=y
CONFIG_PACKAGE_kmod-crypto-ghash=y
CONFIG_PACKAGE_kmod-crypto-seqiv=y
CONFIG_PACKAGE_kmod-cryptodev=y
CONFIG_PACKAGE_kmod-inet-diag=y
CONFIG_PACKAGE_kmod-ipt-conntrack=y
CONFIG_PACKAGE_kmod-ipt-core=y
CONFIG_PACKAGE_kmod-lib-textsearch=y
CONFIG_PACKAGE_kmod-mac80211=y
CONFIG_PACKAGE_kmod-mt76-connac=y
CONFIG_PACKAGE_kmod-mt76-core=y
CONFIG_PACKAGE_kmod-mt7915e=y
CONFIG_PACKAGE_kmod-nf-ipt=y
CONFIG_PACKAGE_kmod-nf-nathelper=y
CONFIG_PACKAGE_kmod-nf-nathelper-extra=y
CONFIG_PACKAGE_kmod-nf-tproxy=y
CONFIG_PACKAGE_kmod-nft-tproxy=y
CONFIG_PACKAGE_kmod-oaf=y
CONFIG_PACKAGE_kmod-thermal=y
CONFIG_PACKAGE_kmod-tun=y
CONFIG_PACKAGE_libbpf=y
CONFIG_PACKAGE_libcap=y
CONFIG_PACKAGE_libcap-bin=y
CONFIG_PACKAGE_libcap-bin-capsh-shell="/bin/sh"
CONFIG_PACKAGE_libcap-ng=y
CONFIG_PACKAGE_libcurl=y
CONFIG_PACKAGE_libelf=y
CONFIG_PACKAGE_liblua=y
CONFIG_PACKAGE_liblucihttp=y
CONFIG_PACKAGE_liblucihttp-lua=y
CONFIG_PACKAGE_liblucihttp-ucode=y
CONFIG_PACKAGE_libncurses=y
CONFIG_PACKAGE_libnghttp2=y
CONFIG_PACKAGE_libpcre2=y
CONFIG_PACKAGE_libreadline=y
CONFIG_PACKAGE_librt=y
CONFIG_PACKAGE_libruby=y
CONFIG_PACKAGE_libubus-lua=y
CONFIG_PACKAGE_libuuid=y
CONFIG_PACKAGE_libyaml=y
CONFIG_PACKAGE_lua=y
CONFIG_PACKAGE_luci=y
CONFIG_PACKAGE_luci-app-appfilter=y
CONFIG_PACKAGE_luci-app-argon-config=y
CONFIG_PACKAGE_luci-app-firewall=y
CONFIG_PACKAGE_luci-app-frpc=y
CONFIG_PACKAGE_luci-app-openclash=y
CONFIG_PACKAGE_luci-app-opkg=y
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Rust_Server is not set
CONFIG_PACKAGE_luci-app-vlmcsd=y
CONFIG_PACKAGE_luci-app-wol=y
CONFIG_PACKAGE_luci-base=y
CONFIG_PACKAGE_luci-compat=y
CONFIG_PACKAGE_luci-i18n-appfilter-zh-cn=y
CONFIG_PACKAGE_luci-i18n-argon-config-zh-cn=y
CONFIG_PACKAGE_luci-i18n-base-zh-cn=y
CONFIG_PACKAGE_luci-i18n-firewall-zh-cn=y
CONFIG_PACKAGE_luci-i18n-frpc-zh-cn=y
CONFIG_PACKAGE_luci-i18n-opkg-zh-cn=y
CONFIG_PACKAGE_luci-i18n-vlmcsd-zh-cn=y
CONFIG_PACKAGE_luci-i18n-wol-zh-cn=y
CONFIG_PACKAGE_luci-lib-base=y
CONFIG_PACKAGE_luci-lib-ip=y
CONFIG_PACKAGE_luci-lib-ipkg=y
CONFIG_PACKAGE_luci-lib-jsonc=y
CONFIG_PACKAGE_luci-lib-nixio=y
CONFIG_PACKAGE_luci-light=y
CONFIG_PACKAGE_luci-lua-runtime=y
CONFIG_PACKAGE_luci-mod-admin-full=y
CONFIG_PACKAGE_luci-mod-network=y
CONFIG_PACKAGE_luci-mod-status=y
CONFIG_PACKAGE_luci-mod-system=y
CONFIG_PACKAGE_luci-proto-ipv6=y
CONFIG_PACKAGE_luci-proto-ppp=y
CONFIG_PACKAGE_luci-ssl-openssl=y
CONFIG_PACKAGE_luci-theme-argon=y
CONFIG_PACKAGE_luci-theme-bootstrap=y
CONFIG_PACKAGE_miniupnpd-nftables=y
CONFIG_PACKAGE_openssl-util=y
CONFIG_PACKAGE_rpcd=y
CONFIG_PACKAGE_rpcd-mod-file=y
CONFIG_PACKAGE_rpcd-mod-iwinfo=y
CONFIG_PACKAGE_rpcd-mod-luci=y
CONFIG_PACKAGE_rpcd-mod-rrdns=y
CONFIG_PACKAGE_rpcd-mod-ucode=y
CONFIG_PACKAGE_ruby=y
CONFIG_PACKAGE_ruby-bigdecimal=y
CONFIG_PACKAGE_ruby-date=y
CONFIG_PACKAGE_ruby-digest=y
CONFIG_PACKAGE_ruby-enc=y
CONFIG_PACKAGE_ruby-forwardable=y
CONFIG_PACKAGE_ruby-pstore=y
CONFIG_PACKAGE_ruby-psych=y
CONFIG_PACKAGE_ruby-stringio=y
CONFIG_PACKAGE_ruby-yaml=y
CONFIG_PACKAGE_socat=y
CONFIG_PACKAGE_terminfo=y
CONFIG_PACKAGE_ucode-mod-html=y
CONFIG_PACKAGE_ucode-mod-lua=y
CONFIG_PACKAGE_ucode-mod-math=y
CONFIG_PACKAGE_uhttpd=y
CONFIG_PACKAGE_uhttpd-mod-ubus=y
CONFIG_PACKAGE_unzip=y
CONFIG_PACKAGE_vlmcsd=y
CONFIG_PACKAGE_wget-ssl=y
CONFIG_PACKAGE_wifi-scripts=y
CONFIG_PACKAGE_wireless-regdb=y
CONFIG_PACKAGE_zlib=y
```

### Terms

- [ ] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
没设置国家代码，并且 dfs 信道可能存在冲突。

**Comment by UR-l** [comment]
1

**Comment by UR-l** [comment]
我知道为什么了

**Comment by UR-l** [comment]
我知道为什么了，重置之后他默认通道宽度是80Mhz，切换成160Mhz就不行了

**Comment by 1715173329** [comment]
必须设置**有效**国家代码。
