### ISSUE TITLE
小小问题

### ISSUE THREAD

**Issue by Eternalklk** [immortalwrt/immortalwrt#1435]
### Describe the bug

编译能完成，但会跳一行警告
WARNING: Applying padding in /workdir/openwrt/bin/packages/aarch64_cortex-a53/luci/Packages to workaround usign SHA-512 bug!

### ImmortalWrt version

20bdbd7

### ImmortalWrt release

master

### ImmortalWrt target/subtarget

filogic

### Device

6086

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
e1f588e446c7ceb696b644b37aeab9b3476e2a57
