### ISSUE TITLE
adblock-lean 兼容性问题

### ISSUE THREAD

**Issue by nocmt** [immortalwrt/immortalwrt#1442]
### Describe the bug

问题现象：安装 https://github.com/lynxthecat/adblock-lean 后，执行 service adblock-lean enable 时提示：

/etc/rc.common: /etc/init.d/adblock-lean: line 716: syntax error: unexpected "("

除此之外还有 731、 736、745、948、1160 行都是这个错误，看起来是不兼容 tee > (xxx ) 这种写法，标准openwrt没有这个问题

请协助处理。

Problem phenomenon: Installation https://github.com/lynxthecat/adblock-lean Later, when executing service adblock lean enable, it prompts:

In addition, lines 731, 736, 745, 948, and 1160 contain this error, which appears to be incompatible with the tee>(xxx) writing style. Standard OpenWrt does not have this issue

Please assist in handling

### ImmortalWrt version

R24.8.1

### ImmortalWrt release

openwrt-21.02 branch (git-23.098.38725-847bd6b) / ImmortalWrt R24.8.1

### ImmortalWrt target/subtarget

mediatek/mt7981

### Device

360 T7

### Image kind

Self-built image

### Steps to reproduce

Terminal execution:

uclient-fetch https://raw.githubusercontent.com/lynxthecat/adblock-lean/main/adblock-lean -O /etc/init.d/adblock-lean
chmod +x /etc/init.d/adblock-lean
service adblock-lean gen_config   # generates default config in /root/adblock-lean/config
uci add_list dhcp.@dnsmasq[0].addnmount='/bin/busybox' && uci commit   # Optional/recommended.  Enables blocklist compression to reduce RAM usage
service adblock-lean enable   # this will allow the script to automatically run on boot

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
使用第三方固件和第三方插件所遇问题自行负责。
