### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by aepub** [immortalwrt/immortalwrt#1446]
### Describe the bug

用git clone  https://github.com/immortalwrt/immortalwrt下载源码，编译，出现：
SHELL= flock /home/imm/immortalwrt/tmp/.libubox-2024.03.29~eb9bcb64.tar.zst.flock -c '          /home/imm/immortalwrt/scripts/download.pl "/home/imm/immortalwrt/dl" "libubox-2024.03.29~eb9bcb64.tar.zst" "a4f671d10840fd8487394335636051a6df5edf6d8854af4fcb834a590efb240a" "" || (         echo "Checking out files from the git repository..."; mkdir -p /home/imm/immortalwrt/tmp/dl && cd /home/imm/immortalwrt/tmp/dl && rm -rf libubox-2024.03.29~eb9bcb64 && [ \! -d libubox-2024.03.29~eb9bcb64 ] && git clone --filter=blob:none  https://git.openwrt.org/project/libubox.git libubox-2024.03.29~eb9bcb64 && (cd libubox-2024.03.29~eb9bcb64 && git checkout eb9bcb64185ac155c02cc1a604692c4b00368324) && export TAR_TIMESTAMP=`cd libubox-2024.03.29~eb9bcb64 && git log -1 --format='\''@%ct'\''` && echo "Generating formal git archive (apply .gitattributes rules)" && (cd libubox-2024.03.29~eb9bcb64 && git config core.abbrev 8 && git archive --format=tar HEAD --output=../libubox-2024.03.29~eb9bcb64.tar.git) && tar --ignore-failed-read -C libubox-2024.03.29~eb9bcb64 -f libubox-2024.03.29~eb9bcb64.tar.git -r .git .gitmodules 2>/dev/null && rm -rf libubox-2024.03.29~eb9bcb64 && mkdir libubox-2024.03.29~eb9bcb64 && tar -C libubox-2024.03.29~eb9bcb64 -xf libubox-2024.03.29~eb9bcb64.tar.git && (cd libubox-2024.03.29~eb9bcb64 && git submodule update --init --recursive --  && rm -rf .git .gitmodules) && echo "Packing checkout..." &&        tar --numeric-owner --owner=0 --group=0 --mode=a-s --sort=name ${TAR_TIMESTAMP:+--mtime="$TAR_TIMESTAMP"} -c libubox-2024.03.29~eb9bcb64 |         zstd -T0 --ultra -20 -c > /home/imm/immortalwrt/tmp/dl/libubox-2024.03.29~eb9bcb64.tar.zst && mv /home/imm/immortalwrt/tmp/dl/libubox-2024.03.29~eb9bcb64.tar.zst /home/imm/immortalwrt/dl/ && rm -rf libubox-2024.03.29~eb9bcb64;  )    '
+ curl -f --connect-timeout 20 --retry 5 --location https://mirror2.immortalwrt.org/sources/libubox-2024.03.29~eb9bcb64.tar.zst
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to mirror2.immortalwrt.org:443 
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://mirror.immortalwrt.org/sources/libubox-2024.03.29~eb9bcb64.tar.zst
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to mirror.immortalwrt.org:443 
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://sources-cdn.immortalwrt.org/libubox-2024.03.29~eb9bcb64.tar.zst
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to sources-cdn.immortalwrt.org:443 
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://sources.immortalwrt.org/libubox-2024.03.29~eb9bcb64.tar.zst
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to sources.immortalwrt.org:443 
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://sources.cdn.openwrt.org/libubox-2024.03.29~eb9bcb64.tar.zst
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to sources.cdn.openwrt.org:443 
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://sources.openwrt.org/libubox-2024.03.29~eb9bcb64.tar.zst
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to sources.openwrt.org:443 
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://mirror2.openwrt.org/sources/libubox-2024.03.29~eb9bcb64.tar.zst
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to mirror2.openwrt.org:443 
Download failed.
No more mirrors to try - giving up.
Checking out files from the git repository...
Cloning into 'libubox-2024.03.29~eb9bcb64'...
fatal: unable to access 'https://git.openwrt.org/project/libubox.git/': gnutls_handshake() failed: Error in the pull function.
make[3]: *** [Makefile:117: /home/imm/immortalwrt/dl/libubox-2024.03.29~eb9bcb64.tar.zst] Error 128
make[3]: Leaving directory '/home/imm/immortalwrt/package/libs/libubox'
time: package/libs/libubox/host-compile#0.44#0.18#40.39
    ERROR: package/libs/libubox [host] failed to build.
make[2]: *** [package/Makefile:175: package/libs/libubox/host/compile] Error 1
make[2]: Leaving directory '/home/imm/immortalwrt'
make[1]: *** [package/Makefile:171: /home/imm/immortalwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/imm/immortalwrt'
make: *** [/home/imm/immortalwrt/include/toplevel.mk:248：world] 错误 2
imm@guo-OptiPlex-3080:~/immortalwrt$ make V=s -j6
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to sources.immortalwrt.org:443
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://sources.cdn.openwrt.org/libubox-2024.03.29~eb9bcb64.tar.zst
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to sources.cdn.openwrt.org:443
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://sources.openwrt.org/libubox-2024.03.29~eb9bcb64.tar.zst
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to sources.openwrt.org:443
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://mirror2.openwrt.org/sources/libubox-2024.03.29~eb9bcb64.tar.zst
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to mirror2.openwrt.org:443
Download failed.
No more mirrors to try - giving up.
Checking out files from the git repository...
Cloning into 'libubox-2024.03.29~eb9bcb64'...
fatal: unable to access 'https://git.openwrt.org/project/libubox.git/': gnutls_handshake() failed: Error in the pull function.
make[3]: *** [Makefile:117: /home/imm/immortalwrt/dl/libubox-2024.03.29~eb9bcb64.tar.zst] Error 128
make[3]: Leaving directory '/home/imm/immortalwrt/package/libs/libubox'
time: package/libs/libubox/host-compile#0.44#0.18#40.39
    ERROR: package/libs/libubox [host] failed to build.
make[2]: *** [package/Makefile:175: package/libs/libubox/host/compile] Error 1
make[2]: Leaving directory '/home/imm/immortalwrt'
make[1]: *** [package/Makefile:171: /home/imm/immortalwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/imm/immortalwrt'
make: *** [/home/imm/immortalwrt/include/toplevel.mk:248：world] 错误 2

### ImmortalWrt version

master

### ImmortalWrt release

master

### ImmortalWrt target/subtarget

master

### Device

X86/64

### Image kind

Self-built image

### Steps to reproduce

看情况貌似libubox-2024.03.29~eb9bcb64.tar.zst下载失败？https://mirror2.openwrt.org/sources/里面没有这个文件，求解决办法！

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
你网烂了
