### ISSUE TITLE
编译完成后，浏览器无法进管理后台

### ISSUE THREAD

**Issue by aepub** [immortalwrt/immortalwrt#1447]
### Describe the bug

自己编译的固件，用VB建虚拟机测试，能够正常启动，但是用浏览器打开后台，提示：无法访问此网站192.168.1.1 拒绝了我的连接请求。谷歌浏览器有一行字一闪而过，好像是需要luci配置啥的，是什么原因？ 

### ImmortalWrt version

master

### ImmortalWrt release

master

### ImmortalWrt target/subtarget

master

### Device

X86/64

### Image kind

Self-built image

### Steps to reproduce

无法访问此网站192.168.1.1 拒绝了我们的连接请求。
请试试以下办法：

检查网络连接
[检查代理服务器和防火墙]
ERR_CONNECTION_REFUSED

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by qiang1352** [comment]
我也是遇到这样的问题

**Comment by initzhu** [comment]
[sir this way](https://github.com/immortalwrt/user-FAQ/blob/main/%E5%B0%8F%E7%99%BD%E9%97%AE%E9%A2%98%E9%80%9F%E6%9F%A5.md#%E8%87%AA%E7%BC%96%E8%AF%91%E7%9A%84%E5%9B%BA%E4%BB%B6%E6%97%A0%E6%B3%95%E8%BF%9B%E5%85%A5%E7%BD%91%E9%A1%B5luci)
