### ISSUE TITLE
Generic x86/64 SNAPSHOT构建失败

### ISSUE THREAD

**Issue by iwowcn** [immortalwrt/immortalwrt#1460]
### Describe the bug

在构建Generic x86/64 SNAPSHOT镜像时，添加预装软件包之后，请求构建报错。
![PixPin_2024-09-09_13-56-48](https://github.com/user-attachments/assets/bfced10a-8c73-4990-b54f-b3f87130bd68)

### ImmortalWrt version

 SNAPSHOT

### ImmortalWrt release

r31509-36bee9bce8

### ImmortalWrt target/subtarget

 SNAPSHOT (r31509-36bee9bce8)

### Device

Generic x86/64

### Image kind

Self-built image

### Additional info

自定义预装软件列表如下：
alsa-utils
autocore
automount
base-files
block-mount
busybox
ca-bundle
default-settings-chn
dnsmasq-full
dropbear
fdisk
firewall4
fstools
grub2-bios-setup
ipv6helper
kmod-8139cp
kmod-8139too
kmod-ac97
kmod-amazon-ena
kmod-amd-xgbe
kmod-bnx2
kmod-button-hotplug
kmod-dwmac-intel
kmod-e1000
kmod-e1000e
kmod-forcedeth
kmod-fs-f2fs
kmod-fs-vfat
kmod-i40e
kmod-igb
kmod-igbvf
kmod-igc
kmod-ixgbe
kmod-ixgbevf
kmod-nf-nathelper
kmod-nf-nathelper-extra
kmod-nft-offload
kmod-pcnet32
kmod-r8101
kmod-r8125
kmod-r8126
kmod-r8168
kmod-sound-hda-codec-hdmi
kmod-sound-hda-codec-realtek
kmod-sound-hda-codec-via
kmod-sound-hda-core
kmod-sound-hda-intel
kmod-sound-i8x0
kmod-sound-via82xx
kmod-tg3
kmod-tulip
kmod-usb-audio
kmod-usb-hid
kmod-usb-net
kmod-usb-net-asix
kmod-usb-net-asix-ax88179
kmod-usb-net-rtl8150
kmod-usb-net-rtl8152-vendor
kmod-vmxnet3
libc
libgcc
libustream-openssl
logd
luci
luci-app-opkg
luci-i18n-opkg-zh-cn
luci-compat
luci-lib-base
luci-lib-ipkg
mkf2fs
mtd
netifd
nftables
opkg
partx-utils
ppp
ppp-mod-pppoe
procd
procd-seccomp
procd-ujail
uci
uclient-fetch
urandom-seed
urngd
losetup
resize2fs
blkid
luci-i18n-firewall-zh-cn
luci-theme-argon
luci-app-accesscontrol
luci-i18n-accesscontrol-zh-cn
luci-app-openclash
luci-app-ddns-go
luci-i18n-ddns-go-zh-cn
luci-app-autoreboot
luci-i18n-autoreboot-zh-cn
luci-app-arpbind
luci-i18n-arpbind-zh-cn
luci-app-vlmcsd
luci-i18n-vlmcsd-zh-cn
luci-app-wol
luci-i18n-wol-zh-cn
luci-app-attendedsysupgrade
luci-i18n-attendedsysupgrade-zh-cn

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by nicholas-opensource** [comment]
luci-app-accesscontrol 已被移除
