### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by johnnywongxy** [immortalwrt/immortalwrt#1461]
### Describe the bug

Signing package index...
make[2]: Leaving directory '/home/xiaoyu/immortalwrt'
export MAKEFLAGS= ;make -w -r json_overview_image_info
make[2]: Entering directory '/home/xiaoyu/immortalwrt'
WORK_DIR=/home/xiaoyu/immortalwrt/build_dir/target-aarch64_cortex-a53_musl/json_info_files /home/xiaoyu/immortalwrt/scripts/json_overview_image_info.py /home/xiaoyu/immortalwrt/bin/targets/mediatek/filogic/profiles.json
make[2]: Leaving directory '/home/xiaoyu/immortalwrt'
export MAKEFLAGS= ;make -w -r checksum
make[2]: Entering directory '/home/xiaoyu/immortalwrt'
make[2]: Leaving directory '/home/xiaoyu/immortalwrt'
make[1]: Leaving directory '/home/xiaoyu/immortalwrt'

### ImmortalWrt version

23.05

### ImmortalWrt release

23.05

### ImmortalWrt target/subtarget

23.05

### Device

redmi ax6000

### Image kind

Official downloaded image

### Steps to reproduce

Signing package index...
make[2]: Leaving directory '/home/xiaoyu/immortalwrt'
export MAKEFLAGS= ;make -w -r json_overview_image_info
make[2]: Entering directory '/home/xiaoyu/immortalwrt'
WORK_DIR=/home/xiaoyu/immortalwrt/build_dir/target-aarch64_cortex-a53_musl/json_info_files /home/xiaoyu/immortalwrt/scripts/json_overview_image_info.py /home/xiaoyu/immortalwrt/bin/targets/mediatek/filogic/profiles.json
make[2]: Leaving directory '/home/xiaoyu/immortalwrt'
export MAKEFLAGS= ;make -w -r checksum
make[2]: Entering directory '/home/xiaoyu/immortalwrt'
make[2]: Leaving directory '/home/xiaoyu/immortalwrt'
make[1]: Leaving directory '/home/xiaoyu/immortalwrt'

只改了3个选项   架构 类型 型号 其他全默认。编译环境ubuntu22.04 按照教程一步一步做的
请教大神我要怎么改？

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
编译正常结束。
