### ISSUE TITLE
23.05分支选用firewall防火墙编译在状态栏查看防火墙提示检测到旧版规则

### ISSUE THREAD

**Issue by smdx** [immortalwrt/immortalwrt#1467]
### Describe the bug

23.05分支选用firewall防火墙编译，在状态栏查看防火墙有检测到旧版规则提示。
请问要怎么解决这个问题？谢谢

防火墙编译选项
CONFIG_PACKAGE_firewall=y
# CONFIG_PACKAGE_firewall4 is not set

使用环境：
PVE虚拟机运行op

提示：
检测到旧版规则
系统上存在旧版 iptables 规则。 不鼓励混合使用 iptables 和 nftables 规则，这可能会导致流量过滤不完整。

然后点击那个 打开iptables 规则概况，显示列表规则是空的。

![2024-09-18_121744](https://github.com/user-attachments/assets/2b253731-4ef5-4302-ba0b-61bab5c2c599)

![2024-09-18_121819](https://github.com/user-attachments/assets/dfb267b9-13e2-408f-b8cd-23acf359d80f)

### ImmortalWrt version

r27999-7a79b154af

### ImmortalWrt release

23.05-SNAPSHOT

### ImmortalWrt target/subtarget

x86/64

### Device

QEMU Standard PC (Q35 + ICH9, 2009)

### Image kind

Official downloaded image

### Terms

- [x] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
旧版规则即 firewall3 iptables，不再获得任何支持。
