### ISSUE TITLE
报告一个dhcp/dns的问题

### ISSUE THREAD

**Issue by 142857X1** [immortalwrt/immortalwrt#1477]
### Describe the bug

在常规  地址 添加/time.android.com/203.107.6.88
 将域名强制指向某个 IP 地址 工作不正常，经常性的重启google tv 造成 已连接  没有网络权限等问题要等好几分钟 甚至重新连接wifi，才正常

而添加路由器的hosts 则完全没有这问题，故判断dhcp/dns中的将域名强制指向某个 IP 地址 有工作不正常。

### ImmortalWrt version

r27917-81a1f98d5b

### ImmortalWrt release

23.05.3

### ImmortalWrt target/subtarget

mediatek/filogic

### Device

CMCC RAX3000M eMMC version (custom U-Boot layout)

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
1. 默认固件无法复现。
2. 可以从 DHCP 主机名 指定。
