### ISSUE TITLE
RAX3000 编译成功后不生成可刷写固件

### ISSUE THREAD

**Issue by 1967937965** [immortalwrt/immortalwrt#1478]
### Describe the bug

RAX3000 编译成功后不生成可刷写固件

### ImmortalWrt version

master

### ImmortalWrt release

master

### ImmortalWrt target/subtarget

master

### Device

RAX3000 nadn

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
什么叫可刷写固件？

**Comment by 1967937965** [comment]
bin文件

**Comment by 1715173329** [comment]
本项目不支持第三方 uboot，如何刷入自行查阅文档。

**Comment by initzhu** [comment]
make带-i -k导致的
