### ISSUE TITLE
2.4G设置强制40Mhz频宽，设备连入后显示20Mhz频宽，速度上不去。

### ISSUE THREAD

**Issue by lipanzjzs** [immortalwrt/immortalwrt#1526]
设备型号：红米AX6000
系统：23.05

wifi2.4g设置如下：
<img width="1212" alt="截屏2024-10-19 07 34 26" src="https://github.com/user-attachments/assets/c43647e5-252d-47a0-91e0-0a76b386c59f">
使用iphone13与macbook连接，均显示只有20Mhz频宽，速度提不上去。试过换工作频率和手工指定信道，都不行。

**Comment by 1715173329** [comment]
openwrt/openwrt#14626

2.4 GHz 谈什么速度，不用 5 GHz 是有什么心事吗？
