### ISSUE TITLE
[X86] 内核启动报错

### ISSUE THREAD

**Issue by skefy** [immortalwrt/immortalwrt#1533]
### Describe the bug

自己编译的固件，启动过程一个关于内核的error，但是最终可以正常启动使用。不知道会不会有潜在影响，请大佬帮忙判断。

机器是倍控G31 Intel-7505 CPU。

具体日志如下：

Sun Oct 20 01:46:29 2024 kern.debug kernel: [    3.347571] pnp 00:01: [dma 0 disabled]
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.347694] system 00:02: [io  0x0680-0x069f] has been reserved
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.353696] system 00:02: [io  0x164e-0x164f] has been reserved
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.359778] system 00:03: [io  0x1854-0x1857] has been reserved
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.366428] system 00:04: [mem 0xfedc0000-0xfedc7fff] has been reserved
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.373124] system 00:04: [mem 0xfeda0000-0xfeda0fff] has been reserved
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.379811] system 00:04: [mem 0xfeda1000-0xfeda1fff] has been reserved
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.386500] system 00:04: [mem 0xc0000000-0xcfffffff] has been reserved
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.393187] system 00:04: [mem 0xfed20000-0xfed7ffff] has been reserved
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.399867] system 00:04: [mem 0xfed90000-0xfed93fff] could not be reserved
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.406900] system 00:04: [mem 0xfed45000-0xfed8ffff] could not be reserved
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.413934] system 00:04: [mem 0xfee00000-0xfeefffff] could not be reserved
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.423323] system 00:05: [io  0x1800-0x18fe] could not be reserved
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.429675] system 00:05: [mem 0xfe000000-0xfe01ffff] could not be reserved
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.436715] system 00:05: [mem 0xfe04c000-0xfe04ffff] has been reserved
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.443407] system 00:05: [mem 0xfe050000-0xfe0affff] has been reserved
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.450086] system 00:05: [mem 0xfe0d0000-0xfe0fffff] has been reserved
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.456774] system 00:05: [mem 0xfe200000-0xfe7fffff] has been reserved
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.463454] system 00:05: [mem 0xff000000-0xffffffff] has been reserved
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.470138] system 00:05: [mem 0xfd000000-0xfd68ffff] has been reserved
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.476827] system 00:05: [mem 0xfd6b0000-0xfd6cffff] has been reserved
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.483510] system 00:05: [mem 0xfd6f0000-0xfdffffff] has been reserved
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.490448] system 00:06: [io  0x2000-0x20fe] has been reserved
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.496762] pnp: PnP ACPI: found 8 devices
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.505818] clocksource: acpi_pm: mask: 0xffffff max_cycles: 0xffffff, max_idle_ns: 2085701024 ns
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.514821] NET: Registered PF_INET protocol family
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.519959] IP idents hash table entries: 262144 (order: 9, 2097152 bytes, linear)
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.529745] tcp_listen_portaddr_hash hash table entries: 8192 (order: 5, 131072 bytes, linear)
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.538474] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, linear)
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.546304] TCP established hash table entries: 131072 (order: 8, 1048576 bytes, linear)
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.554636] TCP bind hash table entries: 65536 (order: 9, 2097152 bytes, linear)
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.562434] TCP: Hash tables configured (established 131072 bind 65536)
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.569145] UDP hash table entries: 8192 (order: 6, 262144 bytes, linear)
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.576060] UDP-Lite hash table entries: 8192 (order: 6, 262144 bytes, linear)
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.583429] NET: Registered PF_UNIX/PF_LOCAL protocol family
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.589177] resource: avoiding allocation from e820 entry [mem 0x0009f000-0x000fffff]
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.597096] resource: avoiding allocation from e820 entry [mem 0x0009f000-0x000fffff]
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.605003] pci 0000:00:1f.5: BAR 0: assigned [mem 0x50d04000-0x50d04fff]
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.611875] pci 0000:00:06.0: PCI bridge to [bus 01]
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.616900] pci 0000:00:06.0:   bridge window [mem 0x50c00000-0x50cfffff]
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.623770] pci 0000:00:1c.0: PCI bridge to [bus 02]
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.628800] pci 0000:00:1c.0:   bridge window [mem 0x50a00000-0x50bfffff]
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.635668] pci 0000:00:1c.5: PCI bridge to [bus 03]
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.640695] pci 0000:00:1c.5:   bridge window [mem 0x50800000-0x509fffff]
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.647564] pci 0000:00:1c.6: PCI bridge to [bus 04]
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.652601] pci 0000:00:1c.6:   bridge window [mem 0x50600000-0x507fffff]
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.659472] pci 0000:00:1c.7: PCI bridge to [bus 05]
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.664500] pci 0000:00:1c.7:   bridge window [mem 0x50400000-0x505fffff]
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.671368] pci_bus 0000:00: resource 4 [io  0x0000-0x0cf7 window]
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.677615] pci_bus 0000:00: resource 5 [io  0x0d00-0xffff window]
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.683867] pci_bus 0000:00: resource 6 [mem 0x000a0000-0x000bffff window]
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.690822] pci_bus 0000:00: resource 7 [mem 0x000e0000-0x000fffff window]
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.697766] pci_bus 0000:00: resource 8 [mem 0x50400000-0xbfffffff window]
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.704714] pci_bus 0000:00: resource 9 [mem 0x4000000000-0x7fffffffff window]
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.712019] pci_bus 0000:01: resource 1 [mem 0x50c00000-0x50cfffff]
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.718356] pci_bus 0000:02: resource 1 [mem 0x50a00000-0x50bfffff]
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.724693] pci_bus 0000:03: resource 1 [mem 0x50800000-0x509fffff]
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.731024] pci_bus 0000:04: resource 1 [mem 0x50600000-0x507fffff]
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.737357] pci_bus 0000:05: resource 1 [mem 0x50400000-0x505fffff]
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.744190] PCI: CLS 64 bytes, default 64
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.748314] PCI-DMA: Using software bounce buffering for IO (SWIOTLB)
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.754858] software IO TLB: mapped [mem 0x0000000035d6f000-0x0000000039d6f000] (64MB)
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.762910] RAPL PMU: API unit is 2^-32 Joules, 3 fixed counters, 655360 ms ovfl timer
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.770933] RAPL PMU: hw unit of domain pp0-core 2^-14 Joules
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.776759] RAPL PMU: hw unit of domain package 2^-14 Joules
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.782497] RAPL PMU: hw unit of domain pp1-gpu 2^-14 Joules
Sun Oct 20 01:46:29 2024 kern.warn kernel: [    3.788258] resource: resource sanity check: requesting [mem 0x00000000fedc0000-0x00000000fedcdfff], which spans more than pnp 00:04 [mem 0xfedc0000-0xfedc7fff]
Sun Oct 20 01:46:29 2024 kern.warn kernel: [    3.802768] caller __uncore_imc_init_box+0xc3/0x130 mapping multiple BARs
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.809683] clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x3990bec8342, max_idle_ns: 881590769617 ns
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.819813] clocksource: Switched to clocksource tsc
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.824875] platform rtc_cmos: registered platform RTC device (no PNP device found)
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.833091] workingset: timestamp_bits=46 max_order=22 bucket_order=0
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.839709] squashfs: version 4.0 (2009/01/31) Phillip Lougher
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.845703] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 247)
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.855737] hv_vmbus: registering driver hyperv_fb
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.860762] input: Sleep Button as /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0E:00/input/input0
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.869236] ACPI: button: Sleep Button [SLPB]
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.873688] input: Power Button as /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0C:00/input/input1
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.882158] ACPI: button: Power Button [PWRB]
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.886607] input: Power Button as /devices/LNXSYSTM:00/LNXPWRBN:00/input/input2
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.894128] ACPI: button: Power Button [PWRF]
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.899373] thermal LNXTHERM:00: registered as thermal_zone0
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.905135] ACPI: thermal: Thermal Zone [TZ00] (28 C)
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.910365] Serial: 8250/16550 driver, 2 ports, IRQ sharing disabled
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.938966] 00:01: ttyS0 at I/O 0x3f8 (irq = 4, base_baud = 115200) is a 16550A
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.946701] Non-volatile memory driver v1.3
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.950995] Linux agpgart interface v0.103
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.955173] AMD-Vi: AMD IOMMUv2 functionality not available on this system - This is not a bug.
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.963987] ACPI: bus type drm_connector registered
Sun Oct 20 01:46:29 2024 kern.notice kernel: [    3.969512] i915 0000:00:02.0: [drm] Transparent Hugepage support is recommended for optimal performance on this platform!
Sun Oct 20 01:46:29 2024 kern.warn kernel: [    3.981758] i915 0000:00:02.0: Direct firmware load for i915/tgl_dmc_ver2_12.bin failed with error -2
Sun Oct 20 01:46:29 2024 kern.warn kernel: [    3.991104] i915 0000:00:02.0: Falling back to sysfs fallback for: i915/tgl_dmc_ver2_12.bin
Sun Oct 20 01:46:29 2024 kern.info kernel: [    3.999765] [drm] Initialized i915 1.6.0 20201103 for 0000:00:02.0 on minor 0
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.008059] ACPI: video: Video Device [GFX0] (multi-head: yes  rom: no  post: no)
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.016009] input: Video Bus as /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:00/input/input3
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.025499] i915 0000:00:02.0: [drm] Cannot find any crtc or sizes
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.031979] i915 0000:00:02.0: [drm] Cannot find any crtc or sizes
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.038768] loop: module loaded
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.042005] Guest personality initialized and is inactive
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.047493] VMCI host device registered (name=vmci, major=10, minor=127)
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.054290] Initialized host personality
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.058347] VMware PVSCSI driver - version 1.0.7.0-k
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.063401] hv_vmbus: registering driver hv_storvsc
Sun Oct 20 01:46:29 2024 kern.debug kernel: [    4.068636] ahci 0000:00:17.0: version 3.0
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.068639] nvme 0000:01:00.0: platform quirk: setting simple suspend
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.068889] ahci 0000:00:17.0: AHCI 0001.0301 32 slots 2 ports 6 Gbps 0x3 impl SATA mode
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.075208] nvme nvme0: pci function 0000:01:00.0
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.083386] ahci 0000:00:17.0: flags: 64bit ncq sntf pm clo only pio slum part deso sadm sds
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.097009] scsi host0: ahci
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.100024] scsi host1: ahci
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.103014] ata1: SATA max UDMA/133 abar m2048@0x50d02000 port 0x50d02100 irq 128
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.104220] nvme nvme0: 4/0/0 default/read/poll queues
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.110593] ata2: SATA max UDMA/133 abar m2048@0x50d02000 port 0x50d02180 irq 128
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.123484] VMware vmxnet3 virtual NIC driver - version 1.7.0.0-k-NAPI
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.130112] hv_vmbus: registering driver hv_netvsc
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.134575]  nvme0n1: p1 p2 p3 p128
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.134983] Fusion MPT base driver 3.04.20
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.142685] Copyright (c) 1999-2008 LSI Corporation
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.147630] Fusion MPT SPI Host driver 3.04.20
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.152153] Fusion MPT SAS Host driver 3.04.20
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.156739] xhci_hcd 0000:00:0d.0: xHCI Host Controller
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.162045] xhci_hcd 0000:00:0d.0: new USB bus registered, assigned bus number 1
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.170611] xhci_hcd 0000:00:0d.0: hcc params 0x20007fc1 hci version 0x120 quirks 0x0000000200009810
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.180054] xhci_hcd 0000:00:0d.0: xHCI Host Controller
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.185366] xhci_hcd 0000:00:0d.0: new USB bus registered, assigned bus number 2
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.192855] xhci_hcd 0000:00:0d.0: Host supports USB 3.1 Enhanced SuperSpeed
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.200107] hub 1-0:1.0: USB hub found
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.203941] hub 1-0:1.0: 1 port detected
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.208083] hub 2-0:1.0: USB hub found
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.211910] hub 2-0:1.0: 4 ports detected
**Sun Oct 20 01:46:29 2024 kern.err kernel: [    4.216013] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.UBTC.RUCC], AE_NOT_FOUND (20230628/psargs-332)
Sun Oct 20 01:46:29 2024 kern.err kernel: [    4.226320] ACPI Error: Aborting method \_SB.PC00.TXHC.RHUB.SS01._PLD due to previous error (AE_NOT_FOUND) (20230628/psparse-529)
Sun Oct 20 01:46:29 2024 kern.err kernel: [    4.238119] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.UBTC.RUCC], AE_NOT_FOUND (20230628/psargs-332)
Sun Oct 20 01:46:29 2024 kern.err kernel: [    4.248424] ACPI Error: Aborting method \_SB.PC00.TXHC.RHUB.SS01._PLD due to previous error (AE_NOT_FOUND) (20230628/psparse-529)
Sun Oct 20 01:46:29 2024 kern.err kernel: [    4.260214] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.UBTC.RUCC], AE_NOT_FOUND (20230628/psargs-332)
Sun Oct 20 01:46:29 2024 kern.err kernel: [    4.270519] ACPI Error: Aborting method \_SB.PC00.TXHC.RHUB.SS02._PLD due to previous error (AE_NOT_FOUND) (20230628/psparse-529)
Sun Oct 20 01:46:29 2024 kern.err kernel: [    4.282280] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.UBTC.RUCC], AE_NOT_FOUND (20230628/psargs-332)
Sun Oct 20 01:46:29 2024 kern.err kernel: [    4.292555] ACPI Error: Aborting method \_SB.PC00.TXHC.RHUB.SS02._PLD due to previous error (AE_NOT_FOUND) (20230628/psparse-529)
Sun Oct 20 01:46:29 2024 kern.err kernel: [    4.304313] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.UBTC.RUCC], AE_NOT_FOUND (20230628/psargs-332)
Sun Oct 20 01:46:29 2024 kern.err kernel: [    4.314591] ACPI Error: Aborting method \_SB.PC00.TXHC.RHUB.SS03._PLD due to previous error (AE_NOT_FOUND) (20230628/psparse-529)
Sun Oct 20 01:46:29 2024 kern.err kernel: [    4.326353] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.UBTC.RUCC], AE_NOT_FOUND (20230628/psargs-332)
Sun Oct 20 01:46:29 2024 kern.err kernel: [    4.336629] ACPI Error: Aborting method \_SB.PC00.TXHC.RHUB.SS03._PLD due to previous error (AE_NOT_FOUND) (20230628/psparse-529)
Sun Oct 20 01:46:29 2024 kern.err kernel: [    4.348398] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.UBTC.RUCC], AE_NOT_FOUND (20230628/psargs-332)
Sun Oct 20 01:46:29 2024 kern.err kernel: [    4.358668] ACPI Error: Aborting method \_SB.PC00.TXHC.RHUB.SS04._PLD due to previous error (AE_NOT_FOUND) (20230628/psparse-529)
Sun Oct 20 01:46:29 2024 kern.err kernel: [    4.370435] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.UBTC.RUCC], AE_NOT_FOUND (20230628/psargs-332)
Sun Oct 20 01:46:29 2024 kern.err kernel: [    4.380706] ACPI Error: Aborting method \_SB.PC00.TXHC.RHUB.SS04._PLD due to previous error (AE_NOT_FOUND) (20230628/psparse-529)**
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.392724] xhci_hcd 0000:00:14.0: xHCI Host Controller
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.398011] xhci_hcd 0000:00:14.0: new USB bus registered, assigned bus number 3
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.406596] xhci_hcd 0000:00:14.0: hcc params 0x20007fc1 hci version 0x120 quirks 0x0000000200009810
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.416074] xhci_hcd 0000:00:14.0: xHCI Host Controller
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.421360] xhci_hcd 0000:00:14.0: new USB bus registered, assigned bus number 4
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.428833] xhci_hcd 0000:00:14.0: Host supports USB 3.1 Enhanced SuperSpeed
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.436074] hub 3-0:1.0: USB hub found
Sun Oct 20 01:46:29 2024 kern.info kernel: [    4.439904] hub 3-0:1.0: 12 ports detected

### ImmortalWrt version

r0-bb8da3b

### ImmortalWrt release

SNAPSHOT

### ImmortalWrt target/subtarget

x86/64

### Device

Default string Default string

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
https://askubuntu.com/questions/1416198/ubuntu-22-04-acpi-bios-error-bug-could-not-resolve-symbol-errors-on-asus-x7
