### ISSUE TITLE
x86平台警告: xt_FULLCONENAT: warning: failed to register a conntrack notifier.

### ISSUE THREAD

**Issue by lysgwl** [immortalwrt/immortalwrt#1547]
### Describe the bug

xt_FULLCONENAT模块开机出现以下告警，该如何解决：
xt_FULLCONENAT: warning: failed to register a conntrack notifier. Disable active GC for mappings
![Snipaste_2024-10-26_09-44-14](https://github.com/user-attachments/assets/947b8136-0fc9-4d2d-beab-4534d7de326c)

内核日志
[kernel.log](https://github.com/user-attachments/files/17529069/kernel.log)

### ImmortalWrt version

25.05.4

### ImmortalWrt release

r28061

### ImmortalWrt target/subtarget

399f9a1db3 

### Device

QEMU Standard PC (i440FX + PIIX, 1996)

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
1. 这是预期输出
2. firewall3 不再受本项目支持，使用后果自负
