### ISSUE TITLE
Boards based on Snapdragon 210/410/615 disappeared ...?

### ISSUE THREAD

**Issue by akbar-npj** [immortalwrt/immortalwrt#1554]
### Describe the bug

Hi, Boards based on Snapdragon 210/410/615 chipsets is not shown in immortalwrt target devices....  Is it intentional or is missed somehow ?

### ImmortalWrt version

23.05

### ImmortalWrt release

23.05

### ImmortalWrt target/subtarget

msm89xx

### Device

msm8916

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
These devices have never been supported.
