### ISSUE TITLE
wireguard 软件包，从dpkg软件源安装，提示内核不兼容，23.05.5的内核过于新，

### ISSUE THREAD

**Issue by Itime-ren** [immortalwrt/immortalwrt#1555]
### Describe the bug

如上

### ImmortalWrt version

23.05.05

### ImmortalWrt release

23.05.05

### ImmortalWrt target/subtarget

dpkg安装

### Device

23.05.05

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
只有从**ImmortalWrt 官方**下载的**稳定版本**才能直接安装内核模块（快照版只有最新构建版本支持）。自编译固件只能自行编译集成。
