### ISSUE TITLE
luci页面查看连接信息出现luci挂掉的情况

### ISSUE THREAD

**Issue by adaptrum-richard** [immortalwrt/immortalwrt#1556]
### Describe the bug

1. 关闭hnat
2. 路由器正常启动
3. tcp/udp连接数大约在7000条
4. 点击luci页面状态->实时信息->连接
5. 出现无法获取连接信息，再次刷新页面时，出现/usr/lib/lua/luci/dispatcher.lua:427: /etc/config/luci seems to be corrupt, unable to find section 'main'

6. ssh登陆到路由器执行/etc/init.d/rpcd restart，可以正常进入luci页面
7. 当tcp/udp连接数低于3000时，不会出现此bug

### ImmortalWrt version

r20660-d25a97123e

### ImmortalWrt release

21.02-SNAPSHOT

### ImmortalWrt target/subtarget

mediatek/mt7986

### Device

JDCloud RE-CP-03

### Image kind

Official downloaded image

### Steps to reproduce

1. 关闭hnat
2. 路由器正常启动
3. tcp/udp连接数大约在7000条
4. 点击luci页面状态->实时信息->连接
5. 出现无法获取连接信息，再次刷新页面时，出现/usr/lib/lua/luci/dispatcher.lua:427: /etc/config/luci seems to be corrupt, unable to find section 'main'
6. ssh登陆到路由器执行/etc/init.d/rpcd restart，可以正常进入luci页面

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
1. 21.02 已经在去年停止支持。
2. 21.02 没有 mt7986 支持。
