### ISSUE TITLE
build variant: full-internal

### ISSUE THREAD

**Issue by lexin8** [immortalwrt/immortalwrt#1569]
make[3] -C package/network/services/hostapd compile
    ERROR: package/network/services/hostapd failed to build (build variant: full-internal).
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/workdir/openwrt/include/toplevel.mk:232: world] Error 1
WARNING: Makefile 'package/feeds/packages/dae/Makefile' has a dependency on 'kmod-xdp-sockets-diag', which does not exist
WARNING: Makefile 'package/feeds/packages/daed/Makefile' has a dependency on 'kmod-xdp-sockets-diag', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'prism54-firmware', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'rtl8192su-firmware', which does not exist
WARNING: Makefile 'package/kernel/mac80211/Makefile' has a dependency on 'kmod-qrtr-smd', which does not exist
WARNING: Makefile 'package/kernel/mac80211/Makefile' has a dependency on 'kmod-qrtr-mhi', which does not exist
WARNING: Makefile 'package/feeds/packages/strongswan/Makefile' has a dependency on 'kmod-crypto-chacha20poly1305', which does not exist
WARNING: Makefile 'package/feeds/packages/switchdev-poller/Makefile' has a dependency on 'swconfig', which does not exist
make[2]: Entering directory '/workdir/openwrt/scripts/config'

make[3]: Entering directory '/workdir/openwrt/feeds/luci/modules/luci-base'
[ ! -d ./src/ ] || cp -fpR ./src/* /workdir/openwrt/build_dir/hostpkg/luci-base
touch /workdir/openwrt/build_dir/hostpkg/luci-base/.prepared6a8e8daf9f61bc576c8470076a5b178d_6664517399ebbbc92a37c5bb081b5c53
touch /workdir/openwrt/build_dir/hostpkg/luci-base/.configured
make -C src/ clean po2lmo jsmin
make[4]: Entering directory '/workdir/openwrt/feeds/luci/modules/luci-base/src'
rm -f contrib/lemon lib/*.o lib/plural_formula.c lib/plural_formula.h core.so version.uc
cc -o contrib/lemon contrib/lemon.c
./contrib/lemon -q lib/plural_formula.y
cc    -DNDEBUG -c -o lib/lmo.o lib/lmo.c
cc    -DNDEBUG -c -o lib/plural_formula.o lib/plural_formula.c
cc  -o po2lmo po2lmo.o lib/lmo.o lib/plural_formula.o
make[4]: 'jsmin' is up to date.
make[4]: Leaving directory '/workdir/openwrt/feeds/luci/modules/luci-base/src'
touch /workdir/openwrt/build_dir/hostpkg/luci-base/.built
install -d -m0755 /workdir/openwrt/staging_dir/hostpkg/bin
install -m0755 src/po2lmo /workdir/openwrt/staging_dir/hostpkg/bin/po2lmo
install -m0755 src/jsmin /workdir/openwrt/staging_dir/hostpkg/bin/jsmin
mkdir -p /workdir/openwrt/staging_dir/hostpkg/stamp
touch /workdir/openwrt/build_dir/hostpkg/luci-base/.built
touch /workdir/openwrt/staging_dir/hostpkg/stamp/.luci-base_installed 
make[3]: Leaving directory '/workdir/openwrt/feeds/luci/modules/luci-base'
time: package/feeds/luci/luci-base/host-compile#1.24#0.31#1.52
make[3]: Entering directory '/workdir/openwrt/package/firmware/wireless-regdb'
mkdir -p /workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/stamp
SHELL= flock /workdir/openwrt/tmp/.root-copy.flock -c 'cp -fpR /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/wireless-regdb-2024.07.04/.pkgdir/wireless-regdb/. /workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/'
touch /workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek/stamp/.wireless-regdb_installed
echo "wireless-regdb" >> /workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/pkginfo/wireless-regdb.default.install
make[3]: Leaving directory '/workdir/openwrt/package/firmware/wireless-regdb'
time: package/firmware/wireless-regdb/compile#0.13#0.06#0.18
make[2]: Circular package/network/services/hostapd/compile <- package/utils/ucode/compile dependency dropped.
make[3]: Entering directory '/workdir/openwrt/package/network/services/hostapd'
rm -f /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/hostapd-full-internal/hostapd-2023-09-08-e5ccbfc6/.built
touch /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/hostapd-full-internal/hostapd-2023-09-08-e5ccbfc6/.built_check
CFLAGS="-I/workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/libnl-tiny -I/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/hostapd-full-internal/hostapd-2023-09-08-e5ccbfc6/src/crypto -I/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-12.3.0_musl/usr/include -I/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-12.3.0_musl/include/fortify -I/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-12.3.0_musl/include -DCONFIG_LIBNL20 -D_GNU_SOURCE  -Os -pipe -mcpu=cortex-a53 -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/hostapd-full-internal/hostapd-2023-09-08-e5ccbfc6=hostapd-2023-09-08-e5ccbfc6 -ffunction-sections -fdata-sections -flto=auto -fno-fat-lto-objects -Wformat -Werror=format-security -DPIC -fPIC -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" make  -C /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/hostapd-full-internal/hostapd-2023-09-08-e5ccbfc6/hostapd AR="aarch64-openwrt-linux-musl-gcc-ar" AS="aarch64-openwrt-linux-musl-gcc -c -Os -pipe -mcpu=cortex-a53 -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/hostapd-full-internal/hostapd-2023-09-08-e5ccbfc6=hostapd-2023-09-08-e5ccbfc6 -ffunction-sections -fdata-sections -flto=auto -fno-fat-lto-objects -Wformat -Werror=format-security -DPIC -fPIC -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=aarch64-openwrt-linux-musl-ld NM="aarch64-openwrt-linux-musl-gcc-nm" CC="aarch64-openwrt-linux-musl-gcc" GCC="aarch64-openwrt-linux-musl-gcc" CXX="aarch64-openwrt-linux-musl-g++" RANLIB="aarch64-openwrt-linux-musl-gcc-ranlib" STRIP=aarch64-openwrt-linux-musl-strip OBJCOPY=aarch64-openwrt-linux-musl-objcopy OBJDUMP=aarch64-openwrt-linux-musl-objdump SIZE=aarch64-openwrt-linux-musl-size CONFIG_ACS=y CONFIG_DRIVER_NL80211=y CONFIG_IEEE80211AC=y CONFIG_IEEE80211AX=y CONFIG_MBO=y CONFIG_UCODE=y LIBS="-L/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-12.3.0_musl/usr/lib -L/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-12.3.0_musl/lib -Wl,--gc-sections -flto=auto -fuse-linker-plugin -DPIC -fPIC -specs=/workdir/openwrt/include/hardened-ld-pie.specs -znow -zrelro -lubox -lubus -lblobmsg_json -lucode -lm -lnl-tiny" LIBS_c="" AR="aarch64-openwrt-linux-musl-gcc-ar" BCHECK= V=1  hostapd hostapd_cli 
make[4]: Entering directory '/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/hostapd-full-internal/hostapd-2023-09-08-e5ccbfc6/hostapd'
aarch64-openwrt-linux-musl-gcc -c -o /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/hostapd-full-internal/hostapd-2023-09-08-e5ccbfc6/build/hostapd/main.o -I/workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/libnl-tiny -I/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/hostapd-full-internal/hostapd-2023-09-08-e5ccbfc6/src/crypto -I/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-12.3.0_musl/usr/include -I/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-12.3.0_musl/include/fortify -I/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-12.3.0_musl/include -DCONFIG_LIBNL20 -D_GNU_SOURCE  -Os -pipe -mcpu=cortex-a53 -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/hostapd-full-internal/hostapd-2023-09-08-e5ccbfc6=hostapd-2023-09-08-e5ccbfc6 -ffunction-sections -fdata-sections -flto=auto -fno-fat-lto-objects -Wformat -Werror=format-security -DPIC -fPIC -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/hostapd-full-internal/hostapd-2023-09-08-e5ccbfc6/src -I/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/hostapd-full-internal/hostapd-2023-09-08-e5ccbfc6/src/utils -DHOSTAPD -DCONFIG_TAXONOMY -DCONFIG_ELOOP_EPOLL -DUBUS_SUPPORT -DUCODE_SUPPORT -DCONFIG_FULL_DYNAMIC_VLAN -DCONFIG_CTRL_IFACE_MIB -DCONFIG_CTRL_IFACE_UNIX -DCONFIG_CTRL_IFACE -DCONFIG_RSN_PREAUTH -DCONFIG_OCV -DCONFIG_IEEE80211R -DCONFIG_IEEE80211R_AP -DCONFIG_ETH_P_OUI -DCONFIG_AIRTIME_POLICY -DCONFIG_WNM -DCONFIG_WNM_AP -DCONFIG_IEEE80211AC -DCONFIG_IEEE80211AX -DCONFIG_MBO -DNO_SUPPLICANT -DCONFIG_DRIVER_WIRED -DCONFIG_DRIVER_NL80211 -I/workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/libnl3  -DCONFIG_ERP -DEAP_SERVER_MD5 -DEAP_SERVER_TLS -DEAP_SERVER_PEAP -DEAP_SERVER_TTLS -DEAP_SERVER_MSCHAPV2 -DEAP_SERVER_GTC -DEAP_SERVER_FAST -DCONFIG_WPS -DEAP_SERVER_WSC -DEAP_SERVER_IDENTITY -DEAP_SERVER -DPKCS12_FUNCS -DEAP_TLS_FUNCS -DCONFIG_TLS_INTERNAL -DCONFIG_TLS_INTERNAL -DCONFIG_TLS_INTERNAL_SERVER -DCONFIG_CRYPTO_INTERNAL -DCONFIG_INTERNAL_LIBTOMMATH -DCONFIG_DES -DCONFIG_SHA256 -DCONFIG_HMAC_SHA256_KDF -DCONFIG_INTERNAL_SHA384 -DCONFIG_INTERNAL_SHA512 -DCONFIG_NO_RANDOM_POOL -DRADIUS_SERVER -DCONFIG_IPV6 -DNEED_AP_MLME -DCONFIG_HS20 -DCONFIG_INTERWORKING -DCONFIG_PROXYARP -DCONFIG_ACS -DCONFIG_DEBUG_SYSLOG main.c
In file included from /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/hostapd-full-internal/hostapd-2023-09-08-e5ccbfc6/src/ap/ucode.h:4,
                 from /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/hostapd-full-internal/hostapd-2023-09-08-e5ccbfc6/src/ap/hostapd.h:22,
                 from main.c:26:
/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/hostapd-full-internal/hostapd-2023-09-08-e5ccbfc6/src/utils/ucode.h:6:10: fatal error: ucode/lib.h: No such file or directory
    6 | #include <ucode/lib.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[4]: *** [../src/build.rules:89: /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/hostapd-full-internal/hostapd-2023-09-08-e5ccbfc6/build/hostapd/main.o] Error 1
make[4]: Leaving directory '/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/hostapd-full-internal/hostapd-2023-09-08-e5ccbfc6/hostapd'
make[3]: *** [Makefile:817: /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/hostapd-full-internal/hostapd-2023-09-08-e5ccbfc6/.built] Error 2
make[3]: Leaving directory '/workdir/openwrt/package/network/services/hostapd'
time: package/network/services/hostapd/full-internal/compile#0.33#0.19#0.51
    ERROR: package/network/services/hostapd failed to build (build variant: full-internal).
make[2]: *** [package/Makefile:129: package/network/services/hostapd/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:123: /workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:232: world] Error 2

**Comment by 1715173329** [comment]
Use official source code.
