### ISSUE TITLE
msd_lite可用但omcproxy不可用

### ISSUE THREAD

**Issue by qwerttvv** [immortalwrt/immortalwrt#1571]
### Describe the bug

后台进程都在，接口也都设置了，在br-lan启用了igmp snooping，msd_lite可正常使用，omcproxy不可用

### ImmortalWrt version

SNAPSHOT，昨天刚刚编译的，同步到1602dae0fef5e8e759958c1aa90d57c75cee84ef

### ImmortalWrt release

SNAPSHOT，昨天刚刚编译的，同步到1602dae0fef5e8e759958c1aa90d57c75cee84ef

### ImmortalWrt target/subtarget

VIKINGYFY/immortalwrt ipq6018

### Device

 ax18

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
> I am reporting an issue for ImmortalWrt, not an unsupported fork.
