### ISSUE TITLE
br-lan: received packet on eth1 with own address as source address (addr:ea:ec:03:bc:ea:2b, vlan:0)

### ISSUE THREAD

**Issue by written143** [immortalwrt/immortalwrt#1589]
### Describe the bug

主路由r4s
lan口连接了ap模式的红米ax6000
2个红米ax1800连到红米ax6000
组有线mesh
每隔一段时间就会出现A：[163804.964712] br-lan: received packet on eth1 with own address as source address (addr:ea:ec:03:bc:ea:2b, vlan:0)
网络中并没有环路
![image](https://github.com/user-attachments/assets/23c75553-783c-4822-b2d0-0efeecf25374)

### ImmortalWrt version

23.05.4

### ImmortalWrt release

23.05.4

### ImmortalWrt target/subtarget

23.05.4

### Device

r4s

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
字面意思，你 ap 问题。
