### ISSUE TITLE
Nanopi系列机型无法启动

### ISSUE THREAD

**Issue by smallprogram** [immortalwrt/immortalwrt#1593]
### Describe the bug

从[downloads.immortalwrt.org](https://downloads.immortalwrt.org/)网站下载的[ImmortalWrt 23.05.3](https://downloads.immortalwrt.org/releases/23.05.3/targets/)的R4S、R5S等固件刷写道tf卡中可以完美启动。

从[downloads.immortalwrt.org](https://downloads.immortalwrt.org/)网站下载的[Snapshot download](https://downloads.immortalwrt.org/snapshots/targets/)的R4S、R5S等固件刷写道tf卡中可以启动，可以获取IP，但是无法访问luci界面，无法进行SSH访问，无法进行任何配置。

通过最新源码snapshots编译的R4S、R5S等，刷入TF卡就无法启动，Lan口无法获取IP，SSH无法连接

### ImmortalWrt version

r32428-a0bab0ccc8

### ImmortalWrt release

snapshots

### ImmortalWrt target/subtarget

rockchip/armv8

### Device

Nanopi R4S

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
No log = no solution.

**Comment by smallprogram** [comment]
> No log = no solution.

@1715173329 大佬，不是我不提供日志，是真没有日志，我借了R5S和R4S，把固件刷到TF卡里，根本就起不来。用lean就固件就没问题，R5S有HDMI视频输出，用immortalwrt的源码编译，连视频输出信号都没有

**Comment by VIKINGYFY** [comment]
R4S启动不了应该快有半年了，某次uboot更新后就启动不了了，一模一样的情况，R5C正常，最后把R4S卖了。。。

**Comment by smallprogram** [comment]
> R4S启动不了应该快有半年了，某次uboot更新后就启动不了了，一模一样的情况，R5C正常，最后把R4S卖了。。。

R5S也不行啊，并且R5S的HDMI都没有视频输出信号

**Comment by VIKINGYFY** [comment]
> > R4S启动不了应该快有半年了，某次uboot更新后就启动不了了，一模一样的情况，R5C正常，最后把R4S卖了。。。
> 
> R5S也不行啊，并且R5S的HDMI都没有视频输出信号

我的是R5C，不是R5S

**Comment by 1715173329** [comment]
No useful information to debug, closing.

**Comment by ssd2077** [comment]
R4S的话我记得我之前拿官方的r8168替换，然后正常运行。我今天再试试。

**Comment by ssd2077** [comment]
测试能用。不过记得把120-r8168-add-LED-configuration-from-OF.patch补丁加回去。不然lan口只亮一个灯。

**Comment by ssd2077** [comment]
而且我发现祖传bug（5.x内核没问题）还在。6.x内核，用ipv6 nat。单线程上行速度异常（lan口到外网）。但是udp传输的话，好像没事。
