### ISSUE TITLE
快照版离线安装apk提示UNTRUSTED signature

### ISSUE THREAD

**Issue by iwowcn** [immortalwrt/immortalwrt#1602]
### Describe the bug

ERROR: /tmp/upload.apk: UNTRUSTED signature
![PixPin_2024-11-24_22-13-11](https://github.com/user-attachments/assets/391bcd2b-8662-4338-99d9-f93b03cca4c5)

### ImmortalWrt version

r32502-b8917e7d1c

### ImmortalWrt release

SNAPSHOT

### ImmortalWrt target/subtarget

x86/64

### Device

Default string

### Image kind

Self-built image

### Additional info

构建镜像软件包列表：
automount
base-files
ca-bundle
dnsmasq-full
dropbear
fdisk
firewall4
fstools
grub2-bios-setup
i915-firmware-dmc
kmod-8139cp
kmod-8139too
kmod-button-hotplug
kmod-e1000e
kmod-fs-f2fs
kmod-i40e
kmod-igb
kmod-igbvf
kmod-igc
kmod-ixgbe
kmod-ixgbevf
kmod-nft-offload
kmod-pcnet32
kmod-r8101
kmod-r8125
kmod-r8126
kmod-r8168
kmod-tulip
kmod-usb-hid
kmod-usb-net
kmod-usb-net-asix
kmod-usb-net-asix-ax88179
kmod-usb-net-rtl8150
kmod-usb-net-rtl8152-vendor
kmod-vmxnet3
libc
libgcc
logd
mkf2fs
mtd
netifd
nftables
odhcp6c
odhcpd-ipv6only
partx-utils
ppp
ppp-mod-pppoe
uci
uclient-fetch
urandom-seed
urngd
kmod-amazon-ena
kmod-amd-xgbe
kmod-bnx2
kmod-e1000
kmod-dwmac-intel
kmod-forcedeth
kmod-fs-vfat
kmod-tg3
apk-mbedtls
e2fsprogs
libustream-mbedtls
kmod-r8169
luci
autocore
block-mount
busybox
default-settings-chn
kmod-nf-nathelper
kmod-nf-nathelper-extra
luci-compat
luci-lib-base
procd
procd-seccomp
procd-ujail
owut
losetup
resize2fs
blkid
curl
luci-i18n-base-zh-cn
luci-i18n-package-manager-zh-cn
luci-i18n-firewall-zh-cn
luci-theme-argon
luci-app-ddns-go
luci-i18n-ddns-go-zh-cn
luci-app-autoreboot
luci-i18n-autoreboot-zh-cn
luci-app-arpbind
luci-i18n-arpbind-zh-cn
luci-app-vlmcsd
luci-i18n-vlmcsd-zh-cn
luci-app-wol
luci-i18n-wol-zh-cn

### Diffconfig

```text
没找见有diffconfig.sh脚本
```

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
第三方打包的 apk 不会被信任。

**Comment by iwowcn** [comment]
> 第三方打包的 apk 不会被信任。

大佬 apk update出现下方错误是什么原因？
![PixPin_2024-11-24_23-09-43](https://github.com/user-attachments/assets/72670e33-2463-48f6-8173-ac07d842e774)

**Comment by 1715173329** [comment]
这不是错误，正常输出而已。

**Comment by iwowcn** [comment]
> 这不是错误，正常输出而已。

明白了。谢谢！一直以为是报错。

**Comment by fuliaojiyue** [comment]
> 第三方资源的apk不会被信任。

请问有办法绕开吗？我需要安装个lucky，谢谢

**Comment by iwowcn** [comment]
apk add --allow-untrusted  手动命令行安装，应该是可以在apk配置文件里关掉签名检查的，但是我没找见。发自我的 iPhone在 2024年11月26日，08:08，fuliaojiyue ***@***.***> 写道：﻿

第三方资源的apk不会被信任。

请问有办法绕开吗？我需要安装个lucky，谢谢
