### ISSUE TITLE
近几天编译的主分支在更新系统后总会被恢复出厂设置(已解决)

### ISSUE THREAD

**Issue by lwb1978** [immortalwrt/immortalwrt#1622]
### Describe the bug

近几天编译主分支的版本在网页更新后重启就会丢失所有设置，编译了x86和arm8都有这个问题。上周之前都好好的。

### ImmortalWrt version

主分支

### ImmortalWrt release

主分支

### ImmortalWrt target/subtarget

主分支

### Device

x86

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
无日志无配置，建议穿越回上周。

**Comment by 1715173329** [comment]
duplicate #1584
