### ISSUE TITLE
autocore: 安装后导致 luci-system 页 无法正常显示 arch

### ISSUE THREAD

**Issue by xlighting2017** [immortalwrt/immortalwrt#1632]
### Describe the bug

在 qualcommax/QNAP-301w 上触发

原因是 `autocore` 使用 `cat /proc/cpuinfo` 获取 arch 信息
但是在 301w 上 （其他平台/设备是否有类似情况未知）
上述命令的输出没有  `model name`，导致 `autocore` 认为获取失败，进而显示 ?
<img width="524" alt="image" src="https://github.com/user-attachments/assets/0745ee0b-4e09-475a-ae31-31f3981c12a6" />

对比 vanilla openwrt， 其 luci 使用的是  ubus 读取， 可以正常显示；
<img width="827" alt="image" src="https://github.com/user-attachments/assets/6a02f646-3fd0-40fe-a09e-c9a309aa04df" />

在含有 `autocore` 的同一个build上，使用以下命令也可以获得正确的 arch
`ubus call system board | jsonfilter -e @.system`

<img width="479" alt="image" src="https://github.com/user-attachments/assets/c9cd6996-2fde-4522-bb61-1e784f27ec5d" />

因此建议 `autocore` 也改成 `ubus` 获取

### ImmortalWrt version

SNAPSHOT

### ImmortalWrt release

SNAPSHOT

### ImmortalWrt target/subtarget

qualcommax/QNAP-301w

### Device

QNAP-301w

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
请使用官方 immortalwrt 源码。
