### ISSUE TITLE
23.05编译失败

### ISSUE THREAD

**Issue by cjlhll** [immortalwrt/immortalwrt#1638]
### Describe the bug

以前是正常编译的，最近编译失败，我是小白，不知道是什么原因。
这是完整日志：
[0_build.txt](https://github.com/user-attachments/files/18177013/0_build.txt)

### ImmortalWrt version

1

### ImmortalWrt release

1

### ImmortalWrt target/subtarget

1

### Device

N1

### Image kind

Official downloaded image

### Terms

- [x] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
非本项目支持的设备，非本项目集成的源码，不受支持。
