### ISSUE TITLE
homeproxy

### ISSUE THREAD

**Issue by xiaomayi755259** [immortalwrt/immortalwrt#1641]
### Describe the bug

编译完固件运行正常，但homeproxy选择gfwlist模式访问不了google,大陆白名单模式可以，请问大佬是怎么回事？

### ImmortalWrt version

23.05.4

### ImmortalWrt release

23.05.4

### ImmortalWrt target/subtarget

23.05.4

### Device

x86/64

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by xiaomayi755259** [comment]
![Screenshot_20241221_073453_Samsung Internet](https://github.com/user-attachments/assets/da151b8d-c1ce-41a2-aa43-29f94b5aa7e0)

**Comment by xiaomayi755259** [comment]
日志这样，远白名单模式日志也是这样

**Comment by science2468** [comment]
你访问下被墙的域名。没有sing-box客户端日志，从你发的图片，home proxy本身没问题。

Sent from [Proton Mail](https://proton.me/mail/home) for iOS

2024 年 12 月 21 日星期六 07:38, xiaomayi755259 ***@***.***(mailto:2024 年 12 月 21 日星期六 07:38, xiaomayi755259 <<a href=)> 来信：

**Comment by 1715173329** [comment]
去 homeproxy 库发 issue。
