### ISSUE TITLE
Dnsmasq 无法转发

### ISSUE THREAD

**Issue by qqsir-dev** [immortalwrt/immortalwrt#1644]
### Describe the bug

系统设置了其他DNS服务器但不生效，强制走Dnsmasq的127.0.0.1, 转发设置后很快就被被系统又设置回来了

### ImmortalWrt version

r0-1dbb52f

### ImmortalWrt release

r0-1dbb52f

### ImmortalWrt target/subtarget

r0-1dbb52f

### Device

VMware, Inc. VMware20,1 X86

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
用第三方源码的自行去问第三方。系统不会自己重置配置，除非你自己装了其他应用或修改。
