### ISSUE TITLE
Confusing project name

### ISSUE THREAD

**Issue by aparcar** [immortalwrt/immortalwrt#277]
Hello, this project uses a confusingly similar name to the official OpenWrt project (openwrt vs project-openwrt). Please rename the organization/project to something else.

**Comment by 1715173329** [comment]
Okay, but could you please give us a little more time?
We need some time to do this, but if it's really necessary we will rename it at once.

**Comment by aparcar** [comment]
Thank you very much for the quick response.

**Comment by 1715173329** [comment]
> Thank you very much for the quick response.

Certainly, it's our responsibility.
And we should say sorry to you for this.

**Comment by 1715173329** [comment]
Finally, we have registered the new domain to replace old one.

**Comment by aparcar** [comment]
Thank you very much!
