### ISSUE TITLE
ipv6没有显示

### ISSUE THREAD

**Issue by osxdiy** [immortalwrt/immortalwrt#279]
IPV6正常但是概况是无显示
![2021-02-08 14-08-53 的屏幕截图](https://user-images.githubusercontent.com/61264947/107182313-74205480-6a17-11eb-9dc6-c87eb3c7efd7.png)

**Comment by 1715173329** [comment]
什么叫做正常？
请出示你的接口页面截图

**Comment by AmadeusGhost** [comment]
代码逻辑是这样的：
```
<% if has_ipv6 then %>
var si6 = document.getElementById('wan6_i');
var ss6 = document.getElementById('wan6_s');
var ifc6 = info.wan6;

if (ifc6 && ifc6.ifname && ifc6.proto != 'none')
{
	xxx
else
{
	si6.innerHTML = '<img src="<%=resource%>/icons/ethernet_disabled.png" /><br /><small>?</small>';
	ss6.innerHTML = '<em><%:Not connected%></em>';
}
<% end %>
```
个人不觉得你的 ipv6 正常

**Comment by osxdiy** [comment]
我的IPV6是正常的，就是概况中IPV6 WAN无显示，是不是多拨造成的

**Comment by osxdiy** [comment]
![2021-02-08 17-26-02 的屏幕截图](https://user-images.githubusercontent.com/61264947/107200878-3af5dd80-6a33-11eb-907b-af52996a4455.png)
![2021-02-08 17-29-05 的屏幕截图](https://user-images.githubusercontent.com/61264947/107200884-3cbfa100-6a33-11eb-8173-7e3bc87f86f5.png)
接口如上

**Comment by AmadeusGhost** [comment]
wan6 没有拿到 ipv6 地址，自然不会显示。

**Comment by osxdiy** [comment]
用LEAN的原码编译的WAN6没有IPV6地址，但是IPV6 WAN 是显示的

**Comment by AmadeusGhost** [comment]
wan 或者 wan6 拿到都可以，应该是多拨搞乱的。

**Comment by osxdiy** [comment]
谢谢了

**Comment by 1715173329** [comment]
LuCI 默认从第一个防火墙为 `WAN` 的接口获取 IP 地址信息
按照图中所示，你的 `VWAN1` 没有有效 IPv6 信息，故不会显示

**Comment by osxdiy** [comment]
谢谢你的解答
