### ISSUE TITLE
master分支编译报如下错

### ISSUE THREAD

**Issue by asiaon123** [immortalwrt/immortalwrt#283]
* pkg_hash_fetch_best_installation_candidate: Packages for libreadline8 found, but incompatible with the architectures configured
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for autosamba:
 * 	libncursesw6
 * opkg_install_cmd: Cannot install package autosamba.
make[2]: *** [package/install] Error 255
make[1]: *** [/workdir/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_install] Error 2

**Comment by AmadeusGhost** [comment]
等上游修复吧，官方最近在大改，出问题难免

**Comment by 1715173329** [comment]
该问题已修复，请 `make clean` 后重新编译。

**Comment by asiaon123** [comment]
已编译确认修复好了
