### ISSUE TITLE
openwrt-18.06 定时任务

### ISSUE THREAD

**Issue by xiaobaishu1** [immortalwrt/immortalwrt#293]
我设置了定时重拨号结果每次断电再通电重启这个定时任务就消失了

**Comment by 1715173329** [comment]
请具体描述设备和行为。
请留意 Flash 空间是否足够。

**Comment by 1715173329** [comment]
由于长时间无回复，且无他人回报同样情况，该 issue 将被关闭。
如有任何更新，欢迎重新打开。
