### ISSUE TITLE
Problem compiling "Luci-app-dockerman" on immortalwrt 18.06

### ISSUE THREAD

**Issue by M33FT** [immortalwrt/immortalwrt#294]
First of all, thank you for your very good project . . .

I was using the "[Luci-app-dockerman](https://github.com/lisaac/luci-app-dockerman)" package in the Coolsnowwolf project and I had no problem compiling this package. But now while compiling "Luci-app-dockerman" in immortalwt 18.06, I encountered the following problem

**WARNING: Makefile 'package/luci-app-dockerman/applications/luci-app-dockerman/Makefile' has a dependency on 'docker-ce', which does not exist**

Of course I know that the "docker-ce" package does not exist in immortalwrt, but I did not have this problem in Lede.
Is there a way to add this package to immortalwrt?

Thanks for guiding me
@1715173329 @hue715

**Comment by AmadeusGhost** [comment]
This package "luci-app-dockerman" already exists, no need to add it manually. And docker-ce has been split into docker and dockerd: https://github.com/openwrt/packages/commit/249d7d8faa3a64e0d6108ee6274c4186bf35a4d7
