### ISSUE TITLE
18.06 k5.4 wireguard无法保存设置

### ISSUE THREAD

**Issue by ricksuzade-maker** [immortalwrt/immortalwrt#295]
昨晚3.2日编译版本，wireguard无法保存设置

**Comment by 1715173329** [comment]
什么设置？什么保存？

**Comment by ricksuzade-maker** [comment]
新建wireguard接口，在其中输入接口私钥以及peer节点公钥等信息，点击保存生效后，再次进入接口修改界面，发现先前输入的私钥以及peer信息全部丢失，无法保存生效，造成此wireguard接口无法使用。不知道说的清不清楚。
