### ISSUE TITLE
How do I enable wifi?

### ISSUE THREAD

**Issue by dausruddin** [immortalwrt/immortalwrt#299]
Hi. I am trying to enable wifi with my RTL8811CU USB adapter with no luck. I have selected rtl8821cu in `make menuconfig`, but Wireless menu does not show up.
![Screenshot from 2021-03-04 22-38-42](https://user-images.githubusercontent.com/5763466/109980002-6e7a0e00-7d3a-11eb-9e22-dda25b993602.png)

 Is there any additional packages I need to enable?

I am trying with branch 21.02.

Thanks

**Comment by AmadeusGhost** [comment]
> Is there any additional packages I need to enable?

Wpad and iwinfo are also necessary packages for wireless. Restart after plugging in the wireless network card. If it still does not appear, please send the kernel log and lsusb results.

**Comment by dausruddin** [comment]
I noticed something wrong. The adapter is detected as `Realtek DISK`
```root@ImmortalWrt:~# lsusb
Bus 002 Device 001: ID 1d6b:0001 Linux 5.4.99 ohci_hcd Generic Platform OHCI controller
Bus 004 Device 001: ID 1d6b:0003 Linux 5.4.99 xhci-hcd xHCI Host Controller
Bus 001 Device 003: ID 0bda:1a2b Realtek DISK
Bus 001 Device 001: ID 1d6b:0002 Linux 5.4.99 ehci_hcd EHCI Host Controller
Bus 003 Device 001: ID 1d6b:0002 Linux 5.4.99 xhci-hcd xHCI Host Controller
```

This is the image of the device. 
<img src="https://user-images.githubusercontent.com/5763466/110065230-a8362d80-7da9-11eb-8d71-87cc59b27587.jpg" width="250">



- Kernel log: [Log.txt](https://github.com/immortalwrt/immortalwrt/files/6088020/Log.txt)
- .config: [config.txt](https://github.com/immortalwrt/immortalwrt/files/6088024/config.txt)

**Comment by AmadeusGhost** [comment]
> Bus 001 Device 003: ID 0bda:1a2b Realtek DISK

It seems that usb-modeswitch is also needed to switch the usb mode, maybe you can find it on the search engine.

**Comment by dausruddin** [comment]
Sorry for the delay. I installed [usb-modeswitch](https://openwrt.org/packages/pkgdata/usb-modeswitch) and it is working great now.

Thanks a lot for your help :)

**Comment by kzh1980** [comment]
> Sorry for the delay. I installed [usb-modeswitch](https://openwrt.org/packages/pkgdata/usb-modeswitch) and it is working great now.
> 
> Thanks a lot for your help :)

it seems that i am having the same one. how do you set the WIFI setting of this device? could you please share yours?

this is my seetings, it didn't works 
Client mode,
AC, 5G,  149,  RU
CCMP force

if the seeting is corrent, the WIFI should be working under Master mode.

**Comment by dausruddin** [comment]
Hi @kzh1980. It has been a while and I no longer using usb wifi adapter. Now I am using a router. I can't remember sadly, but I'm sure that it didn't work when I turned on encryption (enabling password). It only work when I set to no encryption (no password).

I have this image that I captured back then.

<kbd>![IMG_20220204_090725_551](https://user-images.githubusercontent.com/5763466/152455557-058a905a-36a3-4ddf-9ad3-5f038564a710.jpg)</kbd>

And this is what my friend sent me, also long time ago.

<kbd>![IMG_20220204_090723_299](https://user-images.githubusercontent.com/5763466/152455638-a1f7559e-4d84-40be-8fa8-362177ce8511.jpg)</kbd>


Sorry I couldn't help much.
