### ISSUE TITLE
Problem with "https-dns-proxy" after reconnecting WAN in immortalwrt 18.06

### ISSUE THREAD

**Issue by M33FT** [immortalwrt/immortalwrt#307]
Hi . . .
Thank you for your wonderful program.
In the country where I live, DNS is "Hijacked".

![luci-app-https](https://user-images.githubusercontent.com/63062740/110100306-7e840300-7db7-11eb-93c4-9e9c56aec82a.jpg)

I am using this program on OpenWrt project and on Raspberrypi4B device and it works very well. The only problem I have is that when my WAN connection is disconnected (from the Provider) and after it comes back it does not open any website (because it is not Resolve) and I have to restart service "/etc/init.d/https-dns-proxy" from Startup or via Terminal to connect.
Can you tell me how I can solve this problem? Is there a way that I can restart the service after the shutdown, for example through Shell Script?
I saw a script somewhere on the internet but I do not think it is a shell script and if so where should it be used:

```
#!/bin/sh
# Put this script run in crond.

service=ocserv

if test $(netstat -na | grep 0.0.0.0:443 | wc -l) = 2
then
        echo "$service is running!"
else
        /etc/init.d/$service start
fi
```

Do I have to change the script above as follows? (Unfortunately, I do not know any scripting.)

![crontab_03](https://user-images.githubusercontent.com/63062740/110103160-df610a80-7dba-11eb-9e08-b8272d09c579.jpg)

**Is it possible for someone to help me solve this https problem after the WAN is down?**

**Comment by 1715173329** [comment]
Report it to upstream.
https://github.com/openwrt/packages/issues/new
