### ISSUE TITLE
你好我的同志们

### ISSUE THREAD

**Issue by i3roly** [immortalwrt/immortalwrt#312]
问候我亲爱的朋友们，

我正在寻找难以捉摸的MT7615 6.0.2.0软件版本。 我读过，我们的俄罗斯朋友已经在他们的KEENETIC路由器上部署了此修订版。 我希望这个新修订版能够解决2.4GHZ的低迷速度，并且已经完全实现了PMF功能，该功能会在5.0.4.0修订版上导致RX错误。

我之所以创建此讨论，是为了征求您的智慧以获取比5.0.4.0更新的修订版。 我为无法完全优化我的DIR-882而发疯。 如果您还可以将我指向较新的HW_NAT版本，那将很棒。

很抱歉打扰你！

**Comment by AmadeusGhost** [comment]
Emmm，您所说的新 mt7615 闭源驱动我们手里都没有，等泄露出来再说吧。一般而言，资源所有者必须确保放出这些东西不会违反 NDA（Non Disclosure Agreement）。

**Comment by i3roly** [comment]
@AmadeusGhost 我理解保密协议的意义，但是我很好奇我是否同意遵守该协议。 保留此类资源没有问题，因为我只发布了一个二进制文件。 您是否知道我可以从哪里获得此资源，我是否应该接受这样的协议？

**Comment by i3roly** [comment]
哦，我必须说，我确实希望这不会冒犯您：卡通色情作品对大脑不利。 请尝试观看更多传统的唤醒材料！

**Comment by AmadeusGhost** [comment]
> 因为我只发布了一个二进制文件。 

只有二进制文件应该是编译不了的，另外，您最好遵守 NDA，以免您和您的朋友不会被起诉。
