### ISSUE TITLE
IPSec VPN 服务器连接问题

### ISSUE THREAD

**Issue by raiden2007** [immortalwrt/immortalwrt#317]
r4s编译最新固件完成后.IPSec VPN 服务器配置完连接不上,系统日志报ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such device.错误.随后在添加了Universal TUN/TAP device driver support后.重新编译完成后.手机可以连接上ipsec vpn服务器了.但是只能访问内网跟路由器.不能浏览网站.请问这个问题要如何解决呢.感谢

**Comment by 1715173329** [comment]
解释了 114514 次了，自己用 SoftetherVPN。

**Comment by raiden2007** [comment]
新手.感谢大佬回答.我去试试
