### ISSUE TITLE
有些源的地址不对，不知道怎么改

### ISSUE THREAD

**Issue by zhangj3** [immortalwrt/immortalwrt#327]
应该是 http://182.140.223.146/dl/xxxx  而不是http://182.140.223.146/xxxxxx

![image](https://user-images.githubusercontent.com/49198958/111964580-ba48f780-8b2f-11eb-9ffd-caf5c0dd1d7a.png)

**Comment by 1715173329** [comment]
我大意了啊，没有闪。
稍后更新。
