### ISSUE TITLE
R2S编译后的gz解压出错。

### ISSUE THREAD

**Issue by igithublab** [immortalwrt/immortalwrt#337]
R2S使用的是20.02的分支变异的，貌似只有这个分支有R2S的target profile。
gunzip: immortalwrt-rockchip-armv8-friendlyarm_nanopi-r2s-ext4-sysupgrade.img.gz: trailing garbage ignored

虽然有以上报错，但是将解压出来的img文件写入sd卡还是能引导使用。但是直接使用balenaEtcher写gz文件则无法引导。

而且引导后，对sd卡剩余空间创建分区也会有异常。已经编译过很多次均有这个问题。希望大佬能看看是否有什么问题，谢谢！

另外，使用master分支编译的x86和树莓派都没有这个问题。

**Comment by AmadeusGhost** [comment]
现在 `git pull` 后再编译试试？
