### ISSUE TITLE
R2S最新21.02源码无法拨号？

### ISSUE THREAD

**Issue by y9858** [immortalwrt/immortalwrt#349]
云编译用sed -i 's,"eth1" "eth0","eth0" "eth1",g' target/linux/rockchip/armv8/base-files/etc/board.d/02_network
sed -i "s,'eth1' 'eth0','eth0' 'eth1',g" target/linux/rockchip/armv8/base-files/etc/board.d/02_network     交换了网口，拨号提示网络设备不存在，望大神早日修复，3Q。

**Comment by 1715173329** [comment]
那不交换网口呢？

**Comment by y9858** [comment]
> 那不交换网口呢？

没试 不过我用前几天的源码 没问题 应该是那个usbdrd3 patches的问题

**Comment by 1715173329** [comment]
I just reverted this commit.
