### ISSUE TITLE
更新系统后AdGuard恢复默认

### ISSUE THREAD

**Issue by Canary233** [immortalwrt/immortalwrt#350]
更新系统后,AdGuard会恢复默认，固件是github action自动编译的

**Comment by 1715173329** [comment]
描述不清。

**Comment by zxlhhyccc** [comment]
> 更新系统后,AdGuard会恢复默认，固件是github action自动编译的

不明角力。。。。

**Comment by Canary233** [comment]
> 描述不清。

就是在luci中更新系统后，adguard需要重新设置，之前的数据丢失。
