### ISSUE TITLE
Failed compile for nanopi-r4s

### ISSUE THREAD

**Issue by anmansky** [immortalwrt/immortalwrt#364]
[1_build (1).txt](https://github.com/immortalwrt/immortalwrt/files/6347196/1_build.1.txt)
![Screenshot_20210421-023800](https://user-images.githubusercontent.com/81860980/115477596-f06fb900-a24c-11eb-8e24-8d53b0b8a906.png)

**Comment by ricksuzade-maker** [comment]
刷新代码后，依然编译失败

**Comment by 1715173329** [comment]
日志？

**Comment by ricksuzade-maker** [comment]
make[4]: Leaving directory '/home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/rapidjson-2021-01-06-585042c0'
touch /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/rapidjson-2021-01-06-585042c0/.built
rm -rf /home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/stage-rapidjson
mkdir -p /home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/stage-rapidjson/host /home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/target-aarch64_generic_musl/packages /home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/host/packages
install -d -m0755 /home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/stage-rapidjson
cp -fpR /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/rapidjson-2021-01-06-585042c0/ipkg-install/* /home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/stage-rapidjson/
find /home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/stage-rapidjson -name '*.la' | xargs -r rm -f; 
if [ -f /home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/target-aarch64_generic_musl/packages/rapidjson.list ]; then /home/zhiliang/scripts/immortal/r4s/immortalwrt/scripts/clean-package.sh "/home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/target-aarch64_generic_musl/packages/rapidjson.list" "/home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/target-aarch64_generic_musl"; fi
if [ -d /home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/stage-rapidjson ]; then (cd /home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/stage-rapidjson; find ./ > /home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/stage-rapidjson.files); 	SHELL= flock /home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/.staging-dir.flock -c ' mv /home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/stage-rapidjson.files /home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/target-aarch64_generic_musl/packages/rapidjson.list && cp -fpR /home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/stage-rapidjson/* /home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/target-aarch64_generic_musl/; '; fi
rm -rf /home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/stage-rapidjson
touch /home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/target-aarch64_generic_musl/stamp/.rapidjson_installed
make[3]: Leaving directory '/home/zhiliang/scripts/immortal/r4s/immortalwrt/feeds/packages/libs/rapidjson'
time: package/feeds/packages/rapidjson/compile#15.51#1.69#18.44
                                                                                17839800 ->   4059012   22.75%   linux/arm64   main

Packed 1 file.
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/go-build" GO_MOD_CACHE_DIR="/home/zhiliang/scripts/immortal/r4s/immortalwrt/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" /usr/bin/env bash ../../lang/golang//golang-build.sh cache_cleanup
touch /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.built
rm -rf /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.pkgdir/xray-core.installed /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.pkgdir/xray-core
mkdir -p /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.pkgdir/xray-core
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/go-build" GO_MOD_CACHE_DIR="/home/zhiliang/scripts/immortal/r4s/immortalwrt/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/xtls/xray-core" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/xtls/xray-core/main" GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2" GO_BUILD_DIR="/home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.go_work/build" GO_BUILD_BIN_DIR="/home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.go_work/build/bin/linux_arm64" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/target-aarch64_generic_musl/usr/share/gocode/src" /usr/bin/env bash ../../lang/golang//golang-build.sh install_bin "/home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-install"
install -d -m0755 /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.pkgdir/xray-core/usr/bin/
install -m0755 /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-install/usr/bin/main /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.pkgdir/xray-core/usr/bin/xray
ln -sf xray /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.pkgdir/xray-core/usr/bin/v2ray
install -d -m0755 /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.pkgdir/xray-core/etc/xray/
install -m0600 /home/zhiliang/scripts/immortal/r4s/immortalwrt/feeds/packages/net/xray-core/files/config.json.example /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.pkgdir/xray-core/etc/xray/
install -d -m0755 /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.pkgdir/xray-core/etc/config/
install -m0600 /home/zhiliang/scripts/immortal/r4s/immortalwrt/feeds/packages/net/xray-core/files/xray.conf /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.pkgdir/xray-core/etc/config/xray
install -d -m0755 /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.pkgdir/xray-core/etc/init.d/
install -m0755 /home/zhiliang/scripts/immortal/r4s/immortalwrt/feeds/packages/net/xray-core/files/xray.init /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.pkgdir/xray-core/etc/init.d/xray
install -d -m0755 /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.pkgdir/xray-core/etc/capabilities/
install -m0644 /home/zhiliang/scripts/immortal/r4s/immortalwrt/feeds/packages/net/xray-core/files/xray.capabilities /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.pkgdir/xray-core/etc/capabilities/xray.json
touch /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.pkgdir/xray-core.installed
mkdir -p /home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp
SHELL= flock /home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/.root-copy.flock -c 'cp -fpR /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.pkgdir/xray-core/. /home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/target-aarch64_generic_musl/root-rockchip/'
touch /home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp/.xray-core_installed
removed '/home/zhiliang/scripts/immortal/r4s/immortalwrt/bin/packages/aarch64_generic/packages/xray-core_1.4.2-1_aarch64_generic.ipk'
mkdir -p /home/zhiliang/scripts/immortal/r4s/immortalwrt/bin/targets/rockchip/armv8/packages /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-aarch64_generic/xray-core/CONTROL /home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/target-aarch64_generic_musl/pkginfo
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/go-build" GO_MOD_CACHE_DIR="/home/zhiliang/scripts/immortal/r4s/immortalwrt/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/xtls/xray-core" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/xtls/xray-core/main" GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2" GO_BUILD_DIR="/home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.go_work/build" GO_BUILD_BIN_DIR="/home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.go_work/build/bin/linux_arm64" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/target-aarch64_generic_musl/usr/share/gocode/src" /usr/bin/env bash ../../lang/golang//golang-build.sh install_bin "/home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-install"
install -d -m0755 /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-aarch64_generic/xray-core/usr/bin/
install -m0755 /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-install/usr/bin/main /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-aarch64_generic/xray-core/usr/bin/xray
ln -sf xray /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-aarch64_generic/xray-core/usr/bin/v2ray
install -d -m0755 /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-aarch64_generic/xray-core/etc/xray/
install -m0600 /home/zhiliang/scripts/immortal/r4s/immortalwrt/feeds/packages/net/xray-core/files/config.json.example /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-aarch64_generic/xray-core/etc/xray/
install -d -m0755 /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-aarch64_generic/xray-core/etc/config/
install -m0600 /home/zhiliang/scripts/immortal/r4s/immortalwrt/feeds/packages/net/xray-core/files/xray.conf /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-aarch64_generic/xray-core/etc/config/xray
install -d -m0755 /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-aarch64_generic/xray-core/etc/init.d/
install -m0755 /home/zhiliang/scripts/immortal/r4s/immortalwrt/feeds/packages/net/xray-core/files/xray.init /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-aarch64_generic/xray-core/etc/init.d/xray
install -d -m0755 /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-aarch64_generic/xray-core/etc/capabilities/
install -m0644 /home/zhiliang/scripts/immortal/r4s/immortalwrt/feeds/packages/net/xray-core/files/xray.capabilities /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-aarch64_generic/xray-core/etc/capabilities/xray.json
find /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-aarch64_generic/xray-core -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
export CROSS="aarch64-openwrt-linux-musl-"  NO_RENAME=1 ; NM="aarch64-openwrt-linux-musl-nm" STRIP="aarch64-openwrt-linux-musl-strip --strip-all" STRIP_KMOD="/home/zhiliang/scripts/immortal/r4s/immortalwrt/scripts/strip-kmod.sh" PATCHELF="/home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/host/bin/patchelf" /home/zhiliang/scripts/immortal/r4s/immortalwrt/scripts/rstrip.sh /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-aarch64_generic/xray-core
rstrip.sh: /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-aarch64_generic/xray-core/usr/bin/xray: executable
patchelf: no section headers. The input file is probably a statically linked, self-decompressing binary
aarch64-openwrt-linux-musl-strip: error: the input file '/home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-aarch64_generic/xray-core/usr/bin/xray' has no sections
(cd /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-aarch64_generic/xray-core/CONTROL; ( echo "$CONTROL"; printf "Description: "; echo "$DESCRIPTION" | sed -e 's,^[[:space:]]*, ,g'; ) > control; chmod 644 control; ( echo "#!/bin/sh"; echo "[ \"\${IPKG_NO_SCRIPT}\" = \"1\" ] && exit 0"; echo "[ -s "\${IPKG_INSTROOT}/lib/functions.sh" ] || exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_postinst \$0 \$@"; ) > postinst; ( echo "#!/bin/sh"; echo "[ -s "\${IPKG_INSTROOT}/lib/functions.sh" ] || exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_prerm \$0 \$@"; ) > prerm; chmod 0755 postinst prerm; echo "$V_Package_xray_core_conffiles" > conffiles;  )
install -d -m0755 /home/zhiliang/scripts/immortal/r4s/immortalwrt/bin/packages/aarch64_generic/packages
/home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/host/bin/fakeroot /home/zhiliang/scripts/immortal/r4s/immortalwrt/scripts/ipkg-build -m "" /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-aarch64_generic/xray-core /home/zhiliang/scripts/immortal/r4s/immortalwrt/bin/packages/aarch64_generic/packages
Packaged contents of /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-aarch64_generic/xray-core into /home/zhiliang/scripts/immortal/r4s/immortalwrt/bin/packages/aarch64_generic/packages/xray-core_1.4.2-1_aarch64_generic.ipk
removed '/home/zhiliang/scripts/immortal/r4s/immortalwrt/bin/packages/aarch64_generic/packages/xray-geodata_1.4.2-1_all.ipk'
mkdir -p /home/zhiliang/scripts/immortal/r4s/immortalwrt/bin/targets/rockchip/armv8/packages /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-all/xray-geodata/CONTROL /home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/target-aarch64_generic_musl/pkginfo
install -d -m0755 /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-all/xray-geodata/usr/share/xray/
install -m0644 /home/zhiliang/scripts/immortal/r4s/immortalwrt/dl/geoip.dat.202104010913 /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-all/xray-geodata/usr/share/xray/geoip.dat
install -m0644 /home/zhiliang/scripts/immortal/r4s/immortalwrt/dl/dlc.dat.20210401091829 /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-all/xray-geodata/usr/share/xray/geosite.dat
find /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-all/xray-geodata -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
export CROSS="aarch64-openwrt-linux-musl-"  NO_RENAME=1 ; NM="aarch64-openwrt-linux-musl-nm" STRIP="aarch64-openwrt-linux-musl-strip --strip-all" STRIP_KMOD="/home/zhiliang/scripts/immortal/r4s/immortalwrt/scripts/strip-kmod.sh" PATCHELF="/home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/host/bin/patchelf" /home/zhiliang/scripts/immortal/r4s/immortalwrt/scripts/rstrip.sh /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-all/xray-geodata
(cd /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-all/xray-geodata/CONTROL; ( echo "$CONTROL"; printf "Description: "; echo "$DESCRIPTION" | sed -e 's,^[[:space:]]*, ,g'; ) > control; chmod 644 control; ( echo "#!/bin/sh"; echo "[ \"\${IPKG_NO_SCRIPT}\" = \"1\" ] && exit 0"; echo "[ -s "\${IPKG_INSTROOT}/lib/functions.sh" ] || exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_postinst \$0 \$@"; ) > postinst; ( echo "#!/bin/sh"; echo "[ -s "\${IPKG_INSTROOT}/lib/functions.sh" ] || exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_prerm \$0 \$@"; ) > prerm; chmod 0755 postinst prerm;  )
install -d -m0755 /home/zhiliang/scripts/immortal/r4s/immortalwrt/bin/packages/aarch64_generic/packages
/home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/host/bin/fakeroot /home/zhiliang/scripts/immortal/r4s/immortalwrt/scripts/ipkg-build -m "" /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-all/xray-geodata /home/zhiliang/scripts/immortal/r4s/immortalwrt/bin/packages/aarch64_generic/packages
Packaged contents of /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/ipkg-all/xray-geodata into /home/zhiliang/scripts/immortal/r4s/immortalwrt/bin/packages/aarch64_generic/packages/xray-geodata_1.4.2-1_all.ipk
echo "xray-core" >> /home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/target-aarch64_generic_musl/pkginfo/xray-core.default.install
rm -rf /home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/stage-xray-core
mkdir -p /home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/stage-xray-core/host /home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/target-aarch64_generic_musl/packages /home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/host/packages
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/go-build" GO_MOD_CACHE_DIR="/home/zhiliang/scripts/immortal/r4s/immortalwrt/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/xtls/xray-core" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/xtls/xray-core/main" GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2" GO_BUILD_DIR="/home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.go_work/build" GO_BUILD_BIN_DIR="/home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.go_work/build/bin/linux_arm64" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/target-aarch64_generic_musl/usr/share/gocode/src" /usr/bin/env bash ../../lang/golang//golang-build.sh install_src "/home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/stage-xray-core"
find /home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/stage-xray-core -name '*.la' | xargs -r rm -f; 
if [ -f /home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/target-aarch64_generic_musl/packages/xray-core.list ]; then /home/zhiliang/scripts/immortal/r4s/immortalwrt/scripts/clean-package.sh "/home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/target-aarch64_generic_musl/packages/xray-core.list" "/home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/target-aarch64_generic_musl"; fi
if [ -d /home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/stage-xray-core ]; then (cd /home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/stage-xray-core; find ./ > /home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/stage-xray-core.files); 	SHELL= flock /home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/.staging-dir.flock -c ' mv /home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/stage-xray-core.files /home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/target-aarch64_generic_musl/packages/xray-core.list && cp -fpR /home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/stage-xray-core/* /home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/target-aarch64_generic_musl/; '; fi
rm -rf /home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/stage-xray-core
touch /home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/target-aarch64_generic_musl/stamp/.xray-core_installed
rm -rf /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.pkgdir/xray-geodata.installed /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.pkgdir/xray-geodata
mkdir -p /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.pkgdir/xray-geodata
install -d -m0755 /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.pkgdir/xray-geodata/usr/share/xray/
install -m0644 /home/zhiliang/scripts/immortal/r4s/immortalwrt/dl/geoip.dat.202104010913 /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.pkgdir/xray-geodata/usr/share/xray/geoip.dat
install -m0644 /home/zhiliang/scripts/immortal/r4s/immortalwrt/dl/dlc.dat.20210401091829 /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.pkgdir/xray-geodata/usr/share/xray/geosite.dat
touch /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.pkgdir/xray-geodata.installed
mkdir -p /home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp
SHELL= flock /home/zhiliang/scripts/immortal/r4s/immortalwrt/tmp/.root-copy.flock -c 'cp -fpR /home/zhiliang/scripts/immortal/r4s/immortalwrt/build_dir/target-aarch64_generic_musl/Xray-core-1.4.2/.pkgdir/xray-geodata/. /home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/target-aarch64_generic_musl/root-rockchip/'
touch /home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp/.xray-geodata_installed
echo "xray-geodata" >> /home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/target-aarch64_generic_musl/pkginfo/xray-core.default.install
make[3]: Leaving directory '/home/zhiliang/scripts/immortal/r4s/immortalwrt/feeds/packages/net/xray-core'
time: package/feeds/packages/xray-core/compile#37.00#4.56#41.35
make[2]: Leaving directory '/home/zhiliang/scripts/immortal/r4s/immortalwrt'
make[1]: *** [package/Makefile:108: /home/zhiliang/scripts/immortal/r4s/immortalwrt/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/zhiliang/scripts/immortal/r4s/immortalwrt'
make: *** [/home/zhiliang/scripts/immortal/r4s/immortalwrt/include/toplevel.mk:230：world] 错误 2

**Comment by 1715173329** [comment]
在你给的日志中，我找不到任何有价值的内容

**Comment by noreph** [comment]
我也编译出错了，日志：https://paste.ubuntu.com/p/HPSk6b6PYQ/

**Comment by 1715173329** [comment]
看来是一些函数名发生了变动

**Comment by 1715173329** [comment]
已修复。

**Comment by ricksuzade-maker** [comment]
完美通过编译，给天灵大佬点个大赞！
