### ISSUE TITLE
编译pass wall提示缺少依赖，

### ISSUE THREAD

**Issue by stonegr** [immortalwrt/immortalwrt#367]
使用github云编译，将passwallclone到packages目录下，在下载时提示这个
![image](https://user-images.githubusercontent.com/74632994/115513005-2ba5d280-a2b5-11eb-8e75-bb1459db2d0a.png)
后面passwall也会编译失败，不知道什么原因，电脑上又是正常的

**Comment by BabXhwZUNBeTV** [comment]
@stonegr passwall 源码自带 你想自己折腾的话 请看 openwrt.org 官方 wiki https://openwrt.org/docs/guide-developer/helloworld/chapter4
