### ISSUE TITLE
请教大神云编译的时候openwrt-18.06 make menuconfig时候出现的这个能解决吗

### ISSUE THREAD

**Issue by ly20202020** [immortalwrt/immortalwrt#394]
openwrt-18.06 make menuconfig时候出现的，21.02没这个，用本地的看了下，好像18.06的也不会出现这个，能解决不？
![QQ截图20210531104358](https://user-images.githubusercontent.com/81305396/120132888-b60b1b80-c1fd-11eb-921e-c9c6dd62870e.png)

**Comment by 1715173329** [comment]
问题不大，可以先忽略

**Comment by ly20202020** [comment]
感谢大神回复，谢谢！
