### ISSUE TITLE
Not Foundbin file

### ISSUE THREAD

**Issue by midorima5791** [immortalwrt/immortalwrt#398]
![image](https://user-images.githubusercontent.com/55052591/121006589-a07c8f80-c7c3-11eb-89f5-c6ce1b4e16e6.png)
 where's the bin file after finished build I can't find the bin file ?

**Comment by 1715173329** [comment]
I can only assume that you selected too many packages so OpenWrt cannot generate a image within the flash size.

**Comment by midorima5791** [comment]
> I can only assume that you selected too many packages so OpenWrt cannot generate a image within the flash size.

im using newifi D2 router so it means limited package can I install?

**Comment by 1715173329** [comment]
> im using newifi D2 router so it means limited package can I install?

Yes, try to deselect some packages, and build again.

**Comment by midorima5791** [comment]
> > im using newifi D2 router so it means limited package can I install?
> 
> Yes, try to deselect some packages, and build again.

ok thanks for the tips
