### ISSUE TITLE
21.02 的识别不了USB了，是上游调整了么？

### ISSUE THREAD

**Issue by asiaon123** [immortalwrt/immortalwrt#402]

**Comment by AmadeusGhost** [comment]
建议先去看看提问的智慧…

**Comment by asiaon123** [comment]
Sorry，可能不能很好的描述，但是我是按照之前一样的选的，但是现在usb插上去就识别不了了😂

**Comment by asiaon123** [comment]
我的是，hc5962

**Comment by zhihuiyuze** [comment]
请检查是否有对应的kmod，参考https://www.haiyun.me/archives/openwrt-usb-mount-disk.html
