### ISSUE TITLE
18.06 x86 不能启动

### ISSUE THREAD

**Issue by noreph** [immortalwrt/immortalwrt#408]
在物理机和虚拟机上均有复现，开机到 grub loading 就重启了

![](https://i.loli.net/2021/06/16/tmBn9cWjE8MKl47.jpg)

**Comment by 1715173329** [comment]
Same issue can be found here (based on immortalwrt x86 source):
coolsnowwolf/lede#6977
coolsnowwolf/lede#6979

**Comment by 1715173329** [comment]
Please try with this commit: c01acf6c4d01efba2000ca7fe4627eec763a63cc
If you're at openwrt-18.06-k5.4 branch, run the following command:
```bash
curl -fsSL https://github.com/immortalwrt/immortalwrt/commit/c01acf6c4d01efba2000ca7fe4627eec763a63cc.patch | git apply
```

**Comment by 1715173329** [comment]
Please try with latest git HEAD.

**Comment by noreph** [comment]
最新代码编译的在虚拟测试已经正常开机了

**Comment by 1715173329** [comment]
However sysupgrade function is broken...
I have no idea how to address it.

**Comment by 1715173329** [comment]
> However sysupgrade function is broken...
> I have no idea how to address it.

I saw the same issue with master branch... Does anyone have any idea?

**Comment by 1715173329** [comment]
However it boots, so I guess I can close this issue now.
