### ISSUE TITLE
新路由3编译21.02，没有交换机插件，而且cpu使用率较高

### ISSUE THREAD

**Issue by Thanf-code** [immortalwrt/immortalwrt#416]
![image](https://user-images.githubusercontent.com/82493550/124123941-6d6baa00-daaa-11eb-8819-fa329e151fbf.png)
![R)P9IK O8B5_9A~A5J)KJHV](https://user-images.githubusercontent.com/82493550/124123955-72c8f480-daaa-11eb-8f39-4dfe9865b4f8.png)

**Comment by 1715173329** [comment]
- Use Google to find what is called DSA.
- Use luci-app-turboacc to enable hardware offloading.

**Comment by Thanf-code** [comment]
> * Use Google to find what DSA is.
> * Use luci-app-turboacc to enable hardware offloading.

Directory System Agent？ 
我想用应用过滤，但应用过滤与加速模块冲突

**Comment by Gzxhwq** [comment]
https://forum.openwrt.org/t/mini-tutorial-for-dsa-network-config/96998

**Comment by 1715173329** [comment]
> Directory System Agent？

https://www.kernel.org/doc/Documentation/networking/dsa/dsa.txt

> 我想用应用过滤，但应用过滤与加速模块冲突

So it's up to you, appfilter or offloading.

**Comment by Thanf-code** [comment]
> > Directory System Agent？
> 
> https://www.kernel.org/doc/Documentation/networking/dsa/dsa.txt
> 
> > 我想用应用过滤，但应用过滤与加速模块冲突
> 
> So it's up to you, appfilter or offloading.

1.可不可以在ssh界面重新选上交换机插件，该如何操作？
2.lede源码不用加速模块，cpu使用率也还可以，可以借鉴一下？

**Comment by 1715173329** [comment]
Use 18.06 branch.
