### ISSUE TITLE
IPv6可以获取但是无法通过ipv

### ISSUE THREAD

**Issue by kingteng** [immortalwrt/immortalwrt#417]

**Comment by zhihuiyuze** [comment]
在OPENWRT和本地电脑上使用`ip -6 route `获取路由并查看是否正确。
您是电信通过WAN PPPoe接口追踪获取的吗？如果是的，请检查接口是否创建。并把位于LAN的DHCPv6服务器调整为
路由通过服务 服务器模式
DHCPv6 中续模式
NDP代理 已禁用
