### ISSUE TITLE
请教一个小白问题 openclash在哪个目录里啊

### ISSUE THREAD

**Issue by zhangj3** [immortalwrt/immortalwrt#418]
大佬好！
我知道immortalwrt里集成了openclash，是在哪个目录里啊 我想看下源码有没有跟作者的github同步 https://github.com/vernesong/OpenClash/tree/master

谢谢

**Comment by zhangj3** [comment]
immortalwrt/package/里点了一些文件夹 没找到，所以只能问问大佬了

**Comment by AmadeusGhost** [comment]
在 feeds/luci 下：https://github.com/immortalwrt/luci

**Comment by zhangj3** [comment]
> 在 feeds/luci 下：https://github.com/immortalwrt/luci

谢谢大佬，原来不在一个地方。

是没有同步，有什么办法可以手动同步吗？
最近openclash总是出现“{"message":"Resource not found"}”问题 https://github.com/vernesong/OpenClash/issues/1439 ，启动慢，作者好像修复了

![image](https://user-images.githubusercontent.com/49198958/124431600-21b74a00-dda3-11eb-8b45-4867c5d42337.png)

![image](https://user-images.githubusercontent.com/49198958/124431655-3398ed00-dda3-11eb-9ce8-fa4ca3094894.png)

我有什么办法手动同步吗？
