### ISSUE TITLE
luci界面升级上传.gz格式固件提示不支持的格式，之前的版本没出现过

### ISSUE THREAD

**Issue by xuanwumen** [immortalwrt/immortalwrt#422]
X86系统中上传immortalwrt-x86-64-generic-squashfs-combined-efi.img.gz从之前的固件升级新编的出现这种情况,目前分支都试过同样问题
![屏幕截图 2021-07-23 022114](https://user-images.githubusercontent.com/45932714/126689640-fc68a9b3-0647-47dd-84a3-fac5453631a1.png)

**Comment by ElonH** [comment]
fixed in c7251e55940d774ca81a355bb7246574a0177b1c
