### ISSUE TITLE
nanopi r2s: 使用 master 分支源码编译的固件无法启动

### ISSUE THREAD

**Issue by EdiTurn** [immortalwrt/immortalwrt#428]
基于 03c5732，在尝试 distclean 后结果也是一样。

**Comment by love4taylor** [comment]
啊这，昨天用 master 编译的 r4s 也是起不来。

**Comment by kiddin9** [comment]
同样的问题.

**Comment by 1715173329** [comment]
![image](https://user-images.githubusercontent.com/22235437/128859477-630d5b3b-a842-43d4-9a08-f9a8b06c6b78.png)

**Comment by kiddin9** [comment]
编译没有错误,
刷入后无法开机,电源指示灯都不亮,网口灯有闪,风扇有转动.

**Comment by 1715173329** [comment]
Don't you know what is TTL console?

**Comment by kiddin9** [comment]
不好意思,没用过,不会操作.

**Comment by klever1988** [comment]
电源灯能亮个几秒 然后就全灭了 18.05-k5.4 branch

**Comment by EdiTurn** [comment]
已确认上游也有问题

**Comment by AmadeusGhost** [comment]
May be fixed in https://github.com/openwrt/openwrt/commit/29a3967e61334d0c6a1a7d391f0e751272d77b1d , and it seems that someone said that r1s also failed to bootup.

**Comment by 1715173329** [comment]
Fixed in 4262a83d1d0316f45fdcc66595b8fc37fbf875db.

**Comment by 1715173329** [comment]
Fixed in 751967e121738723182408c7c22ad003234ccf69.
