### ISSUE TITLE
18.06多次测试只要安装了passwall，在关于防火墙方面的保存都会转圈圈，卸载passwall就没问题，如下图

### ISSUE THREAD

**Issue by xuanwumen** [immortalwrt/immortalwrt#440]
![image](https://user-images.githubusercontent.com/45932714/130730374-5276a2e6-75fe-4f81-80cd-91dc2e8984e3.png)

**Comment by xuanwumen** [comment]
补充说明是一直转圈圈

**Comment by 1715173329** [comment]
你防火墙卡死了，fw3 reload 即可。
另外，不用 passwall 即可解决问题。
