### ISSUE TITLE
内核升级

### ISSUE THREAD

**Issue by zhq1** [immortalwrt/immortalwrt#450]
大佬请教下怎么升级内核到5.10呢，我现在查看好像内核/immortalwrt/include/kernel-version.mk文件里面显示3个
LINUX_VERSION-4.9 = .280
LINUX_VERSION-4.14 = .244
LINUX_VERSION-4.19 = .204
编译默认只有4.14

**Comment by jh0072110** [comment]
换k5.4或master分支

**Comment by zhq1** [comment]
@jh0072110 谢谢，我说咋回事，没注意看默认是18.06
