### ISSUE TITLE
能否添加对rtl8192eu的支持

### ISSUE THREAD

**Issue by bosense** [immortalwrt/immortalwrt#456]
谢谢

**Comment by 1715173329** [comment]
no pain, no gain
no device, no agenda

**Comment by AmadeusGhost** [comment]
能，您可以选择赞助我们。

**Comment by bosense** [comment]
如何赞助

**Comment by 1715173329** [comment]
请通过 https://afdian.net/order/create?user_id=5c815aa683f711ea8a5052540025c377 发起赞助并备注 rtl8192eu
至少足够购买一个常规 rtl8192eu USB 网卡

**Comment by 1715173329** [comment]
会在近期支持。

**Comment by bosense** [comment]
已有19.07的源码资源，缺少21版本的，linux驱动参照https://github.com/Mange/rtl8192eu-linux-driver

**Comment by AmadeusGhost** [comment]
试试这个：https://github.com/AmadeusGhost/lede/commit/88ee043d1065846221b40b5533648ffeef702904 ，没问题我再 push 上来。

**Comment by bosense** [comment]
可以使用，万分感谢！
