### ISSUE TITLE
最新源码CPU Usage多了一个%

### ISSUE THREAD

**Issue by huanghuangge** [immortalwrt/immortalwrt#458]
![0](https://user-images.githubusercontent.com/37528193/132851751-9fb7c91e-571c-446f-ab61-c606359c99eb.png)
如上图

**Comment by zxlhhyccc** [comment]
同样。。。。

**Comment by Boos4721** [comment]
pick it https://github.com/Boos4721/openwrt/commit/0cc81f93d0f3f0639958f9128278bfabb70b925e
