### ISSUE TITLE
何如让外网访问内网的445端口

### ISSUE THREAD

**Issue by edwardfhsiao** [immortalwrt/immortalwrt#460]
设置了端口转发如图:

![image](https://user-images.githubusercontent.com/11728228/133103049-e7ef0325-0102-4916-bc6b-a773ae61d62e.png)

mydomain是ddns设置的域名
外网访问 mydomain.com:8081是成功的
外网访问 mydomain.com:4455是失败的
在局域网内部445(192.168.50.1:445)是可以连的

```
// 8081

telnet mydomain.com 8081

Trying 1xx.xxx.xxx.xxx...
Connected to mydomain.com.
Escape character is '^]'.
```

```
// 445

telnet mydomain.com 4455

Trying 1xx.xxx.xxx.xxx...
telnet: connect to address 1xx.xxx.xxx.xxx: Connection refused
telnet: Unable to connect to remote host
```

**Comment by 1715173329** [comment]
![IMG_20200918_234643_149](https://user-images.githubusercontent.com/22235437/133113334-22ed56a2-b923-407e-9327-8d3b9a280755.jpg)
 issue != forum

**Comment by edwardfhsiao** [comment]
yes sir

**Comment by edwardfhsiao** [comment]
For anyone who may have the same problem, my solution after 2 days of researching is to switch to the vanilla OpenWrt with the vanilla Samba.  And it works great.
