### ISSUE TITLE
ksmbd and ksmbd-tools?

### ISSUE THREAD

**Issue by Neustradamus** [immortalwrt/immortalwrt#461]
Hello the team,

Where are:
- ksmbd
- ksmbd-tools

It is important pour CIFS/SMBv1/SMBv2/SMBv3.

Thanks in advance.

**Comment by 1715173329** [comment]
https://github.com/immortalwrt/packages/tree/master/kernel/ksmbd
https://github.com/immortalwrt/packages/tree/master/net/ksmbd-tools

**Comment by Neustradamus** [comment]
Sorry for the noise, I do not found my ticket...

You can removed the second one.
