### ISSUE TITLE
[21.02] 编译ssr+ xray没有生成sysupgrade，只有initramfs

### ISSUE THREAD

**Issue by sooxt98** [immortalwrt/immortalwrt#468]

**Comment by 1715173329** [comment]
你选的插件太多了，导致固件总大小超过了 flash 容量，无法生成 sysupgrade 文件。

**Comment by sooxt98** [comment]
@1715173329 应该不会吧initramfs-kernel只有14.9MB，我只是加SSR+而已，没其他的了，有方法解决么？

![image](https://user-images.githubusercontent.com/13378059/133917043-15a3867c-2734-43cd-b9a0-976fe13b5084.png)




![image](https://user-images.githubusercontent.com/13378059/133917054-63638d97-6193-42a7-8b12-4c63d910cf47.png)
