### ISSUE TITLE
built  wrong  in X86-64   branch:Master

### ISSUE THREAD

**Issue by imy7** [immortalwrt/immortalwrt#481]
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

cd -P . && \
type aclocal >/dev/null 2>&1 && exec aclocal; \
touch aclocal.m4
cd -P . && exec autoconf -o configure
./tool/file2lastrev.rb:6:in `require': cannot load such file -- optparse (LoadError)
	from ./tool/file2lastrev.rb:6:in `<main>'
make[4]: *** [uncommon.mk:1156: revision.tmp] Error 1
make[4]: Leaving directory '/home/imy7/Desktop/imwrt/build_dir/hostpkg/ruby-3.0.2'
make[3]: *** [Makefile:1134: /home/imy7/Desktop/imwrt/build_dir/hostpkg/ruby-3.0.2/.built] Error 2
make[3]: Leaving directory '/home/imy7/Desktop/imwrt/feeds/packages/lang/ruby'
time: package/feeds/packages/ruby/host-compile#2.14#0.14#3.06
    ERROR: package/feeds/packages/ruby [host] failed to build.
make[2]: *** [package/Makefile:114: package/feeds/packages/ruby/host/compile] Error 1
make[2]: Leaving directory '/home/imy7/Desktop/imwrt'
make[1]: *** [package/Makefile:110: /home/imy7/Desktop/imwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/imy7/Desktop/imwrt'
make: *** [/home/imy7/Desktop/imwrt/include/toplevel.mk:230: world] Error 2

**Comment by 1715173329** [comment]
https://github.com/immortalwrt/OpenWrt-Compilation-Checker/runs/3837980422?check_suite_focus=true#step:6:106
CI was passing, check your build env.
