### ISSUE TITLE
[18.06]-Newifi-D2 MTK7621 编译后不显示无线wifi-openwrt，且无法进去路由界面

### ISSUE THREAD

**Issue by lgfyxx1** [immortalwrt/immortalwrt#501]
如标题，多次尝试编译后的完整固件均是相同问题， 应该是固件问题。

1. 编译后不显示无线wifi-openwrt，
2. 直接连网线的情况下也无法进去路由界面： 192.168.1.1

刷回9月份编译的老固件一切正常。

感谢大佬！

**Comment by AmadeusGhost** [comment]
你不接个 ttl 我们怎么知道是什么情况🌚

**Comment by lgfyxx1** [comment]
不知道。。。。ttl 是啥

**Comment by Thanf-code** [comment]
自9月中旬源码更新以来，新路由三的cpu使用率就比较高，一直在28%以上，不知道为啥？

**Comment by lgfyxx1** [comment]
> 自9月中旬源码更新以来，新路由三的cpu使用率就比较高，一直在28%以上，不知道为啥？

你有编译最新的固件吗? 想问下能不能进去路由器管理界面呢？谢谢

**Comment by Thanf-code** [comment]
> > 自9月中旬源码更新以来，新路由三的cpu使用率就比较高，一直在28%以上，不知道为啥？
> 
> 你有编译最新的固件吗? 想问下能不能进去路由器管理界面呢？谢谢

有，但是cpu占用较高问题未解决

**Comment by 1715173329** [comment]
Well, can you guys send me a sample firmware that you compiled?

**Comment by Thanf-code** [comment]
> Well, can you guys send me a sample firmware that you compiled? Also with `.config`.

I compiled it using the 21.02 branch

**Comment by Thanf-code** [comment]
> > 自9月中旬源码更新以来，新路由三的cpu使用率就比较高，一直在28%以上，不知道为啥？
> 
> 你有编译最新的固件吗? 想问下能不能进去路由器管理界面呢？谢谢

我用master分支编译出来还算比较正常看你需不需要

**Comment by lgfyxx1** [comment]
[immortalwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.zip](https://github.com/immortalwrt/immortalwrt/files/7492400/immortalwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.zip)
IP能进去了，无线还是有问题，好几个终端连不上，显示
“MediaTek MT76x2E 802.11nac (radio1)
信道: 36 (5.180 GHz) | 传输速率: ？ Mbit/s  
WIFI 0% ”

**Comment by zxlhhyccc** [comment]
> [immortalwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.zip](https://github.com/immortalwrt/immortalwrt/files/7492400/immortalwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.zip) IP能进去了，无线还是有问题，好几个终端连不上，显示 “MediaTek MT76x2E 802.11nac (radio1) 信道: 36 (5.180 GHz) | 传输速率: ？ Mbit/s WIFI 0% ”

你是哪个分支编译的？如果是master分支编译的，一定是hostpad更新后造成的。。。
解决办法：
1、回退hostpad；
2、对mac80211.sh添加一行代码：
set wireless.default_radio${devidx}.iw_qos_map_set=none

**Comment by lgfyxx1** [comment]
> > [immortalwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.zip](https://github.com/immortalwrt/immortalwrt/files/7492400/immortalwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.zip) IP能进去了，无线还是有问题，好几个终端连不上，显示 “MediaTek MT76x2E 802.11nac (radio1) 信道: 36 (5.180 GHz) | 传输速率: ？ Mbit/s WIFI 0% ”
> 
> 你是哪个分支编译的？如果是master分支编译的，一定是hostpad更新后造成的。。。 解决办法： 1、回退hostpad； 2、对mac80211.sh添加一行代码： set wireless.default_radio${devidx}.iw_qos_map_set=none

18.06 master

**Comment by lgfyxx1** [comment]
> > [immortalwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.zip](https://github.com/immortalwrt/immortalwrt/files/7492400/immortalwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.zip) IP能进去了，无线还是有问题，好几个终端连不上，显示 “MediaTek MT76x2E 802.11nac (radio1) 信道: 36 (5.180 GHz) | 传输速率: ？ Mbit/s WIFI 0% ”
> 
> 你是哪个分支编译的？如果是master分支编译的，一定是hostpad更新后造成的。。。 解决办法： 1、回退hostpad； 2、对mac80211.sh添加一行代码： set wireless.default_radio${devidx}.iw_qos_map_set=none

非常感谢，我试试

**Comment by lgfyxx1** [comment]
搜到好多，想问下每一个都需要改吗？ 谢谢

![1636332703(1)](https://user-images.githubusercontent.com/68235325/140668972-94bb0cd7-f8cd-4e8b-a813-d1b22ffc863a.png)

**Comment by Thanf-code** [comment]
> [immortalwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.zip](https://github.com/immortalwrt/immortalwrt/files/7492400/immortalwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.zip) IP能进去了，无线还是有问题，好几个终端连不上，显示 “MediaTek MT76x2E 802.11nac (radio1) 信道: 36 (5.180 GHz) | 传输速率: ？ Mbit/s WIFI 0% ”

这是5G信号 要设备支持5G才能连上

**Comment by zxlhhyccc** [comment]
> 搜到好多，想问下每一个都需要改吗？ 谢谢
> 
> ![1636332703(1)](https://user-images.githubusercontent.com/68235325/140668972-94bb0cd7-f8cd-4e8b-a813-d1b22ffc863a.png)

机器上改的话：修改/etc/config/wireless，在2.4G和5G下面添加：option iw_qos_map_set 'none'试试。
比如：
![image](https://user-images.githubusercontent.com/45259624/140692043-bc85daf5-b394-43bd-aaea-d74ac2559fc4.png)

**Comment by AmadeusGhost** [comment]
![d2](https://user-images.githubusercontent.com/42570690/143888215-5c323d92-469e-46db-b415-5a327e01622c.png)
之前我也遇到了 18.06 新三无法启动的问题，`make dirclean` 之后实测能正常启动。
