### ISSUE TITLE
K5.4 Overview issue

### ISSUE THREAD

**Issue by jh0072110** [immortalwrt/immortalwrt#502]
![image](https://user-images.githubusercontent.com/50496854/139788294-94858128-fdc7-4879-a79e-9c23f6403e6d.png)
Just like this screenshot, overview can't show right model of this router (I just test x86-64)

**Comment by 1715173329** [comment]
So it's your own issue, your BIOS doesn't provide a valid model name.

**Comment by jh0072110** [comment]
> So it's your own issue, your BIOS doesn't provide a valid model name.

Thx
