### ISSUE TITLE
R4S使用immortalwrt+openclash出现降速问题

### ISSUE THREAD

**Issue by wtoxin** [immortalwrt/immortalwrt#516]
R4S 使用 ImmortalWrt 18.06-SNAPSHOT r10525-4af9b12df 固件开启 openclash 一段时间后会出现降速，500Mbps能降到100Mbps左右，关闭openclash或者重启系统（开启openclash）后恢复正常

**Comment by AmadeusGhost** [comment]
I don't think this should be an issue :)
