### ISSUE TITLE
pc浏览器进不去luci界面，手机浏览器可以进

### ISSUE THREAD

**Issue by 13528943945** [immortalwrt/immortalwrt#523]
最近多次用master分支编译，完成后出现pc浏览器进不去luci界面，手机浏览器进luci界面一切正常

**Comment by nicholas-opensource** [comment]
尝试使用隐身模式或者换一个PC浏览器进入，js导致的缓存

**Comment by 13528943945** [comment]
> 尝试使用隐身模式或者换一个PC浏览器进入，js导致的缓存

不是缓存的原因，试了谷歌和火狐，而且先清缓存再打开，依然进不了luci界面，只出现luci-lua configuration interface字样
