### ISSUE TITLE
[19.08] u-boot patch 文件修复

### ISSUE THREAD

**Issue by imoldchen** [immortalwrt/immortalwrt#534]
编译时执行 patch 报错，修复如下：
patch 文件位置
tools/mkimage/patches/090-macos-arm64-builing-fix.patch

`diff --git a/Makefile b/Makefile
index b4f1cbc..551041f 100644
--- a/Makefile
+++ b/Makefile
@@ -324,11 +324,6 @@ HOSTCC       = $(call os_x_before, 10, 5, "cc", "gcc")
 HOSTCFLAGS  += $(call os_x_before, 10, 4, "-traditional-cpp")
 HOSTLDFLAGS += $(call os_x_before, 10, 5, "-multiply_defined suppress")
 
-# since Lion (10.7) ASLR is on by default, but we use linker generated lists
-# in some host tools which is a problem then ... so disable ASLR for these
-# tools
-HOSTLDFLAGS += $(call os_x_before, 10, 7, "", "-Xlinker -no_pie")
-
 # macOS Mojave (10.14.X) 
 # Undefined symbols for architecture x86_64: "_PyArg_ParseTuple"
 HOSTLDFLAGS += $(call os_x_after, 10, 14, "-lpython -dynamclib", "")
`

**Comment by AmadeusGhost** [comment]
19.08 是什么鬼？
