### ISSUE TITLE
[18.06-k5.4] rt4230w kernel patch出错，附

### ISSUE THREAD

**Issue by zheshifandian** [immortalwrt/immortalwrt#546]
出错文件
immortalwrt/target/linux/ipq806x/patches-5.4/0065-arm-override-compiler-flags.patch
须更改为
arch-$(CONFIG_CPU_32v7M)	=-D__LINUX_ARM_ARCH__=7 -march=armv7-m
-arch-$(CONFIG_CPU_32v7)		=-D__LINUX_ARM_ARCH__=7 -march=armv7-a
+arch-$(CONFIG_CPU_32v7)		=-D__LINUX_ARM_ARCH__=7 -mcpu=cortex-a15
 arch-$(CONFIG_CPU_32v6)		=-D__LINUX_ARM_ARCH__=6 -march=armv6

**Comment by 1715173329** [comment]
Thanks for reporting the issue. Do you have a PR for it?

**Comment by zheshifandian** [comment]
> Thanks for reporting the issue. Do you have a PR for it?

PR了

**Comment by 1715173329** [comment]
#547
