### ISSUE TITLE
opkg貌似有问题

### ISSUE THREAD

**Issue by bonnyandsky** [immortalwrt/immortalwrt#567]
master版本：ImmortalWrt SNAPSHOT r21315-88bbb16ca6 / LuCI Master git-22.012.10926-288e6e5

opkg update后提示
root@ImmortalWrt:~# opkg update
Collected errors:
 * opkg_conf_load: Could not lock /var/lock/opkg.lock: Resource temporarily unavailable.

上网看了下 要这样修复才可以
echo "nameserver 119.29.29.29">/tmp/resolv.conf
rm -f /var/lock/opkg.lock

**Comment by AmadeusGhost** [comment]
/var/lock/... 算了，你自己理解
