### ISSUE TITLE
[21.02]rtl88x2bu驱动似乎更换了仓库位置

### ISSUE THREAD

**Issue by Achang233** [immortalwrt/immortalwrt#606]
rtl88x2bu驱动似乎更换了仓库位置 由`https://github.com/morrownr/88x2bu` 更改为了 `https://github.com/morrownr/88x2bu-20210702`

ImmortalWrt需要对这个更改做出反应吗

**Comment by lxl6125** [comment]
仓库位置不是重点，重点是
PKG_SOURCE_VERSION:=47a666315d0a5ff37b53adb48ca21404787565cf

https://github.com/morrownr/88x2bu/tree/47a666315d0a5ff37b53adb48ca21404787565cf

**Comment by AmadeusGhost** [comment]
不需要，能正常编译和使用就行。
