### ISSUE TITLE
我表示很无语，进你们TG群，回答被拒五次，还不让我发言了？还要关闭我留言？

### ISSUE THREAD

**Issue by Assassincc** [immortalwrt/immortalwrt#616]
刷了你们固件 现在本地访问很卡，上来问个问题，进不去群里，回答全是错的，google搜索的都不对。不知道你们想搞什么。

**Comment by MarksonHon** [comment]
@Assassincc issue区是用来提交软件本身的问题的，而不是你所谓的“留言”。

**Comment by Assassincc** [comment]
我现在没办法进群，我能怎么办哪？？我现在刷了这个固件我本地访问特别卡，外网倒是不错了，就是本地卡爆了 百度都打不开，我没开全局，开的绕过大陆IP，结果还是卡爆。

**Comment by MarksonHon** [comment]
@Assassincc 既然这样 那你把你的网络拓扑图与所用的网络设备型号发一下吧 看下有没有好心人拉你一把
