### ISSUE TITLE
Orangepi One Plus  coremark跑分

### ISSUE THREAD

**Issue by ZZMHA227** [immortalwrt/immortalwrt#622]
前段时间捡了个Orangepi one plus的板子，H6芯片。用K5.4编译后跑了一下分，1.2W。这和H5的跑分差不多呀。应该不至于那么低，应该比RK3328高才对，求大佬看看哪里出了问题。

![屏幕截图 2022-03-11 213826](https://user-images.githubusercontent.com/57690855/157883172-4c724e6f-03a9-4320-80f2-01941ea5b463.png)

**Comment by AmadeusGhost** [comment]
你 cpu 主频拉到 1.8G 了嘛？

**Comment by ZZMHA227** [comment]
> 默认频率跑的，CPU频率调节没适配这款机器。
![屏幕截图 2022-03-11 223223](https://user-images.githubusercontent.com/57690855/157887524-ddfc6eff-1147-48bd-95db-ab296a94fdcc.png)

**Comment by ZZMHA227** [comment]
@AmadeusGhost 佬，H6用的是H5的频率设置，能fix吗？
![2F424A4F-5F24-48DE-8F1A-A2BA03362F7C](https://user-images.githubusercontent.com/57690855/158063985-2c5b9907-7e23-4fbe-a392-997f337fdb7c.jpeg)
![7F7AC008-C4F3-42C0-AF3D-66D5BC227D0E](https://user-images.githubusercontent.com/57690855/158063986-2a5395cd-00aa-4eba-9c08-940f8696cf72.jpeg)

**Comment by AmadeusGhost** [comment]
```
diff --git a/target/linux/sunxi/patches-5.4/102-arm64-dts-allwinner-h6-Enable-CPU-opp-tables-for-orangepi.patch b/target/linux/sunxi/patches-5.4/102-arm64-dts-allwinner-h6-Enable-CPU-opp-tables-for-orangepi.patch
new file mode 100644
index 000000000..2e4f3ea4e
--- /dev/null
+++ b/target/linux/sunxi/patches-5.4/102-arm64-dts-allwinner-h6-Enable-CPU-opp-tables-for-orangepi.patch
@@ -0,0 +1,38 @@
+--- a/arch/arm64/boot/dts/allwinner/sun50i-h6-orangepi.dtsi
++++ b/arch/arm64/boot/dts/allwinner/sun50i-h6-orangepi.dtsi
+@@ -7,6 +7,7 @@
+ /dts-v1/;
+ 
+ #include "sun50i-h6.dtsi"
++#include "sun50i-h6-cpu-opp.dtsi"
+ 
+ #include <dt-bindings/gpio/gpio.h>
+ 
+@@ -47,6 +48,10 @@
+ 	};
+ };
+ 
++&cpu0 {
++	cpu-supply = <&reg_dcdca>;
++};
++
+ &ehci0 {
+ 	status = "okay";
+ };
+@@ -158,13 +163,15 @@
+ 			reg_dcdca: dcdca {
+ 				regulator-always-on;
+ 				regulator-min-microvolt = <810000>;
+-				regulator-max-microvolt = <1080000>;
++				regulator-max-microvolt = <1160000>;
++				regulator-ramp-delay = <2500>;
+ 				regulator-name = "vdd-cpu";
+ 			};
+ 
+ 			reg_dcdcc: dcdcc {
+ 				regulator-min-microvolt = <810000>;
+ 				regulator-max-microvolt = <1080000>;
++				regulator-ramp-delay = <2500>;
+ 				regulator-name = "vdd-gpu";
+ 			};
+
```
你把补丁打进去编译试试吧。

**Comment by ZZMHA227** [comment]
![屏幕截图 2022-03-24 202906](https://user-images.githubusercontent.com/57690855/159916373-967d1921-c80d-49a4-a0e3-a2b4f46f5971.png)
patch 打进去之后编译失败

**Comment by ZZMHA227** [comment]
用lean的代码可以编译成功，但是频率还是1.2GHz,不是1.8GHz

**Comment by AmadeusGhost** [comment]
你要在 18.06-k5.4 分支下测试，还有你就这样发一张 action 的图片可能只有上帝才能帮助你了，实在不会弄就本地编译。

**Comment by ZZMHA227** [comment]
![屏幕截图 2022-03-25 174301](https://user-images.githubusercontent.com/57690855/160096216-e9e3a7d9-3054-4f78-99a4-e4e69278e82e.png)
![屏幕截图 2022-03-25 123043](https://user-images.githubusercontent.com/57690855/160096257-a5a19186-a327-4f4a-844a-e0a277a46ef1.png)
![屏幕截图 2022-03-25 174434](https://user-images.githubusercontent.com/57690855/160096414-e75b84ef-d21e-403b-ae54-61ebc2510b72.png)
用的5.4分支，patches-5.4
目录下也有新加的patch，但最高还是1.2GHz，没到1.8GHz。另外，新加的patch不需要在make menuconfig里勾选吧。

**Comment by ZZMHA227** [comment]
随便搜索看到这个，佬，要不要加？https://github.com/armbian/build/blob/735a3679e2de12db555e17b0485f99f86a1d106a/patch/kernel/sunxi-dev-h6/add-1.8ghz.patch
曾经试过openwrt源码，也是1.2GHz

**Comment by AmadeusGhost** [comment]
发一下内核日志看看？你这个是 cpufreq 驱动根本没工作。

**Comment by ZZMHA227** [comment]
[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd034]
[    0.000000] Linux version 5.4.162 (runner@fv-az132-586) (gcc version 8.4.0 (OpenWrt GCC 8.4.0 r11797-d16776bc33)) #0 SMP Fri Mar 25 02:39:55 2022
[    0.000000] Machine model: OrangePi One Plus
[    0.000000] On node 0 totalpages: 262144
[    0.000000]   DMA32 zone: 4096 pages used for memmap
[    0.000000]   DMA32 zone: 0 pages reserved
[    0.000000]   DMA32 zone: 262144 pages, LIFO batch:63
[    0.000000] psci: probing for conduit method from DT.
[    0.000000] psci: PSCIv1.1 detected in firmware.
[    0.000000] psci: Using standard PSCI v0.2 function IDs
[    0.000000] psci: MIGRATE_INFO_TYPE not supported.
[    0.000000] psci: SMC Calling Convention v1.0
[    0.000000] percpu: Embedded 21 pages/cpu s45784 r8192 d32040 u86016
[    0.000000] pcpu-alloc: s45784 r8192 d32040 u86016 alloc=21*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3 
[    0.000000] Detected VIPT I-cache on CPU0
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 258048
[    0.000000] Kernel command line: console=ttyS0,115200 earlyprintk root=PARTUUID=5452574f-02 rootwait
[    0.000000] Dentry cache hash table entries: 131072 (order: 8, 1048576 bytes, linear)
[    0.000000] Inode-cache hash table entries: 65536 (order: 7, 524288 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 1016188K/1048576K available (7678K kernel code, 698K rwdata, 2196K rodata, 576K init, 287K bss, 32388K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] rcu: 	RCU restricting CPUs from NR_CPUS=8 to nr_cpu_ids=4.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=4
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[    0.000000] GIC: Using split EOI/Deactivate mode
[    0.000000] random: get_random_bytes called from start_kernel+0x2dc/0x42c with crng_init=0
[    0.000000] arch_timer: cp15 timer(s) running at 24.00MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x588fe9dc0, max_idle_ns: 440795202592 ns
[    0.000004] sched_clock: 56 bits at 24MHz, resolution 41ns, wraps every 4398046511097ns
[    0.000185] Console: colour dummy device 80x25
[    0.000213] Calibrating delay loop (skipped), value calculated using timer frequency.. 48.00 BogoMIPS (lpj=240000)
[    0.000222] pid_max: default: 32768 minimum: 301
[    0.000343] Mount-cache hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    0.000355] Mountpoint-cache hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    0.001521] ASID allocator initialised with 32768 entries
[    0.001587] rcu: Hierarchical SRCU implementation.
[    0.001995] smp: Bringing up secondary CPUs ...
[    0.002491] Detected VIPT I-cache on CPU1
[    0.002539] CPU1: Booted secondary processor 0x0000000001 [0x410fd034]
[    0.002975] Detected VIPT I-cache on CPU2
[    0.003002] CPU2: Booted secondary processor 0x0000000002 [0x410fd034]
[    0.003402] Detected VIPT I-cache on CPU3
[    0.003427] CPU3: Booted secondary processor 0x0000000003 [0x410fd034]
[    0.003482] smp: Brought up 1 node, 4 CPUs
[    0.003498] SMP: Total of 4 processors activated.
[    0.003503] CPU features: detected: 32-bit EL0 Support
[    0.003508] CPU features: detected: CRC32 instructions
[    0.003540] CPU features: emulated: Privileged Access Never (PAN) using TTBR0_EL1 switching
[    0.003547] CPU: All CPU(s) started at EL2
[    0.003563] alternatives: patching kernel code
[    0.008071] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.008091] futex hash table entries: 1024 (order: 4, 65536 bytes, linear)
[    0.008249] pinctrl core: initialized pinctrl subsystem
[    0.008921] NET: Registered protocol family 16
[    0.009819] DMA: preallocated 2048 KiB pool for atomic allocations
[    0.022300] iommu: Default domain type: Translated 
[    0.022562] SCSI subsystem initialized
[    0.022691] libata version 3.00 loaded.
[    0.022886] usbcore: registered new interface driver usbfs
[    0.022922] usbcore: registered new interface driver hub
[    0.022956] usbcore: registered new device driver usb
[    0.023140] pps_core: LinuxPPS API ver. 1 registered
[    0.023145] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    0.023162] PTP clock support registered
[    0.023630] Advanced Linux Sound Architecture Driver Initialized.
[    0.023678] workqueue: max_active 576 requested for napi_workq is out of range, clamping between 1 and 512
[    0.024380] clocksource: Switched to clocksource arch_sys_counter
[    0.028059] thermal_sys: Registered thermal governor 'step_wise'
[    0.028543] NET: Registered protocol family 2
[    0.028666] IP idents hash table entries: 16384 (order: 5, 131072 bytes, linear)
[    0.029237] tcp_listen_portaddr_hash hash table entries: 512 (order: 1, 8192 bytes, linear)
[    0.029262] TCP established hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    0.029336] TCP bind hash table entries: 8192 (order: 5, 131072 bytes, linear)
[    0.029483] TCP: Hash tables configured (established 8192 bind 8192)
[    0.029570] UDP hash table entries: 512 (order: 2, 16384 bytes, linear)
[    0.029603] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes, linear)
[    0.029750] NET: Registered protocol family 1
[    0.029775] PCI: CLS 0 bytes, default 64
[    0.030307] kvm [1]: IPA Size Limit: 40 bits
[    0.030660] kvm [1]: vgic interrupt IRQ1
[    0.030768] kvm [1]: Hyp mode initialized successfully
[    0.031508] workingset: timestamp_bits=46 max_order=18 bucket_order=0
[    0.035839] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.035951] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.037180] sun50i-de2-bus 1000000.bus: Error couldn't map SRAM to device
[    0.037608] sun4i-usb-phy 5100400.phy: Couldn't request ID GPIO
[    0.041780] sun50i-h6-r-pinctrl 7022000.pinctrl: initialized sunXi PIO driver
[    0.042097] sun4i-pwm 300a000.pwm: get bus clock failed fffffffffffffdfb
[    0.050639] Serial: 8250/16550 driver, 8 ports, IRQ sharing disabled
[    0.052427] cacheinfo: Unable to detect cache hierarchy for CPU 0
[    0.055389] loop: module loaded
[    0.056370] libphy: Fixed MDIO Bus: probed
[    0.057695] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    0.057708] ehci-platform: EHCI generic platform driver
[    0.058215] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    0.058240] ohci-platform: OHCI generic platform driver
[    0.058541] usbcore: registered new interface driver usb-storage
[    0.058910] mousedev: PS/2 mouse device common for all mice
[    0.059637] sun6i-rtc 7000000.rtc: registered as rtc0
[    0.059646] sun6i-rtc 7000000.rtc: RTC enabled
[    0.059733] i2c /dev entries driver
[    0.059915] sun50i-h6-r-pinctrl 7022000.pinctrl: 7022000.pinctrl supply vcc-pl not found, using dummy regulator
[    0.060406] axp20x-i2c 0-0036: AXP20x variant AXP806 found
[    0.065599] input: axp20x-pek as /devices/platform/soc/7081400.i2c/i2c-0/0-0036/axp221-pek/input/input0
[    0.067061] vdd-cpu: supplied by vcc-5v
[    0.068188] vdd-gpu: supplied by vcc-5v
[    0.068666] vdd-sys: supplied by vcc-5v
[    0.069231] vcc-dram: supplied by vcc-5v
[    0.069803] vcc-pl: supplied by vcc-5v
[    0.070348] vcc-ac200: Bringing 700000uV into 3300000-3300000uV
[    0.070755] vcc-ac200: supplied by vcc-5v
[    0.071224] vcc25-dram: supplied by vcc-5v
[    0.071797] vcc-bias-pll: supplied by vcc-5v
[    0.072771] vcc-efuse-pcie-hdmi-io: supplied by vcc-5v
[    0.073322] vcc-dcxoio: supplied by vcc-5v
[    0.073981] bldo4: supplied by vcc-5v
[    0.074454] vcc-3v3: supplied by vcc-5v
[    0.075009] vcc-wifi-1: Bringing 700000uV into 3300000-3300000uV
[    0.075420] vcc-wifi-1: supplied by vcc-5v
[    0.075907] vcc-wifi-2: Bringing 700000uV into 3300000-3300000uV
[    0.076304] vcc-wifi-2: supplied by vcc-5v
[    0.076463] sw: supplied by regulator-dummy
[    0.076533] axp20x-i2c 0-0036: AXP20X driver loaded
[    0.077399] sunxi-wdt 7020400.watchdog: Watchdog enabled (timeout=16 sec, nowayout=0)
[    0.077736] sun50i-cpufreq-nvmem: probe of sun50i-cpufreq-nvmem failed with error -2
[    0.079907] NET: Registered protocol family 10
[    0.080559] Segment Routing with IPv6
[    0.080616] NET: Registered protocol family 17
[    0.080649] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
[    0.080655] can: controller area network core (rev 20170425 abi 9)
[    0.080696] NET: Registered protocol family 29
[    0.080703] 8021q: 802.1Q VLAN Support v1.8
[    0.090774] sun4i-usb-phy 5100400.phy: Couldn't request ID GPIO
[    0.094442] sun50i-h6-pinctrl 300b000.pinctrl: initialized sunXi PIO driver
[    0.094967] sun50i-h6-pinctrl 300b000.pinctrl: 300b000.pinctrl supply vcc-ph not found, using dummy regulator
[    0.095267] printk: console [ttyS0] disabled
[    0.115670] 5000000.serial: ttyS0 at MMIO 0x5000000 (irq = 21, base_baud = 1500000) is a 16550A
[    0.911803] printk: console [ttyS0] enabled
[    0.916735] sun50i-h6-pinctrl 300b000.pinctrl: 300b000.pinctrl supply vcc-pd not found, using dummy regulator
[    0.926802] dwmac-sun8i 5020000.ethernet: IRQ eth_wake_irq not found
[    0.933148] dwmac-sun8i 5020000.ethernet: IRQ eth_lpi not found
[    0.939126] dwmac-sun8i 5020000.ethernet: Failed to get PHY regulator (-517)
[    0.948718] sun50i-h6-pinctrl 300b000.pinctrl: 300b000.pinctrl supply vcc-pf not found, using dummy regulator
[    0.959078] sunxi-mmc 4020000.mmc: Got CD GPIO
[    0.987029] sunxi-mmc 4020000.mmc: initialized, max. request size: 16384 KB, uses new timings mode
[    0.996460] sun50i-h6-pinctrl 300b000.pinctrl: 300b000.pinctrl supply vcc-pd not found, using dummy regulator
[    1.006568] vcc-gmac-3v3: supplied by vcc-ac200
[    1.011280] sun50i-h6-pinctrl 300b000.pinctrl: 300b000.pinctrl supply vcc-pc not found, using dummy regulator
[    1.022216] dwmac-sun8i 5020000.ethernet: IRQ eth_wake_irq not found
[    1.028582] dwmac-sun8i 5020000.ethernet: IRQ eth_lpi not found
[    1.034588] dwmac-sun8i 5020000.ethernet: 5020000.ethernet supply phy-io not found, using dummy regulator
[    1.044247] dwmac-sun8i 5020000.ethernet: PTP uses main clock
[    1.050010] dwmac-sun8i 5020000.ethernet: Current syscon value is not the default 58000 (expect 50000)
[    1.094212] mmc0: host does not support reading read-only switch, assuming write-enable
[    1.104152] mmc0: new high speed SDHC card at address b368
[    1.110185] mmcblk0: mmc0:b368 NCard 29.1 GiB 
[    1.115737]  mmcblk0: p1 p2
[    1.174520] dwmac-sun8i 5020000.ethernet: No HW DMA feature register supported
[    1.181736] dwmac-sun8i 5020000.ethernet: RX Checksum Offload Engine supported
[    1.188963] dwmac-sun8i 5020000.ethernet: COE Type 2
[    1.193921] dwmac-sun8i 5020000.ethernet: TX Checksum insertion supported
[    1.200706] dwmac-sun8i 5020000.ethernet: Normal descriptors
[    1.206365] dwmac-sun8i 5020000.ethernet: Chain mode enabled
[    1.212022] dwmac-sun8i 5020000.ethernet: device MAC address ea:b8:85:dc:a1:56
[    1.219370] libphy: stmmac: probed
[    1.224556] phy phy-5100400.phy.0: Changing dr_mode to 1
[    1.229876] ehci-platform 5101000.usb: EHCI Host Controller
[    1.235464] ehci-platform 5101000.usb: new USB bus registered, assigned bus number 1
[    1.243277] ehci-platform 5101000.usb: irq 25, io mem 0x05101000
[    1.274389] ehci-platform 5101000.usb: USB 2.0 started, EHCI 1.00
[    1.280612] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 5.04
[    1.288879] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.296100] usb usb1: Product: EHCI Host Controller
[    1.300970] usb usb1: Manufacturer: Linux 5.4.162 ehci_hcd
[    1.306448] usb usb1: SerialNumber: 5101000.usb
[    1.311281] hub 1-0:1.0: USB hub found
[    1.315070] hub 1-0:1.0: 1 port detected
[    1.319587] ehci-platform 5311000.usb: EHCI Host Controller
[    1.325176] ehci-platform 5311000.usb: new USB bus registered, assigned bus number 2
[    1.332982] ehci-platform 5311000.usb: irq 27, io mem 0x05311000
[    1.364384] ehci-platform 5311000.usb: USB 2.0 started, EHCI 1.00
[    1.370587] usb usb2: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 5.04
[    1.378851] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.386087] usb usb2: Product: EHCI Host Controller
[    1.390958] usb usb2: Manufacturer: Linux 5.4.162 ehci_hcd
[    1.396442] usb usb2: SerialNumber: 5311000.usb
[    1.401263] hub 2-0:1.0: USB hub found
[    1.405040] hub 2-0:1.0: 1 port detected
[    1.524452] ohci-platform 5101400.usb: Generic Platform OHCI controller
[    1.531071] ohci-platform 5101400.usb: new USB bus registered, assigned bus number 3
[    1.538910] ohci-platform 5101400.usb: irq 26, io mem 0x05101400
[    1.618513] usb usb3: New USB device found, idVendor=1d6b, idProduct=0001, bcdDevice= 5.04
[    1.626778] usb usb3: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.633990] usb usb3: Product: Generic Platform OHCI controller
[    1.639909] usb usb3: Manufacturer: Linux 5.4.162 ohci_hcd
[    1.645392] usb usb3: SerialNumber: 5101400.usb
[    1.650199] hub 3-0:1.0: USB hub found
[    1.653967] hub 3-0:1.0: 1 port detected
[    1.658477] ohci-platform 5311400.usb: Generic Platform OHCI controller
[    1.665104] ohci-platform 5311400.usb: new USB bus registered, assigned bus number 4
[    1.672920] ohci-platform 5311400.usb: irq 28, io mem 0x05311400
[    1.748514] usb usb4: New USB device found, idVendor=1d6b, idProduct=0001, bcdDevice= 5.04
[    1.756781] usb usb4: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.763992] usb usb4: Product: Generic Platform OHCI controller
[    1.769911] usb usb4: Manufacturer: Linux 5.4.162 ohci_hcd
[    1.775396] usb usb4: SerialNumber: 5311400.usb
[    1.780187] hub 4-0:1.0: USB hub found
[    1.783952] hub 4-0:1.0: 1 port detected
[    1.788570] usb_phy_generic usb_phy_generic.1.auto: usb_phy_generic.1.auto supply vcc not found, using dummy regulator
[    2.004567] musb-hdrc musb-hdrc.2.auto: MUSB HDRC host driver
[    2.010319] musb-hdrc musb-hdrc.2.auto: new USB bus registered, assigned bus number 5
[    2.018274] usb usb5: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 5.04
[    2.026538] usb usb5: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    2.033750] usb usb5: Product: MUSB HDRC host driver
[    2.038719] usb usb5: Manufacturer: Linux 5.4.162 musb-hcd
[    2.044197] usb usb5: SerialNumber: musb-hdrc.2.auto
[    2.049430] hub 5-0:1.0: USB hub found
[    2.053196] hub 5-0:1.0: 1 port detected
[    2.058304] sun6i-rtc 7000000.rtc: setting system clock to 1970-01-01T00:00:11 UTC (11)
[    2.066762] ALSA device list:
[    2.069726]   No soundcards found.
[    2.086597] EXT4-fs (mmcblk0p2): mounted filesystem without journal. Opts: (null)
[    2.094107] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    2.101137] Freeing unused kernel memory: 576K
[    2.154407] Run /sbin/init as init process
[    2.226033] random: fast init done
[    2.250260] init: Console is alive
[    2.253796] init: - watchdog -
[    2.641219] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[    2.713135] Key type encrypted registered
[    2.727474] raid6: using algorithm neonx8 gen() 0 MB/s
[    2.732612] raid6: .... xor() 0 MB/s, rmw enabled
[    2.737337] raid6: using neon recovery algorithm
[    2.746335] xor: measuring software checksum speed
[    2.844372]    8regs     :  1804.000 MB/sec
[    2.944368]    32regs    :  2069.600 MB/sec
[    3.044368]    arm64_neon:  1840.000 MB/sec
[    3.048544] xor: using function: 32regs (2069.600 MB/sec)
[    3.123705] Btrfs loaded, crc32c=crc32c-generic
[    3.129372] kmodloader: done loading kernel modules from /etc/modules-boot.d/*
[    3.143499] init: - preinit -
[    3.312724] random: jshn: uninitialized urandom read (4 bytes read)
[    3.347355] random: jshn: uninitialized urandom read (4 bytes read)
[    3.363388] random: jshn: uninitialized urandom read (4 bytes read)
[    3.466381] dwmac-sun8i 5020000.ethernet eth0: PHY [stmmac-0:01] driver [RTL8211E Gigabit Ethernet]
[    3.476149] dwmac-sun8i 5020000.ethernet eth0: No Safety Features support found
[    3.483452] dwmac-sun8i 5020000.ethernet eth0: No MAC Management Counters available
[    3.491110] dwmac-sun8i 5020000.ethernet eth0: PTP not supported by HW
[    3.497640] dwmac-sun8i 5020000.ethernet eth0: configuring for phy/rgmii link mode
[    6.560012] mount_root: mounting /dev/root
[    6.564880] EXT4-fs (mmcblk0p2): warning: mounting unchecked fs, running e2fsck is recommended
[    6.576201] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[    6.581745] mount_root: loading kmods from internal overlay
[    6.601766] kmodloader: loading kernel modules from //etc/modules-boot.d/*
[    6.609432] kmodloader: done loading kernel modules from //etc/modules-boot.d/*
[    6.785405] block: attempting to load /etc/config/fstab
[    6.793092] block: extroot: not configured
[    6.887766] FAT-fs (mmcblk0p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
[    7.014587] urandom-seed: Seeding with /etc/urandom.seed
[    7.201758] procd: - early -
[    7.204747] procd: - watchdog -
[    7.454660] FAT-fs (mmcblk0p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
[    7.749014] procd: - watchdog -
[    7.753886] procd: - ubus (running as root!) -
[    7.767852] urandom_read: 2 callbacks suppressed
[    7.767858] random: ubusd: uninitialized urandom read (4 bytes read)
[    7.808052] random: ubusd: uninitialized urandom read (4 bytes read)
[    7.814588] random: ubusd: uninitialized urandom read (4 bytes read)
[    7.821999] procd: - init -
[    7.960332] urngd: v1.0.2 started.
[    7.996718] random: crng init done
[    8.000124] random: 2 urandom warning(s) missed due to ratelimiting
[    8.170071] kmodloader: loading kernel modules from /etc/modules.d/*
[    8.214718] NET: Registered protocol family 38
[    8.237653] async_tx: api initialized (async)
[    8.252852] device-mapper: ioctl: 4.41.0-ioctl (2019-09-16) initialised: dm-devel@redhat.com
[    8.301528] cryptodev: driver 1.12 loaded.
[    8.356253] Bridge firewalling registered
[    8.378187] xt_time: kernel timezone is -0000
[    8.408467] PPP generic driver version 2.4.2
[    8.413565] PPP MPPE Compression module registered
[    8.419420] NET: Registered protocol family 24
[    8.431527] kmodloader: done loading kernel modules from /etc/modules.d/*
[   10.692704] xt_FULLCONENAT: RFC3489 Full Cone NAT module
[   10.692704] xt_FULLCONENAT: Copyright (C) 2018 Chion Tang <tech@chionlab.moe>
[   11.146911] dwmac-sun8i 5020000.ethernet eth0: PHY [stmmac-0:01] driver [RTL8211E Gigabit Ethernet]
[   11.156792] dwmac-sun8i 5020000.ethernet eth0: No Safety Features support found
[   11.164110] dwmac-sun8i 5020000.ethernet eth0: No MAC Management Counters available
[   11.171810] dwmac-sun8i 5020000.ethernet eth0: PTP not supported by HW
[   11.178384] dwmac-sun8i 5020000.ethernet eth0: configuring for phy/rgmii link mode
[   11.187188] br-lan: port 1(eth0) entered blocking state
[   11.192415] br-lan: port 1(eth0) entered disabled state
[   11.197892] device eth0 entered promiscuous mode
[   15.365007] dwmac-sun8i 5020000.ethernet eth0: Link is Up - 1Gbps/Full - flow control rx/tx
[   15.373413] br-lan: port 1(eth0) entered blocking state
[   15.378685] br-lan: port 1(eth0) entered forwarding state
[   15.384515] IPv6: ADDRCONF(NETDEV_CHANGE): br-lan: link becomes ready

**Comment by ZZMHA227** [comment]
佬，这块板子还有得救吗？靠，不会全网就我一个人用这板子吧(给大佬递🚬

**Comment by AmadeusGhost** [comment]
> 靠，不会全网就我一个人用这板子吧

目前来看是的，我也不知道为什么 cpufreq 驱动没加载成功。后面我还跑去 armbian 看了下相关部分，补丁并无什么差别。只能自己解决或者选择寄给我们（

**Comment by ZZMHA227** [comment]
我记得有的矿难产品，我家云，用的也是H6的芯片。但它的那个cpu频率是1.8GHz，还可以动态调节。

**Comment by ZZMHA227** [comment]
你们地址是啥，寄过去给你们修修看

**Comment by AmadeusGhost** [comment]
> 你们地址是啥，寄过去给你们修修看

mailto: amadeus@openjmu.xyz，留下你的联系方式（最好是用 tg，其次 qq）
