### ISSUE TITLE
master 分支编译失败 已尝试单线也是失败 

### ISSUE THREAD

**Issue by WXR2727** [immortalwrt/immortalwrt#646]
make[2]: Leaving directory '/home/khor/immortalwrt'
package/Makefile:110: recipe for target '/home/khor/immortalwrt/staging_dir/target-aarch64_generic_musl/stamp/.package_compile' failed
make[1]: *** [/home/khor/immortalwrt/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/khor/immortalwrt'
Build failed - please re-run with -j1 to see the real error message
/home/khor/immortalwrt/include/toplevel.mk:228: recipe for target 'world' failed
make: *** [world] Error 1

**Comment by ksong008** [comment]
请帖j1的图

**Comment by WXR2727** [comment]
VPS ubuntu 18 编译

**Comment by WXR2727** [comment]
![Screenshot 2022-03-26 at 10 32 56 PM](https://user-images.githubusercontent.com/96520876/160244157-6d0c5746-aa86-463a-a0df-2bff88f18550.png)

**Comment by WXR2727** [comment]
Luci application 我通常只选passwall

**Comment by 1715173329** [comment]
不要用 master 分支。

**Comment by WXR2727** [comment]
21.02 昨天编译一样问题 ， 今天下午编译的21.02就成功 可是老失联 R2S

**Comment by WXR2727** [comment]
失联就是断网 后台进不去

**Comment by WXR2727** [comment]
![Screenshot 2022-03-26 at 10 46 30 PM](https://user-images.githubusercontent.com/96520876/160244679-2f5ae5cb-cb40-46fd-9c56-477a0fd5f657.png)
官方openwrt也是一样的问题

**Comment by 1715173329** [comment]
> 失联就是断网 后台进不去

体质问题，换驱动。rtl8152-vendor

**Comment by WXR2727** [comment]
大佬求教学 怎么换

**Comment by WXR2727** [comment]
大佬驱动是bootloader么

**Comment by AmadeusGhost** [comment]
> 失联就是断网 后台进不去

这边建议出掉 r2s 换个 x86 或者硬路由。
