### ISSUE TITLE
5.15编译错误

### ISSUE THREAD

**Issue by ohbaby30** [immortalwrt/immortalwrt#661]
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/62003514/161362935-0752a7c0-c9b2-4b8c-b3a9-111371957410.png">

这是R2S编译5.15的错误 去掉shortcut-fe就好了 R4S是一样的错误

但是X86 5.15是usb-asix-AX88179错误 去掉也能成功

但是5.10下没有问题

望修复

**Comment by 1715173329** [comment]
两个问题，一个日志，建议隔壁寻找算命先生。
master 不是给普通用户使用的。

**Comment by WXR2727** [comment]
21.02 没有问题 ，建议用这个稳定的版本
