### ISSUE TITLE
出现错误

### ISSUE THREAD

**Issue by 990052053** [immortalwrt/immortalwrt#662]
<img width="1824" alt="捕获" src="https://user-images.githubusercontent.com/77133451/161409183-ca6bc190-19f6-45fb-9978-2277e19d0d16.PNG">

**Comment by EnnawYang** [comment]
为你算了一卦：寄，不要用ssh

**Comment by 990052053** [comment]
> 为你算了一卦：寄，不要用ssh

不用ssh还得本地虚拟机建立.config文件,要不然也不行啊,这是ssh远程配置.config的原因吗
