### ISSUE TITLE
k5.4 分支 LuCI -> Applications 下面找不到 adguardhome 的 luci 了

### ISSUE THREAD

**Issue by zfh18** [immortalwrt/immortalwrt#667]
不提供 luci-app-adguardhome 的编译了吗？

**Comment by WuSiYu** [comment]
今天编译也遇到了，搜了一下，是在immortalwrt/luci仓库移除的这个commit移除的：https://github.com/immortalwrt/luci/commit/fb311084c2adfef02d561e70f4f11d8ff7dee054
相关讨论应该是：https://github.com/immortalwrt/luci/issues/98

个人感觉luci-app-adguardhome还是有点用的，比如端口映射和看日志，但上游不维护了

**Comment by zzz6839** [comment]
加APP的惯性思维是从LUCI>APPLICATION里面找，如果要加adguardhome需要翻package table才能定位到，会很麻烦，而且LUCI的APP勾选能确保所有依赖被选中，所以在LUCI里面加luci-app-Adguardhome是更人性化的做法。

**Comment by WuSiYu** [comment]
> @WuSiYu adgh的web ui是adgh自带的 和luci有啥关系？

https://github.com/rufengsuixing/luci-app-adguardhome
