### ISSUE TITLE
这个是sulinggg/openwrt的官方源吗？

### ISSUE THREAD

**Issue by lanyucomputer** [immortalwrt/immortalwrt#676]
如果是的话，反馈一下，章鱼星球刷这个sulinggg/openwrt可以用，但架构那里显示是空白的

**Comment by 1715173329** [comment]
This is a unsupported device.

**Comment by lanyucomputer** [comment]
but it can work with my device,i can show you 20220423155556.png,you see？

**Comment by AmadeusGhost** [comment]
> 章鱼星球刷这个openwrt可以用，但架构那里显示是空白的

这里不欢迎杂交固件，只支持能启动原生 op 的设备。
