### ISSUE TITLE
openwrt-21.02 可以新增内核5.4/5.10支持吗? 希望能支持小米 CR660X 

### ISSUE THREAD

**Issue by ayancn** [immortalwrt/immortalwrt#708]
跟[openwrt-18.06-k5.4](https://github.com/immortalwrt/immortalwrt/tree/openwrt-18.06-k5.4)这个分支一样的, 谢谢

**Comment by 1715173329** [comment]
可以用 master 分支。

**Comment by ayancn** [comment]
> 可以用 master 分支。

最新的master 分支有自动重启问题,可以出22.03分支版本吗,谢谢!
