### ISSUE TITLE
GCC11.3.0 patch error

### ISSUE THREAD

**Issue by zheshifandian** [immortalwrt/immortalwrt#757]
branch openwrt-18.06-k5.4
gcc 11.3.0

make[2]: Entering directory '/home/zheshifandian/immortalwrt/toolchain/gcc/initial'
/home/zheshifandian/immortalwrt/staging_dir/host/bin/sed -i -e 's,TARGET_CROSS=.*,TARGET_CROSS=arm-openwrt-linux-muslgnueabi-,' /home/zheshifandian/immortalwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.3.0_musl_eabi/info.mk
/home/zheshifandian/immortalwrt/staging_dir/host/bin/sed -i -e 's,GCC_VERSION=.*,GCC_VERSION=11.3.0,' /home/zheshifandian/immortalwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.3.0_musl_eabi/info.mk
. /home/zheshifandian/immortalwrt/include/shell.sh; xzcat /home/zheshifandian/immortalwrt/dl/gcc-11.3.0.tar.xz | tar -C /home/zheshifandian/immortalwrt/build_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.3.0_musl_eabi/gcc-11.3.0-initial/.. -xf - --exclude-from='/home/zheshifandian/immortalwrt/toolchain/gcc/initial/../exclude-testsuite' --exclude=gcc/ada/*.ad* --exclude=libjava
[ ! -d ./src/ ] || cp -fpR ./src/* /home/zheshifandian/immortalwrt/build_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.3.0_musl_eabi/gcc-11.3.0-initial

Applying ../patches/11.3.0/001-Revert-Cleanup-range-of-address-calculations.patch using plaintext: 
patching file gcc/gimple-range.cc
Hunk #1 succeeded at 447 (offset 16 lines).
Hunk #2 FAILED at 446.
1 out of 2 hunks FAILED -- saving rejects to file gcc/gimple-range.cc.rej
patching file gcc/gimple-range.h
Hunk #1 succeeded at 66 with fuzz 1 (offset 4 lines).
patching file gcc/range-op.cc
Patch failed!  Please fix ../patches/11.3.0/001-Revert-Cleanup-range-of-address-calculations.patch!
make[2]: *** [Makefile:44: /home/zheshifandian/immortalwrt/build_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.3.0_musl_eabi/gcc-11.3.0-initial/.prepared] Error 1
make[2]: Leaving directory '/home/zheshifandian/immortalwrt/toolchain/gcc/initial'
time: toolchain/gcc/initial/compile#6.84#1.80#6.39
    ERROR: toolchain/gcc/initial failed to build.
make[1]: *** [toolchain/Makefile:97: toolchain/gcc/initial/compile] Error 1
make[1]: Leaving directory '/home/zheshifandian/immortalwrt'
make: *** [/home/zheshifandian/immortalwrt/include/toplevel.mk:230：toolchain/compile] 错误 2

**Comment by 1715173329** [comment]
Fixed.
