### ISSUE TITLE
Realtek PCI network card not detected

### ISSUE THREAD

**Issue by umarizulkifli** [immortalwrt/immortalwrt#758]
**Description**
Realtek PCI network card not detected because there's no driver.

```
$ lspci -v
Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL810xE PCI Express Fast Ethernet controller [10ec:8136] (rev 02)
$ ifconfig eth0
ifconfig: eth0: error fetching interface information: Device not found
```

**Sources**
http://mirror2.openwrt.org/sources/r8101-1.014.00.tar.bz2
https://github.com/ghostrider-reborn/realtek-r8101-linux-driver

**Comment by 1715173329** [comment]
version?
