### ISSUE TITLE
R4S LAN口被识别成WAN口 WAN口不工作

### ISSUE THREAD

**Issue by KernelErr** [immortalwrt/immortalwrt#768]
编译用的Commit：[e5b3c58](https://github.com/immortalwrt/immortalwrt/commit/e5b3c583bff7e0dc85de856046a5d5187d6e57b5)

配置文件：
[config.zip](https://github.com/immortalwrt/immortalwrt/files/9444589/config.zip)
除了选择Target到R4S外没有修改其他选项

编译后能够正常启动，但WAN口不工作（插上网线后不亮灯），LAN口工作但是被识别为了WAN口，即插上网线到LAN后WAN灯亮，接上级路由可以找到路由器。由于有防火墙的原因无法ssh链接和进入LuCI。类似的Issue是#309，但是不知道怎么解决的。

**Comment by 1715173329** [comment]
你的设备没有 EEPROM，无法支持。
