### ISSUE TITLE
歌华链ghl-r-001 18.06-k5.4无线有bug，修改信道或加密模式等其他设置后无法重启/开机自动启动

### ISSUE THREAD

**Issue by 4thanks** [immortalwrt/immortalwrt#784]
路由器：歌华链ramips-mt7621-gehua_ghl-r-001
固件版本：18.06-k5.4

重启/开机需手动重启无线，即使在开机脚本加入
```
ifconfig ra0 up   #2G
ifconfig rai0 up  #5G
```
能启动Wi-Fi但连接后无法获取IP，看LAN接口也没桥接wireless？

**Comment by 1715173329** [comment]
18.06-k5.4 is EoL, use 21.02 instead, or use https://github.com/padavanonly/immortalwrt.
