### ISSUE TITLE
mt_wifi sta mode support

### ISSUE THREAD

**Issue by i3roly** [immortalwrt/immortalwrt#817]
hi,

from what i'm seeing in all mtk drivers, the sta mode does not work at this time.

is this correct? or is the sta mode working but only with private source code?

i've looked at mt7921 v7400 and mt7615 v5100 and it seems the existing sources do not provide STA support.

**Comment by 1715173329** [comment]
Support for the 18.06-k5.4 branch is EoL, you may move to https://github.com/padavanonly/immortalwrtmt7622/

Thanks.
