### ISSUE TITLE
可以增加一下h68k支持吗？

### ISSUE THREAD

**Issue by Beaverfffan** [immortalwrt/immortalwrt#844]
h68k有计划做cpe版本（走usb），想问一下能否添加一下支持。我这个菜鸟搞不定dts了。
https://github.com/coolsnowwolf/lede/search?q=h68k&type=commits

**Comment by 1715173329** [comment]
没设备要怎么支持。

**Comment by Beaverfffan** [comment]
打扰您了。mt7921这玩意在rk的驱动看起来很恶心，得等到6.1内核才能用。暂时不尝试移植过来了。
