### ISSUE TITLE
翻译问题 有点玄学

### ISSUE THREAD

**Issue by yyhhkya** [immortalwrt/immortalwrt#858]
### Describe the bug

使用github action编译21.02 均没有报错
[https://github.com/yyhhkya/build-immortalwrt](https://github.com/yyhhkya/build-immortalwrt)

之前编译了好几次 这些都全是英文的
![@69WVFQ)~{A1E7IJJ}A~%IV](https://user-images.githubusercontent.com/87574541/213350901-d9ff29df-49cd-4df4-adae-02a2b7035520.png)

这次新加了上网时间控制 那个统计就变中文了 然后轮到这个新加的变英文了
![M_D1@NPYZ{ EV0V_)EJ0](https://user-images.githubusercontent.com/87574541/213351006-c6ecd326-a967-4132-bc26-98b00cc533b7.png)

### ImmortalWrt version

r19866-5657d4ffb0

### ImmortalWrt target/subtarget

ramips/mt7621

### Device

Newifi-D2

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
本地缓存问题。

**Comment by yyhhkya** [comment]
嗷 抱歉 犯低级错误了~
