### ISSUE TITLE
Unable to downloand 21.02.4 version

### ISSUE THREAD

**Issue by naveen1hot** [immortalwrt/immortalwrt#867]
### Describe the bug

While I search under release 21.02.4 it's empty. But I can see packages file under the same release. Target files is available?? If yes where I can download. Kindly help. Thanks.
![Screenshot_20230207-084939_Chrome](https://user-images.githubusercontent.com/67212860/217140089-c394c85c-284b-4464-b136-f7483ba7f3d8.png)

### ImmortalWrt version

21.02.4

### ImmortalWrt target/subtarget

Ath79

### Device

TP-Link Archer A7-v5

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
It's not released yet. Blocked by upcoming mac80211 updates.
