### ISSUE TITLE
X86/X64 Intel GPU驱动

### ISSUE THREAD

**Issue by VRMonsters** [immortalwrt/immortalwrt#904]
### Describe the bug

目前X86/X64平台的固件没有Intel的驱动。最新的openwrt已经支持kmod-drm-i915。自动化构建也提示无该包

Unsupported package(s): kmod-drm-i915

### ImmortalWrt version

21.02.4

### ImmortalWrt target/subtarget

x64

### Device

intel

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
https://github.com/openwrt/openwrt/pull/5027
It's yet merged upstream. Maybe you can create a new PR for it.
