### ISSUE TITLE
802.11v 似乎没有正常启用

### ISSUE THREAD

**Issue by f0re1gnKey** [immortalwrt/immortalwrt#929]
### Describe the bug

在luci无线处启用了802.11v，winfi里并没有看到相应的功能启用
目前mt7620和mt7621均有此现象

### ImmortalWrt version

r19951-da9ffd2add

### ImmortalWrt target/subtarget

ramips/mt7621

### Device

Phicomm K2P

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
ramips 推荐刷 padavan
