### ISSUE TITLE
Immortal master 5.15.106 状态-概览 cpu的核心数，线程数，频率，温度显示异常

### ISSUE THREAD

**Issue by ximiTech** [immortalwrt/immortalwrt#930]
### Describe the bug

Immortal master 5.15.106 状态-概览 中 cpu的核心数，线程数，频率，温度显示异常，没有显示了，之前好像有这个功能的。

### ImmortalWrt version

5.15.106

### ImmortalWrt target/subtarget

x86

### Device

x86

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
没选 autocore
