### ISSUE TITLE
21.02 云编译报错

### ISSUE THREAD

**Issue by lj0307222** [immortalwrt/immortalwrt#936]
### Describe the bug

Run cd openwrt
[82](https://github.com/lj0307222/openwrtbuild/actions/runs/4781844868/jobs/8500657917#step:15:83)
2 thread compile
[83](https://github.com/lj0307222/openwrtbuild/actions/runs/4781844868/jobs/8500657917#step:15:84)
WARNING: Makefile 'package/emortal/default-settings/Makefile' has a dependency on 'luci-i18n-base-zh_Hans', which does not exist

### ImmortalWrt version

21.02

### ImmortalWrt target/subtarget

x84

### Device

x86

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
https://github.com/immortalwrt/immortalwrt/commit/14f80a84492d0cef5665fa81f13ae43d1a14e88a
不要自作聪明去修改 Makefile
