### ISSUE TITLE
R66s编译失败

### ISSUE THREAD

**Issue by Kaslana-Neko-charm** [immortalwrt/immortalwrt#940]
### Describe the bug

以下为编译日志
make[4]: Entering directory '/media/alex/R66s/immortalwrt/build_dir/target-aarch64_generic_musl/u-boot-fastrhino-r66s-rk3568/u-boot-2023.04'
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
scripts/kconfig/conf  --syncconfig Kconfig
  UPD     include/config.h
  CFG     u-boot.cfg
  GEN     include/autoconf.mk
  GEN     include/autoconf.mk.dep
  CFG     spl/u-boot.cfg
  GEN     spl/include/autoconf.mk
  UPD     include/config/uboot.release
  UPD     include/generated/version_autogenerated.h
  UPD     include/generated/timestamp_autogenerated.h
  UPD     include/generated/dt.h
  ENVC    include/generated/env.txt
  ENVP    include/generated/env.in
  ENVT    include/generated/environment.h
  CC      lib/asm-offsets.s
  UPD     include/generated/generic-asm-offsets.h
  CC      arch/arm/lib/asm-offsets.s
  UPD     include/generated/asm-offsets.h
  SHIPPED scripts/dtc/pylibfdt/libfdt.i
  PYMOD   rebuild
Traceback (most recent call last):
  File "/media/alex/R66s/immortalwrt/build_dir/target-aarch64_generic_musl/u-boot-fastrhino-r66s-rk3568/u-boot-2023.04/scripts/dtc/pylibfdt/setup.py", line 23, in <module>
    from setuptools import setup, Extension
ModuleNotFoundError: No module named 'setuptools'
make[6]: *** [scripts/dtc/pylibfdt/Makefile:33: rebuild] Error 1
make[5]: *** [scripts/Makefile.build:397: scripts/dtc/pylibfdt] Error 2
make[4]: *** [Makefile:2003: scripts_dtc] Error 2
make[4]: Leaving directory '/media/alex/R66s/immortalwrt/build_dir/target-aarch64_generic_musl/u-boot-fastrhino-r66s-rk3568/u-boot-2023.04'
make[3]: *** [Makefile:204: /media/alex/R66s/immortalwrt/build_dir/target-aarch64_generic_musl/u-boot-fastrhino-r66s-rk3568/u-boot-2023.04/.built] Error 2
make[3]: Leaving directory '/media/alex/R66s/immortalwrt/package/boot/uboot-rockchip'
time: package/boot/uboot-rockchip/fastrhino-r66s-rk3568/compile#7.51#3.60#9.74
    ERROR: package/boot/uboot-rockchip failed to build (build variant: fastrhino-r66s-rk3568).
make[2]: *** [package/Makefile:116: package/boot/uboot-rockchip/compile] Error 1
make[2]: Leaving directory '/media/alex/R66s/immortalwrt'
make[1]: *** [package/Makefile:110: /media/alex/R66s/immortalwrt/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/media/alex/R66s/immortalwrt'
make: *** [/media/alex/R66s/immortalwrt/include/toplevel.mk:231：world] 错误 2

### ImmortalWrt version

master

### ImmortalWrt target/subtarget

R66s

### Device

debian11

### Image kind

Official downloaded image

### Steps to reproduce

编译就会发生此错误

### Diffconfig

```text
#!/bin/sh
make ./scripts/config/conf >/dev/null || { make ./scripts/config/conf; exit 1; }
grep \^CONFIG_TARGET_ .config | head -n3 > tmp/.diffconfig.head
grep \^CONFIG_TARGET_DEVICE_ .config >> tmp/.diffconfig.head
grep '^CONFIG_ALL=y' .config >> tmp/.diffconfig.head
grep '^CONFIG_ALL_KMODS=y' .config >> tmp/.diffconfig.head
grep '^CONFIG_ALL_NONSHARED=y' .config >> tmp/.diffconfig.head
grep '^CONFIG_DEVEL=y' .config >> tmp/.diffconfig.head
grep '^CONFIG_TOOLCHAINOPTS=y' .config >> tmp/.diffconfig.head
grep '^CONFIG_BUSYBOX_CUSTOM=y' .config >> tmp/.diffconfig.head
grep '^CONFIG_TARGET_PER_DEVICE_ROOTFS=y' .config >> tmp/.diffconfig.head
./scripts/config/conf --defconfig=tmp/.diffconfig.head -w tmp/.diffconfig.stage1 Config.in >/dev/null
./scripts/kconfig.pl '>+' tmp/.diffconfig.stage1 .config >> tmp/.diffconfig.head
./scripts/config/conf --defconfig=tmp/.diffconfig.head -w tmp/.diffconfig.stage2 Config.in >/dev/null
./scripts/kconfig.pl '>' tmp/.diffconfig.stage2 .config >> tmp/.diffconfig.head
cat tmp/.diffconfig.head
rm -f tmp/.diffconfig tmp/.diffconfig.head
```

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
依赖没装全，自己看 readme
