### ISSUE TITLE
R66还是无法编译

### ISSUE THREAD

**Issue by xiaobaishu1** [immortalwrt/immortalwrt#944]
### Describe the bug

18.04乌班图编译不过

### ImmortalWrt version

master

### ImmortalWrt target/subtarget

无

### Device

电牛子R66S

### Image kind

Self-built image

### Steps to reproduce

make[4]: Entering directory '/home/openwrt/immortalwrt/build_dir/target-aarch64_generic_musl/u-boot-fastrhino-r66s-rk3568/u-boot-2023.04'
  ENVC    include/generated/env.txt
  ENVP    include/generated/env.in
  ENVT    include/generated/environment.h
  PYMOD   rebuild
Traceback (most recent call last):
  File "scripts/dtc/pylibfdt/setup.py", line 23, in <module>
    from setuptools import setup, Extension
ModuleNotFoundError: No module named 'setuptools'
scripts/dtc/pylibfdt/Makefile:30: recipe for target 'rebuild' failed
make[6]: *** [rebuild] Error 1
scripts/Makefile.build:397: recipe for target 'scripts/dtc/pylibfdt' failed
make[5]: *** [scripts/dtc/pylibfdt] Error 2
Makefile:2003: recipe for target 'scripts_dtc' failed
make[4]: *** [scripts_dtc] Error 2
make[4]: Leaving directory '/home/openwrt/immortalwrt/build_dir/target-aarch64_generic_musl/u-boot-fastrhino-r66s-rk3568/u-boot-2023.04'
Makefile:205: recipe for target '/home/openwrt/immortalwrt/build_dir/target-aarch64_generic_musl/u-boot-fastrhino-r66s-rk3568/u-boot-2023.04/.built' failed
make[3]: *** [/home/openwrt/immortalwrt/build_dir/target-aarch64_generic_musl/u-boot-fastrhino-r66s-rk3568/u-boot-2023.04/.built] Error 2
make[3]: Leaving directory '/home/openwrt/immortalwrt/package/boot/uboot-rockchip'
time: package/boot/uboot-rockchip/fastrhino-r66s-rk3568/compile#0.51#0.51#1.18
    ERROR: package/boot/uboot-rockchip failed to build (build variant: fastrhino-r66s-rk3568).
package/Makefile:118: recipe for target 'package/boot/uboot-rockchip/compile' failed
make[2]: *** [package/boot/uboot-rockchip/compile] Error 1
make[2]: Leaving directory '/home/openwrt/immortalwrt'
package/Makefile:114: recipe for target '/home/openwrt/immortalwrt/staging_dir/target-aarch64_generic_musl/stamp/.package_compile' failed
make[1]: *** [/home/openwrt/immortalwrt/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/openwrt/immortalwrt'
/home/openwrt/immortalwrt/include/toplevel.mk:229: recipe for target 'world' failed
make: *** [world] Error 2

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
RTFM
