### ISSUE TITLE
这个兼容高通msmxx/msm8916  平台吗？

### ISSUE THREAD

**Issue by zzduci** [immortalwrt/immortalwrt#969]
### Describe the bug

这个兼容高通msmxx/msm8916  平台吗？

### ImmortalWrt version

21.02

### ImmortalWrt target/subtarget

r19892-a6dce2ceb7

### Device

msmxx/msm8916 

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
目前 ImmortalWrt 项目暂无添加 msm8916 支持的计划，感谢您的关注。
