### ISSUE TITLE
静态编译的执行文件，无法在启用 procd jail 的情况下启动

### ISSUE THREAD

**Issue by wy580477** [immortalwrt/immortalwrt#970]
### Describe the bug

在 procd 服务文件添加 procd_add_jail mosdns log requirejail 后，静态编译的 mosdns 无法启动。

Mon Jun  5 15:09:51 2023 user.err : jail: failed to load the .dynamic section from /opt/bin/mosdns
Mon Jun  5 15:09:51 2023 daemon.err mosdns[5987]: jail: failed to load the .dynamic section from /opt/bin/mosdns
Mon Jun  5 15:09:51 2023 user.err : jail: failed to load dependencies
Mon Jun  5 15:09:51 2023 daemon.err mosdns[5987]: jail: failed to load dependencies
Mon Jun  5 15:09:56 2023 user.err : jail: failed to load the .dynamic section from /opt/bin/mosdns
Mon Jun  5 15:09:56 2023 daemon.err mosdns[6037]: jail: failed to load the .dynamic section from /opt/bin/mosdns

### ImmortalWrt version

r20007-6e54cb5d37

### ImmortalWrt target/subtarget

ramips/mt7621

### Device

Xiaomi Mi Router CR6608

### Image kind

Official downloaded image

### Additional info

官方仓库相关讨论： https://github.com/openwrt/openwrt/issues/10933

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
should be fixed by 7cf66961200a6f36409255bd3182b40e90f836ec
