### ISSUE TITLE
使用omcproxy组播代理，看组播四分钟断流

### ISSUE THREAD

**Issue by 13528943945** [immortalwrt/immortalwrt#971]
### Describe the bug

omcproxy组播代理软件零配置，luci界面选择上下行接口，局域网内即可播放rtp://239.x.x.x:x的组播流。无需像igmpproxy啰啰嗦嗦配置一大堆的东西，甚至防火墙都无需Allow-IGMP
问题点如题：使用omcproxy组播代理，看组播四分钟断流
问题分析：能看组播，说明信号通道没毛病。断流原因大概率出在组播续订信息被防火墙阻挡而无法到达组播服务器
也尝试过br-lan网桥启用igmp侦听，但系统无法保存并引发自动回退
提示1：用igmpproxy也可以调通组播，但也是四分钟断流
提示2：用udpxy看组播转单播，并设置2分钟续订，如option mcsub_renew '120'，则一直观看不断流！

我的配置如下：
配置路径：etc/config/network
config interface 'iptv'
	option proto 'static'
	option device 'wan.45'
	option ipaddr '192.168.1.2'
	option netmask '255.255.255.0'

配置路径：etc/config/omcproxy
config proxy
	option uplink 'iptv'
	option downlink 'lan'

配置路径：etc/config/firewall
config zone
	option name 'wan'
	option input 'REJECT'
	option output 'ACCEPT'
	option forward 'REJECT'
	option masq '1'
	option mtu_fix '1'
	list network 'wan'
	list network 'wan6'
	list network 'iptv'

顺便贴一下udpxy的配置（与主题无关）
config udpxy
	option disabled '0'
	option respawn '1'
	option status '1'
	option port '4022'
	option source 'wan.45'
	option mcsub_renew '120'

### ImmortalWrt version

测试几个版本都这样

### ImmortalWrt target/subtarget

MT7621

### Device

ZTE_E8820S

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
https://github.com/rozhuk-im/msd_lite/issues/4
